### ISSUE TITLE
Possible conflict between SQLPS and SqlServer PS modules

### ISSUE THREAD

**Issue by arcotek-ltd** [dsccommunity/SqlServerDsc#1097]
#### Details of the scenario you tried and the problem that is occurring
When using the resource MSFT_SqlRS, I get the following output in DSC logs:

```
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Preferred module SqlServer found.
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Importing PowerShell module SqlServer.
The 'Invoke-Sqlcmd' command was found in the module 'SQLPS', but the module could not be loaded. For more information, run 'Import-Module SQLPS'.
The 'Invoke-Sqlcmd' command was found in the module 'SQLPS', but the module could not be loaded. For more information, run 'Import-Module SQLPS'.
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = "MSSQLSERVER"),'methodName' = SetDatabaseConnection,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'.
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Operation 'Invoke CimMethod' complete.
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = "MSSQLSERVER"),'methodName' = InitializeReportServer,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'.
[AUCADN102002076]:                            [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB] Operation 'Invoke CimMethod' complete.
[AUCADN102002076]: LCM:  [ End    Set      ]  [[SqlRS]ConfigureRSDatabase::[crAxDbConfig]AXR3Database::[crRoleAxDBServer]ConfigureAxDB]  in 60.1810 seconds.
PowerShell DSC resource MSFT_SqlRS  failed to execute Set-TargetResource functionality with error message: Method InitializeReportServer() failed with an error. Error: The report server cannot open a connection to the report server database. A connection to the database is required for all requests and processing. (rsReportServerDatabaseUnavailable);Login failed for user 'contoso\AUCADN102002076$'. (HRESULT:-2146233088) 

```

For some reason `Invoke-SqlCmd` seems to be trying to get the cmdlet from SQLPS and not SqlServer. In `SqlRs`'s Set-TargetResource, I see the lines:
```
Import-SQLPSModule
Invoke-Sqlcmd -ServerInstance $reportingServicesConnection -Query $reportingServicesDatabaseScript.Script
                Invoke-Sqlcmd -ServerInstance $reportingServicesConnection -Query $reportingServicesDatabaseRightsScript.Script
```

If I do `Import-Module SqlServer -Verbose -Force`, I get the error:
```
PS C:\> Import-Module sqlserver -verbose -force
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\sqlserver\21.0.17224\sqlserver.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\sqlserver\21.0.17224\sqlprovider.types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\sqlserver\21.0.17224\sqlprovider.format.ps1xml'.
Import-Module : The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultKeyPropertySet is already present.
Error in TypeData "Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultDisplayPropertySet is already present.
Error in TypeData "Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultDisplayProperty is already present.
At line:1 char:1
+ Import-Module sqlserver -verbose -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
```

A quick Google suggests SQLPS and SqlServer modules are incompatible. At this point, SQLPS is loaded.
If I `Remove-Module SQLPS` and then `Import-Module SqlServer -Verbose -Force` SqlServer module loads without issue.

I am adding `Remove-Module SQLPS` to the function `Import-SQLPSModule` (SqlServerDscHelper.psm1) and see if this resolves the issue. I'll update here with my progress.

What I also note, is that when DSC comes around for the next pass, it succeeds. When I log on to the server, `Get-Module` shows `SQLPS` and not `SqlServer`. Maybe `Import-SQLPSModule` is confusing it.

#### The DSC configuration that is using the resource (as detailed as possible)
```
    SqlRS ConfigureRSDatabase
    {
        InstanceName = $DBSettings.SqlInstanceName
        DatabaseServerName = $DatabaseServerName
        DatabaseInstanceName = $DBSettings.SqlInstanceName

        PsDscRunAsCredential = $DynamicsInstallUserCredential
    }
```

#### Version of the operating system and PowerShell the target node is running
```
PS C:\> Get-CimInstance -ClassName 'Win32_OperatingSystem' | ft Caption,OSArchitecture,Version,MUILanguages,{$PSVersionTable.PSVersion}

Caption                                     OSArchitecture Version  MUILanguages $PSVersionTable.PSVersion
-------                                     -------------- -------  ------------ -------------------------
Microsoft Windows Server 2012 R2 Datacenter 64-bit         6.3.9600 {en-US}      5.1.14409.1005     
```

#### SQL Server edition and version the target node is running
```
Edition  : Enterprise Edition: Core-based Licensing
Version  : 13.0.1601.5
Language : 1033
```

#### What SQL Server PowerShell modules, and which version, are present on the target node.
```
Name         Version    Path                                                                                                   
----         -------    ----                                                                                                   
SqlServer    21.0.17224 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.0.17224\SqlServer.psd1                         
SQLASCMDLETS 2.0        C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1
SQLPS        1.0        C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1   
```

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
```
Name         Version  Path                                                                              
----         -------  ----                                                                              
SqlServerDsc 11.1.0.2 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\11.1.0.2\SqlServerDsc.psd1
```

**Comment by arcotek-ltd** [comment]
My change has resolved the modules error, but not the error:

 `failed to execute Set-TargetResource functionality with error message: Method InitializeReportServer() failed with an error`

The change I made to `SqlServerDscHelper.psm1`, `Import-SQLPSModule`:
`if($oldModule)`
```
function Import-SQLPSModule
{
    [CmdletBinding()]
    param
    (
    )

    $module = (Get-Module -FullyQualifiedName 'SqlServer' -ListAvailable).Name
    if ($module)
    {
        Write-Verbose -Message ($script:localizedData.PreferredModuleFound) -Verbose
        
        #SQLPS and SqlServer are incompatible, therefore remove old module.
        $oldModule = Get-Module -Name "SQLPS"
        if($oldModule)
        {
            Write-Verbose -Message "SQLPS module loaded. Removing..." -Verbose
            
            Try
            {
                Remove-Module -Name SQLPS -Verbose -Force -ErrorAction Stop
            }
            Catch
            {
                $errorMessage = "Unable to remove SQLPS module. It may still be loaded!"
                New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
            }
        }
    }
    else
    {
        Write-Verbose -Message ($script:localizedData.PreferredModuleNotFound) -Verbose

        <#
            After installing SQL Server the current PowerShell session doesn't know about the new path
            that was added for the SQLPS module.
            This reloads PowerShell session environment variable PSModulePath to make sure it contains
            all paths.
        #>
        $env:PSModulePath = [System.Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')

        $module = (Get-Module -FullyQualifiedName 'SQLPS' -ListAvailable).Name
    }

    if ($module)
    {
        try
        {
            Write-Debug -Message ($script:localizedData.DebugMessagePushingLocation)
            Push-Location

            Write-Verbose -Message ($script:localizedData.ImportingPowerShellModule -f $module) -Verbose

            <#
                SQLPS has unapproved verbs, disable checking to ignore Warnings.
                Suppressing verbose so all cmdlet is not listed.
            #>
            Import-Module -Name $module -DisableNameChecking -Verbose:$False -ErrorAction Stop

            Write-Debug -Message ($script:localizedData.DebugMessageImportedPowerShellModule -f $module)
        }
        catch
        {
            $errorMessage = $script:localizedData.FailedToImportPowerShellSqlModule -f $module
            New-InvalidOperationException -Message $errorMessage -ErrorRecord $_
        }
        finally
        {
            Write-Debug -Message ($script:localizedData.DebugMessagePoppingLocation)
            Pop-Location
        }
    }
    else
    {
        $errorMessage = $script:localizedData.PowerShellSqlModuleNotFound
        New-InvalidOperationException -Message $errorMessage
    }
}
```

**Comment by Jetski5822** [comment]
Im hitting this too - did anyone have a work around?

**Comment by johlju** [comment]
This was closed by the stale bot since the issue needed more information. 
Could you provide the configuration and verbose log output of the problem you are seeing, then it could be easier to see what’s going on.

**Comment by Jetski5822** [comment]
Hey - Sure.... I do this...

```
    if ((Get-Module -Name "SQLPS")) {
        Write-Host "Removing SQLPS"
        Remove-Module SQLPS
    }

    if (!(Get-Module -Name "SqlServer")) {
        Write-Host "Importing SQLServer module"
    
        Import-Module (Join-Path $PSScriptRoot "sqlserver.21.1.18135\SqlServer.psm1")
    }
```

Before calling;

```
		Set-RsDatabase `
			-ReportServerInstance "$ReportServerInstance" `
			-ReportServerVersion SQLServer2017 `
			-DatabaseServerName "$SQLServerName" `
			-DatabaseName "ReportServer" `
			-DatabaseCredentialType SQL `
			-DatabaseCredential $dbCredentials `
			-Confirm:$false `
			-Verbose
```

![image](https://user-images.githubusercontent.com/619530/60995810-37780d00-a34b-11e9-99a6-e2410d2011ae.png)

I have other code that relies on the SQLServer module being loading, any thoughts?

**Comment by johlju** [comment]
Okay, so you having an issue with this outside of DSC. So this is probably an issue with SQLPS is on the module paths before the SqlServer one 🤔
It looks like in your example that it is the Set-RsDatabase that calls Invoke-Sqlcmd. Wonder if it does that in a different user context (session) than the one you import SqlServer into. Wonder if it runs under the database Credential you provided to the cmdlet. 

I would try switching the paths in $PSModulePath so the path where SqlServer exist is before the SQLPS ones (if more than one). Then run in a new PowerShell session to make sure it gets the new path order. 🤔

**Comment by Jetski5822** [comment]
So I have simplified the code a bit...

```
Import-Module (Join-Path $ModulesPath "reportingservices.0.0.5.0\ReportingServicesTools.psm1")
Import-Module (Join-Path $ModulesPath "sqlserver.21.1.18135\SqlServer.psm1")

$dbCredentialsPW = ConvertTo-SecureString -AsPlainText -Force $SqlServerLoginPassword
$dbCredentials = New-Object System.Management.Automation.PSCredential($SqlServerLogin, $dbCredentialsPW)

Set-RsDatabase `
	-ReportServerInstance "$ReportServerInstance" `
	-ReportServerVersion SQLServer2017 `
	-DatabaseServerName "$SQLServerName" `
	-DatabaseName "ReportServer" `
	-DatabaseCredentialType SQL `
	-DatabaseCredential $dbCredentials `
	-Confirm:$false `
	-Verbose
```

I get the same error... If I change

Import-Module (Join-Path $ModulesPath "reportingservices.0.0.5.0\ReportingServicesTools.psm1")
Import-Module (Join-Path $ModulesPath "sqlserver.21.1.18135\SqlServer.psm1")

to

Import-Module (Join-Path $ModulesPath "sqlserver.21.1.18135\SqlServer.psm1")
Import-Module (Join-Path $ModulesPath "reportingservices.0.0.5.0\ReportingServicesTools.psm1")

I get the same error again.

**Comment by Jetski5822** [comment]
This line

> Import-Module (Join-Path $ModulesPath "sqlserver.21.1.18135\SqlServer.psm1")

is what is breaking it.... if I remove it, this function works fine, but if I put it back, it breaks again

**Comment by johlju** [comment]
You should just just `Import-Module -Name SqlServer` so it imports the correct assemblies and so on. Make sure SqlServer is in path in the $env:PSModulePath.

**Comment by johlju** [comment]
Don’t think the SqlServer module has a (public) GitHub repo. I know bugs can be reported on the comment section in PowerShell Gallery, and also here https://feedback.azure.com/forums/908035-sql-server/filters/new?category_id=325153

**Comment by Jetski5822** [comment]
I have to use it offline im afraid - sucks but for good reason.

I have added it to  $env:PSModulePath; like so... to test;

```
		$env:PSModulePath = $env:PSModulePath + ";" + (Join-Path $ModulesPath "sqlserver.21.1.18135")

		Import-Module (Join-Path $ModulesPath "reportingservices.0.0.5.0\ReportingServicesTools.psm1")
		Import-Module (Join-Path $ModulesPath "sqlserver.21.1.18135\SqlServer.psm1")
		
		Write-Host $env:PSModulePath 
```

Still hitting the same issue :/ so weird.

**Comment by Jetski5822** [comment]
Ah - I see what you mean by import module, good idea :) - same issue, but still, nicer code!

**Comment by aistvan** [comment]
I have the same problem.

`PS C:\Windows\system32> Get-Module SqlServer -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     21.1.18229 SqlServer                           {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvail...

PS C:\Windows\system32> Get-Module SQLPS -ListAvailable


    Directory: C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0        SQLPS                               {Backup-SqlDatabase, Save-SqlMigrationReport, Add-SqlAvail...


    Directory: C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   14.0       SQLPS                               {Backup-SqlDatabase, Save-SqlMigrationReport, Add-SqlAvail...`

When I tried to import SQLPS:

`PS C:\Windows\system32> Import-Module SQLPS
Import-Module : The following error occurred while loading the extended type data file: Error in TypeData
"Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultKeyPropertySet is already present.
Error in TypeData "Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultDisplayPropertySet is already present.
Error in TypeData "Microsoft.SqlServer.Management.Smo.NamedSmoObject": The member DefaultDisplayProperty is already present.
At line:1 char:1
+ Import-Module SQLPS
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand`
