### ISSUE TITLE
New resource proposal: Server and database audit 

### ISSUE THREAD

**Issue by imarambiocatan** [dsccommunity/SqlServerDsc#1132]
I've been trying to use this module alongside with DSCEA to check for compliance which means I have an SQL server environment already and have run into some issues
the first is that right now the SQLserverlogin resource requires a the name of the user to check for compliance with the various password policy options. I solved this using a lot of imagination and connecting to the various SQL server instances to generate several mof files, one per computer. This one won't be fixed in all likelyhood
the second is that I have yet to find how to configure the database audit policy with DSC. is this even possible?

**Comment by johlju** [comment]
@imarambiocatan Is it [SQL Server Audit (Database Engine)](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-2017) you are looking if there are support for? If so, there are no resource that handles this yet. It would be possible to add a resource for this when looking at [Creating and Managing Audits with Transact-SQL](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-2017#creating-and-managing-audits-with-transact-sql).

**Comment by imarambiocatan** [comment]
Yes, that is correct, that is what I'm looking for. Is there another way to do this? within dsc i mean

**Comment by johlju** [comment]
There are no DSC resource for this, so currently no. I labeled it help wanted so that anyone in the community can run with it.

**Comment by Fiander** [comment]
Hi,
just started with this for myself and just found this issue.
I have the audit ( the storage part ) running.

I am now starting with the serverAuditSpecifications part. the databaseAuditSpecifications part  wil be last.
[https://github.com/Fiander/SqlServerDsc](https://github.com/Fiander/SqlServerDsc)

**Comment by johlju** [comment]
Cool! Happy to review a PR if you want to send it in here.
