### ISSUE TITLE
SqlLogin: can I use gMSA?

### ISSUE THREAD

**Issue by joshan1120** [dsccommunity/SqlServerDsc#1207]
ISSUE TITLE:
    MSFT_SqlServerLogin: can I use gMSA? I cannot seem to get it to work...

    ISSUE DESCRIPTION (this template):
   I am trying to set a gMSA account as a Sql Domain Account, as we are using that for SQL auth now in databases. However, it does not seem to work as by default "Service accounts" are not selected.

VERBOSE: [2018-08-27 23:09:36Z] [ERROR] PowerShell DSC resource 
MSFT_SqlServerLogin  failed to execute Set-TargetResource functionality with 
error message: Creation of the Windows login 'MyDomain\gMSAsqlservice$' failed due 
to an unspecified error. 

For it to work in SQL I have to go in and change the "location" to entire directory, and change"Object Type" to service accounts.

#### Details of the scenario you tried and the problem that is occurring

I am trying to add a gMSA account using SqlServerLogin

#### The DSC configuration that is using the resource (as detailed as possible)

foreach ($sqlDomainAuthAccounts in $environmentNode.sqlServerDomainAccounts) {
			SqlServerLogin "SqlDomainAccounts($sqlDomainAuthAccounts)" {
				ServerName = $env:COMPUTERNAME
				InstanceName = $environmentNode.sqlInstanceName
				ensure = 'Present'
				LoginType = 'WindowsUser'
				Name = "$($sqlDomainAuthAccounts)"
				DependsOn = "[SqlSetup]SqlServerSetup"
			}
		}

sqlServerDomainAccounts = @('MyDomain\gMSAsqlservice$')

#### Version of the operating system and PowerShell the target node is running

Caption                                  OSArchitecture Version    MUILanguages $PSVersionTable.PSVersion
Microsoft Windows Server 2016 Datacenter 64-bit         10.0.14393 {en-US}      5.1.14393.2395   

#### SQL Server edition and version the target node is running

Edition  : Developer Edition
Version  : 14.0.1000.169
Language : 1033

#### What SQL Server PowerShell modules, and which version, are present on the target node.

Name         Version Path                                                                                                                                                                                                 
SqlServer    20.0    C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psd1                                    
SQLASCMDLETS 2.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1
SQLPS        1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1              
SQLPS        14.0    C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1       

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

Name         Version                                                                                                                                  
SqlServerDsc 10.0.0.0

**Comment by johlju** [comment]
I need to test this myself, but I'm afraid I won't have time to do it for a while. So if someone else has an opportunity to verify if the code that adds as user works with a gMSA, or if a certain property must be set for the account to be added? It should just work as any other computer account or domain account? 🤔

**Comment by martin9700** [comment]
Apparently not too many people use gMSA's. I've run into the same issue with SqlLogin. My guess is the Microsoft.SqlServer.Management.Smo.Login object doesn't support MSA objects, only User Objects.

**Comment by johlju** [comment]
Closing as per previous comment. Thank you for confirming it works. 🙂
