### ISSUE TITLE
SqlMemory: Incorrect syntax near ';'

### ISSUE THREAD

**Issue by grpowershell** [dsccommunity/SqlServerDsc#1257]
#### Details of the scenario you tried and the problem that is occurring

When running DSC configuration using xSQLServerMemory resource, configuration not applied with error message complaining about 'Incorrect syntax near ';'.

#### Verbose logs showing the problem

2018/12/10 14:05:36Z: Message: The errors from user scripts: PowerShell DSC resource MSFT_xSQLServerMemory  failed to execute Set-TargetResource functionality with error message: 
Failed to alter the server configuration memory for EC2AMAZ-UA1RECS\MSSQLSERVER. InnerException: Exception calling 
"Alter" with "0" argument(s): "Alter failed for Server 'EC2AMAZ-UA1RECS'. " 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
Incorrect syntax near ';'. 
 Msg 102, Level 15, State 1, Procedure , Line 1.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
    + PSComputerName        : localhost

#### Suggested solution to the issue
 
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

xSQLServerMemory ConfigureSQLServerMaxMemory {
        SQLInstanceName = $Instance
        MaxMemory = $MaxMemory
        DynamicAlloc = $False
        DependsOn = '[xSQLServerSetup]InstallSqlServer2016DE'
    }

#### SQL Server edition and version the target node is running

SQL Server 2016 Developer Edition

#### SQL Server PowerShell modules present on the target node

SqlServer  21.1.18068 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18068\SqlServer.psd1
xSQLServer 9.1.0.0    C:\Program Files\WindowsPowerShell\Modules\xSQLServer\9.1.0.0\xSQLServer.psd1

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.14393.2608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

Name       Version Path
----       ------- ----
xSQLServer 9.1.0.0 C:\Program Files\WindowsPowerShell\Modules\xSQLServer\9.1.0.0\xSQLServer.psd1

**Comment by grpowershell** [comment]
I am just going to use the SqlServerMemory resource in the SqlServerDSC module. I don't know why I didn't use this before. Didn't know about it I suppose. Hopefully this will work.

**Comment by grpowershell** [comment]
It actually hasn't. What is wrong with what I am doing? Does the resource not like variables?

**Comment by johlju** [comment]
Can you please provide the verbose output from when you run the SqlServerMemory resource? The verbose output when running `Start-DscConfiguration` with the `-Wait -Verbose` parameters.

**Comment by grpowershell** [comment]
Hi the verbose output from SqlServerMemory is much the same as the output from the other resource, please see below;

2018/12/18 17:22:10Z: Message: The errors from user scripts: PowerShell DSC resource MSFT_SqlServerMemory  failed to execute Set-TargetResource functionality with error message: 
Failed to alter the server configuration memory for EC2AMAZ-4QMO857\MSSQLSERVER. InnerException: Exception calling 
"Alter" with "0" argument(s): "Alter failed for Server 'EC2AMAZ-4QMO857'. " 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

I am expecting the value of 120 to be passed to the resource using the variable.

**Comment by grpowershell** [comment]
I've been forced to use a Script resource executing a SQL query in order to set the max memory. Not a huge bother but it's annoying that this DSC resource simply doesn't seem to work - when you use variables at least as I haven't tried directly giving the 'MaxMemory' field a numerical value.

**Comment by SphenicPaul** [comment]
@grpowershell - Did/Do you still have problems/feedback with this (given it's nearly 2 years since raised)?

I've used the current [`SqlMemory`](https://github.com/dsccommunity/SqlServerDsc/tree/dfa1c7c90c6dde838f045038ab01599f354a70d2/source/DSCResources/DSC_SqlMemory) resource a number of times in the last year (and I'd guess a number of other users of this module would have) and haven't seen this error/exception thrown.

Is it worth closing this issue?

**Comment by johlju** [comment]
This resource have probably been refactored since this issue wich could or could not have fixed this. I'm closing this, and if this is still a problem then I'm happily reopen the issue.
