### ISSUE TITLE
SqlServerDsc: Add a new pipeline job to test SQL Server 2019 family

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1310]
#### Details of the scenario you tried and the problem that is occurring
Suggest we add another job that can be run in the AppVeyor build worker to test the SQL Server 2019 family. For example SQL Server 2019, Reporting Services 2019, Power BI Reporting Services 2019. Or at least for the last two, maybe different builds than what are installed on the two existing jobs.

*SQL Server 2019 is not yet available, but as soon as they are we should look into this.*

#### Verbose logs showing the problem
n/a

#### Suggested solution to the issue
Add a new job in appveyor.yml and add the necessary changes to the SqlSetup, SqlRSSetup, and SqlPBIRSSetup (when available). 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
n/a

#### SQL Server edition and version the target node is running
n/a

#### SQL Server PowerShell modules present on the target node
n/a

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by SphenicPaul** [comment]
@johlju - How quickly can SQL2019 be added to the integration tests (presumably now in Azure Pipelines)? - I guess more people/companies will be using this now and this will only increase (I'm starting to install these more so would be good to know this was being tested on that version).

My thoughts are that it would just be an update to the `azure-pipelines.yml` file, maybe adding additional conditions in this where they exist in the tests and fixing issues off the back of failing tests on SQL2019 (although there is no visablity of what these may be without running the tests for the first time).

It also looks like there are also ISOs for SQL2016 and SQL2017 specified in config within the `SqlSetup`, integration tests. Is there an equivalent SQL2019 ISO present (or can it be easily added?). Not currently sure where these are sourced from (and how).

**Comment by SphenicPaul** [comment]
Additionally, are there any plans to setup integration tests on resources (where relevant) against Azure SQL Database instances?

**Comment by johlju** [comment]
> @johlju - How quickly can SQL2019 be added to the integration tests (presumably now in Azure Pipelines)? - I guess more people/companies will be using this now and this will only increase (I'm starting to install these more so would be good to know this was being tested on that version).

I updated the issue title. To get a new job to run in Azure Pipelines:

1. Copy this section and replace job name and display name, also change the key `configuration:` to `Integration_SQL2019`.

https://github.com/dsccommunity/SqlServerDsc/blob/5ab05bd5c307eefa8374b4f1419b4bbacd51c91f/azure-pipelines.yml#L183-L249

2, For each integration tests that should run for SQL2019 change the list of categories to include `Integration_SQL2019`). It checks the environment variable set in the pipeline job.
```powershell
if (-not (Test-BuildCategory -Type 'Integration' -Category @('Integration_SQL2016','Integration_SQL2017', 'Integration_SQL2019')))
```

> It also looks like there are also ISOs for SQL2016 and SQL2017 specified in config within the `SqlSetup`, downloaded as part of the integration tests. Guess the SQL2019 equivalent needs adding also.

Yes, a public link to the evaluation ISO media is needed. Preferably a a link to a Microsoft CDN which probably download quicker in Azure Pipelines (if it uses the same CDN), but otherwise AWS is always helpful in the [quickstart-microsoft-sql](https://github.com/aws-quickstart/quickstart-microsoft-sql) which has a link to AWS cloud: https://github.com/aws-quickstart/quickstart-microsoft-sql/blob/1c13ae4bc55fd5ac13e407724a5f3b802ddb23fd/ci/sql-master-ds-defaults.json#L36

**Comment by johlju** [comment]
> Additionally, are there any plans to setup integration tests on resources (where relevant) against Azure SQL Database instances?

The problem here is that we need access to a tenant where we can create the instances, but if we have that then it would be great to test that too.. But I happily review integration tests that can be run manually by a user to their own tenants.

**Comment by johlju** [comment]
The exe can be download with this link:

https://download.microsoft.com/download/d/a/2/da259851-b941-459d-989c-54a18a5d44dd/SQL2019-SSEI-Dev.exe

Then run with this to download the iso:

```
.\SQL2019-SSEI-Dev.exe /ENU /Quiet /HideProgressBar /Action=Download /Language=en-US /MediaType=ISO /MediaPath=C:\Temp
```

Full help from the .exe:

```
SQL2019-SSEI-Dev.exe [/ENU] [/Help] [/IAcceptSqlServerLicenseTerms] [/Quiet] [/HideProgressBar] [/Verbose] [/ConfigurationFile=C:\Configuration.ini] [/Action=Install] [/Language=en-US] [/MediaType=ISO] [/InstallPath=c:\Program Files\Microsoft SQL Server] [/MediaPath=C:\SetupMedia]

ACTION                    Indicates the workflow when performing a unattended operation.
                          Allowed Values      : Install, Download
                          Supported Actions   : Any

CONFIGURATIONFILE         Specifies the ConfigurationFile to use.
                          Supported Actions   : Install

ENU                       Use this parameter to install the English version of SQL Server on a localized operating system.
                          Supported Actions   : Any

HELP                      Displays the usage options for unattended operations.
                          Alias               : ?
                          Supported Actions   : Any

HIDEPROGRESSBAR           Indicates a progress bar should not be displayed in an unattended install.
                          Alias               : HP
                          Supported Actions   : Any

IACCEPTSQLSERVERLICENSETERMS Required to acknowledge acceptance of the license terms.
                          Supported Actions   : Install

INSTALLPATH               Specifies the data directory for SQL Server data files.
                          Supported Actions   : Install

LANGUAGE                  Language choice for Install or Download operations.
                          Alias               : Lang
                          Allowed Values      : zh-CN, zh-TW, en-US, fr-FR, de-DE, it-IT, ja-JP, ko-KR, pt-BR, ru-RU, es-ES
                          Supported Actions   : Any

MEDIAPATH                 Location where SQL Server setup media will be downloaded and extracted to.
                          Supported Actions   : Any

MEDIATYPE                 Indicates the type of media to download when /Action=Download
                          Alias               : MT
                          Allowed Values      : ISO, CAB
                          Supported Actions   : Download

QUIET                     Specifies that SQL Server Installer runs in a quiet mode without any user interface. This is used for unattended operations.
                          Alias               : Q
                          Supported Actions   : Any

VERBOSE                   Logs verbose output to the console.
                          Alias               : V
                          Supported Actions   : Any
```

**Comment by SphenicPaul** [comment]
Great. Thanks for those.

I might try and pick this up when PR #1652 is merged/closed.

Finally, are there any concerns/considerations around build time/minutes/cost with having 3 SQL versions running/building in parallel? i.e. There's not a requirement to replace SQL2017 with SQL2019, for example?

**Comment by johlju** [comment]
No there is no problem running more jobs. I think we can have 6-8 jobs in parallel and then it starts queuing. Every job can run up to 6 hours. It’s all at no cost for public repos. 

So no need to replace any older OS. Would be awesome to have all current (of a Microsoft) supported versions of SQL in the pipeline. But adding SQL 2019 is high priority as it is the one starting to be used more as you mentioned.
