### ISSUE TITLE
SqlRSSetup: Document that the properties ProductKey and Edition is mutually exclusive 

### ISSUE THREAD

**Issue by cosmos500** [dsccommunity/SqlServerDsc#1386]
#### Details of the scenario you tried and the problem that is occurring
When i run it the script wants the edition and Product key. It does not state they are mandatory fields.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### SQL Server edition and version the target node is running
Sql 2016

#### SQL Server PowerShell modules present on the target node
5.1

#### The operating system the target node is running
windows server 2016

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
n/a

**Comment by johlju** [comment]
Neither is mandatory because you can use either to install. Edition to install a free edition, and the ProductKey to install a licensed edition.

https://github.com/PowerShell/SqlServerDsc/blob/0a91a406611d7fd6ee8a6d5a571d14d39b460d98/DSCResources/MSFT_SqlRSSetup/MSFT_SqlRSSetup.psm1#L292-L304

This could be documented better, I label this issue as documentation and help wanted so that someone in the community can resolve this in the documentation.

**Comment by cosmos500** [comment]
This is my code
SqlRSSetup 'InstallDefaultInstance'
                {
                    Action                = "Install"
                    InstanceName          = 'SSRS'
                    IAcceptLicenseTerms   = 'Yes'
                    SourcePath            = $node.SourcePath + "\SQLServerReportingServices.exe"
                    PsDscRunAsCredential  = $Node.InstallerServiceAccount
                }

but it fails asking for Product key and version

**Comment by johlju** [comment]
When you compile the configuration it will not ask for additional parameters. You need to provide them in the configuration with the rest of the parameters. See the example here https://github.com/PowerShell/SqlServerDsc/blob/dev/Examples/Resources/SqlRSSetup/1-InstallReportingServices.ps1

**Comment by cosmos500** [comment]
that is the same as my code except for the edition parameter. The edition parameter is not a required parameter so not sure why it is complaining

**Comment by johlju** [comment]
The Edition or ProductKey parameter is a mutually exclusive mandatory parameter, it is just not a mandatory parameter in the schema. The code is throwing an error saying you need to provide either Edition or ProductKey, right?

**Comment by cosmos500** [comment]
Yes both
