### ISSUE TITLE
SqlServerDsc: nuspec file versioning

### ISSUE THREAD

**Issue by da3210** [dsccommunity/SqlServerDsc#1394]
In the nuget pack that can be downloaded(https://www.powershellgallery.com/packages/SqlServerDsc/13.0.0.0), the versioning in the file sqlserverdsc.nuspec is 13.0.0 

When i used it in my own nuget repository and installing the sqlserverdsc I coudn't find the resources.

To fix the issue i had to change the sqlserverdsc.nuspec version to 13.0.0.0.

I am not sure if this is an issue but for me is worthy publishing it just in case someone else have the same "issue"

**Comment by johlju** [comment]
This was recently discussed here https://github.com/PowerShell/DscResources/issues/508. Hoping this will be solved in the (near) future.

**Comment by johlju** [comment]
This should be resolved now with the new CI/CD pipeline.
