### ISSUE TITLE
SqlMemory: Allow setting of dynamic value for min server memory.

### ISSUE THREAD

**Issue by johnmart82** [dsccommunity/SqlServerDsc#1397]
#### Details of the scenario you tried and the problem that is occurring
Setting a discrete value for min server memory rather than dynamically calculating it adds overhead when managing generic configurations that are applied to many servers. I have a baseline configuration that goes out with all servers. Currently I leave Min Server Memoryh to the default rathe than set a value in the configuration.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Allow for a dynamic calcualtion of min server memory based on a specific percentage of the max server memory value (discrete or dynamically calculated).

If I have a server with 128 GB of RAM and have a max server memory value of 105GB, I then want to say that I want a min server memory value that is 35% of the max server memory value so it should be calculated and set to ~36GB. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
N/A
```

#### SQL Server edition and version the target node is running
SQL 2016 & 2017 

#### SQL Server PowerShell modules present on the target node
N/A

#### The operating system the target node is running
Windows server 2016 & 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
13.0.0.0

**Comment by SQLCanuck** [comment]
It would also be useful to add the ability to use a percentage based allocation of total server memory, for the max server memory setting as well.  It would be useful in situations where multiple services (RS, AS, DB) or multiple instances are running on the same server.

**Comment by TrisBits** [comment]
@johlju  I can take a look into this issue, as a first time contributor.

**Comment by johlju** [comment]
Absolutely, go for it. Happy to review a PR for this, tag me when you are done. 😃

**Comment by TrisBits** [comment]
@johlju  PR submitted.  I expanded a little beyond the primary issue to include the comment by @SQLCanuck.  The PR therefore includes the ability to dynamically set min memory and/or max memory based on a specified percentage of total server memory.
