### ISSUE TITLE
SqlServerDsc rebooting before ssms is installed

### ISSUE THREAD

**Issue by cosmos500** [dsccommunity/SqlServerDsc#1399]
#### Details of the scenario you tried and the problem that is occurring
I have a script that installs sql and ssms. Nothing has changed in the script. It used to install ssms then reboot. Now it is rebooting before the install of ssms. What determines the timing on the reboo. I do not know why the reboot changed

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

LocalConfigurationManager
        {
            AllowModuleOverwrite = $true
            RebootNodeIfNeeded = $true
        }


Package SSMS
           {
                Ensure = "Present"
                Name = "SSMS-Setup-ENU"
                Path = $node.SourcePath + "\SSMS-Setup-ENU.exe"
                Arguments = "/install /passive /norestart"
                ProductId ="xxxxxxxxxxxxxxxxxxx" 
           }

#### SQL Server edition and version the target node is running
2016 DEV

#### SQL Server PowerShell modules present on the target node


#### The operating system the target node is running
SERVER 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by johlju** [comment]
If you look at the verbose output of the resource prior to installing, which resource are asking for the reboot? If it is SqlSetup then there are certain rules that make it want to reboot; setup exit with code 3010 (will be enabled in the future, today just write a warning) and pending file renames. It calls the helper function `Test-PendingRestart` to see if a restart is needed.

**Comment by cosmos500** [comment]
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Setup exited with code '0'. Setup finished successfully.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Rebooting target node.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Using path '\\isd-p-pws-v01\SQL2016Dev\setup.exe'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Database Engine feature.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Database Engine feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Servi
ce WHERE Name = 'MSSQLSERVER','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Operation 'Query CimInstances' complete.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Servi
ce WHERE Name = 'SQLSERVERAGENT','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Operation 'Query CimInstances' complete.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting replication feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL13.MSSQLSERVER\ConfigurationSt
ate).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Replication feature not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Data Services Client feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\DQ\*).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Data Quality Services feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Data Quality Client feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationState).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Data Quality Client feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Importing PowerShell module 'SQLPS' with version '1.0' from path 'M:\Program Files (x86)\Microsoft SQL Server\13
0\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Connected to SQL instance 'myserver'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Clustered instance not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Full-text feature.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Full-text feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Servi
ce WHERE Name = 'MSSQLFDLauncher','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Operation 'Query CimInstances' complete.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Reporting Services feature.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Reporting Services feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Servi
ce WHERE Name = 'ReportServer','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Operation 'Query CimInstances' complete.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Analysis Services feature.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Analysis Services feature not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Integration Services feature.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Integration Services feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM Win32_Servi
ce WHERE Name = 'MsDtsServer130','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Operation 'Query CimInstances' complete.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Documentation Components feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationState
).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Documentation Components feature not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Client Connectivity Tools feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\Tools\Setup\Clien
t_Components_Full).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Client Connectivity Tools feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Client Connectivity Backwards Compatibility Tools feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Serv
er\130\Tools\Setup\Client_Components_Full).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Client Connectivity Backwards Compatibility Tools feature detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Client Tools SDK feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\Tools\Setup\Client_Compone
nts_Full).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Client Tools SDK feature not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Detecting Master Data Services (MDS) feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\130\ConfigurationSta
te).
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Master Data Services (MDS) feature not detected.
VERBOSE: [myserver]:                            [[SqlSetup]myserver] Found features already installed: SQLENGINE,DQ,DQC,FULLTEXT,RS,IS,CONN,BC
VERBOSE: [myserver]: LCM:  [ End    Set      ]  [[SqlSetup]myserver]  in 1188.7010 seconds.
VERBOSE: [myserver]: LCM:  [ End    Resource ]  [[SqlSetup]myserver]
VERBOSE: [myserver]:                            [] A reboot is scheduled to progress further. Configuration will be continued after the reboot.

WARNING: [myserver]:                            [] A reboot is scheduled to progress further. Configuration will be continued after the reboot.
VERBOSE: [myserver]: LCM:  [ End    Set      ]
VERBOSE: [myserver]: LCM:  [ End    Set      ]    in  1199.2370 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1199.356 seconds

**Comment by johlju** [comment]
Probably file renames, either by the SQL setup or because of something else. 
https://blogs.technet.microsoft.com/brad_rutkowski/2007/06/27/are-there-pending-operations-waiting-for-a-reboot/

**Comment by johlju** [comment]
This is the code that if returning true, a restart will be triggered.

https://github.com/PowerShell/SqlServerDsc/blob/2d37a930d957d2bbe148d118a5065a2f6f33d29e/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L853-L871

**Comment by cosmos500** [comment]
the strange thing is i did not make any code changes and the reboot changed to before the ssms install. It was doing it after the ssms install before

**Comment by cosmos500** [comment]
what if i set RebootNodeIfNeeded = $false

**Comment by cosmos500** [comment]
the main reason i ask is because i have this piece of code at the end and now that the reboot happens to soon this code does not work because ssms is not installed.

**Comment by johlju** [comment]
`RebootNodeIfNeeded = $false` will make the LCM to never restart.

When the node reboots the configuration will run again, and it will install SSMS on the next run. If you have the Invoke call as the last step (in a Script resource?) then it should run after the reboot (or after the SSMS reboot).
If you want to suppress restart in the resource SqlSetup, if you have another way of rebooting, you can use `SuppressReboot`. Note that the instance might not be available until after reboot.

**Comment by johlju** [comment]
See parameters here: https://github.com/PowerShell/SqlServerDsc#parameters-32

**Comment by cosmos500** [comment]
I am trying suppress reboot as we speak, thanks
