### ISSUE TITLE
SqlServerNetwork: Add support for protocol configuration

### ISSUE THREAD

**Issue by jcgillespie** [dsccommunity/SqlServerDsc#14]
It would be very nice if I could specify that I wanted Named Pipes or TCP/IP enabled as part of my DSC.

This could be done as either additional parameters for each setup parameter or a single parameter that accepted a path to a configurationfile.ini.

The command line/configuration options for the network protocols have been present in the setup.exe since SQL 2008
[How to: Install SQL Server 2008 from the Command Prompt](https://msdn.microsoft.com/en-us/library/ms144259%28v=sql.100%29.aspx)

**Comment by Arturas-K** [comment]
@jcgillespie as of #20 merge you now have a new resource xSQLServerNetwork that lets you configure TCP/IP. At the moment it doesn't support NamedPipes/Shared Memory but you can enable and configure ports for TCP/IP.

This is not using setup parameters, but during setup you can only enable or disable protocols, with new resource you can modify port configuration.

**Comment by glennmate** [comment]
+1 on this, much needed

**Comment by johlju** [comment]
There are unit tests prepared for this change that is commented. 

https://github.com/PowerShell/SqlServerDsc/blob/a8cb7528153eb7d7246a41b97c7a28b831686ac5/Tests/Unit/MSFT_SqlServerNetwork.Tests.ps1#L165-L186

**Comment by johlju** [comment]
A suggested snippet for this was added to this https://github.com/PowerShell/SqlServerDsc/issues/1161#issuecomment-418921734. Today SqlServerNetwork uses `Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer`, maybe that can be used for Named Pipes as well?
