### ISSUE TITLE
SqlServerRole drops existing system logins!

### ISSUE THREAD

**Issue by KarimAlpha** [dsccommunity/SqlServerDsc#1405]
#### Details of the scenario you tried and the problem that is occurring
I am trying to add the predefined system login NT AUTHORITY\SYSTEM to the sysadmin role.
My configuration completes with an error as it tries to drop the predfined sa login!
I never asked to drop sa...
#### Verbose logs showing the problem
PowerShell DSC resource MSFT_SqlServerRole  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Failed to drop member 'sa' to the 
server role named 'sysadmin' on 'BEZAVWV80028\SQLDEV07'. ---> System.Management.Automation.MethodInvocationException: Exception calling "DropMember" with "1" argument(s): "Drop member 
failed for ServerRole 'sysadmin'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Drop member failed for ServerRole 'sysadmin'.  ---> 
Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Cannot 
use the special principal 'sa'.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.ServerRole.DropMember(String memberName)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.ServerRole.DropMember(String memberName)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace --- 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : BEZAVWV80028
 
#### Suggested solution to the issue
I found this piece of code in the powershell Gallery:

foreach ($memberName in $memberNamesInRoleObject)
                    {
                        if ( -not ($Members.Contains($memberName)))
                        {
                            Remove-SqlDscServerRoleMember -SqlServerObject $sqlServerObject `
                                -LoginName $memberName `
                                -ServerRoleName $ServerRoleName
                        }
                    }
It is there that it tries to remove sa.
You can find the code in https://www.powershellgallery.com/packages/SqlServerDsc/12.1.0.0/Content/DSCResources%5CMSFT_SqlServerRole%5CMSFT_SqlServerRole.psm1
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration InstallSqlServerSQLDEV07 {
 
    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName SqlServerDsc
    
    
    #$saCred = (Get-Credential -Credential sa)
    $InstanceName = 'SQLDEV07'
    $saUser = 'sa'
    $saPWord = ConvertTo-SecureString -String 'xxxxxx' -AsPlainText -Force
    $saCred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList($saUser, $saPWord)

    $User = 'xxxxx\xxxx'
    $PWord = ConvertTo-SecureString -String 'xxxxxx' -AsPlainText -Force
    $Cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList($User, $PWord)

    

    Node $AllNodes.NodeName {
        #WindowsFeature InstallDotNet {
        #    Name                = 'NET-Framework-Features'
        #    Ensure              = 'Present'
        #}
        
        File CreateDataDir {
            DestinationPath     = $ConfigurationData.NonNodeData.DataDir
            Ensure              = 'Present'
            Type                = 'Directory'
        }
        File CreateLogsDir {
            DestinationPath     = $ConfigurationData.NonNodeData.LogDir
            Ensure              = 'Present'
            Type                = 'Directory'
        }
        File CreateTempDataDir {
            DestinationPath     = $ConfigurationData.NonNodeData.TempDataDir
            Ensure              = 'Present'
            Type                = 'Directory'
        }

        File CreateTempLogDir {
            DestinationPath     = $ConfigurationData.NonNodeData.TempLogDir
            Ensure              = 'Present'
            Type                = 'Directory'
        }

       # LocalConfigurationManager 
       # { 
       #    CertificateId =  $ConfigurationData.AllNodes.Thumbprint 
       # } 
       
        SqlSetup InstallSql {
            InstanceName        = $InstanceName
            InstanceDir         = 'E:\Microsoft SQL Server' 
            INSTALLSHAREDDIR    = 'E:\Program Files\Microsoft SQL Server'
            INSTALLSHAREDWOWDIR = 'E:\Program Files (x86)\Microsoft SQL Server'
            SourcePath          = '\\fs-sunarchive\dbasoftware$\SQL2017\SQL 2017 Standard Edition'
            Features            = 'SQLENGINE,REPLICATION,FULLTEXT'
            SQLSysAdminAccounts = 'AVI-DC\GN-BRU-DatabaseAdministrators'
            BROWSERSVCSTARTUPTYPE='Automatic'
            SQLUserDBDir        = $ConfigurationData.NonNodeData.DataDir
            SQLUserDBLogDir     = $ConfigurationData.NonNodeData.LogDir
            SQLTempDBDir        = $ConfigurationData.NonNodeData.TempDataDir
            SQLBackupDir        = $ConfigurationData.NonNodeData.BackupDir
            SqlTempdbFileCount  = 1
            SqlTempdbFileGrowth = 256
            SqlTempdbFileSize   = 128
            SQLTempDBLogDir     = $ConfigurationData.NonNodeData.TempLogDir 
            SqlTempdbLogFileGrowth = 64 
            SqlTempdbLogFileSize   = 128
            SQLCollation           = 'SQL_Latin1_General_CP1_CI_AS'
            SecurityMode           = 'SQL'
            SAPwd                  = $saCred#(Get-Credential -Credential sa)
            UpdateEnabled          = 'True'
            UpdateSource           = '.\Updates'
            PsDscRunAsCredential   = $Cred#(Get-Credential -Credential avi-dc\operator-attaleb)
            SuppressReboot = $True

        }
        SqlServerNetwork EnableTcpIp {
            DependsOn           = '[SqlSetup]InstallSql'
            InstanceName        = $InstanceName
            ProtocolName        = 'Tcp'
            IsEnabled           = $true
            TCPPort             = 4102
            RestartService      = $true
        }

        SqlServerRole 'NT_AUTHORITY_SYSTEM'
        {
            InstanceName = $InstanceName
            ServerName   = $Node.NodeName
            ServerRoleName = 'sysadmin'
            DependsOn = '[SqlSetup]InstallSql'
            Members = 'NT AUTHORITY\SYSTEM'
            PsDscRunAsCredential = $Cred
        }
        
        SqlServerLogin 'disable_sa'
        {
            DependsOn    = '[SqlSetup]InstallSql'
            InstanceName = $InstanceName
            Name         = 'sa'
            ServerName   = $Node.NodeName
            Disabled     = $True
            
        }
       

        SqlDatabase 'kattaleb_db'
        {
            DependsOn    = '[SqlSetup]InstallSql'
            InstanceName = $InstanceName
            Name         = 'kattaleb'
            ServerName   = $Node.NodeName
            Ensure = 'Present'
        }

        Registry REG_NumErrorLogs
        {
            Key         = 'HKEY_LOCAL_MACHINE\Software\Microsoft\MSSQLServer\MSSQLServer'
            ValueName   = 'NumErrorLogs'
            ValueType   = 'DWORD'
            ValueData   = 12
        }

        
        $ConfigurationData.NonNodeData.ConfigOptions.foreach{
            SqlServerConfiguration ('SetConfigOption{0}' -f $_.name) {
                DependsOn       = '[SqlSetup]InstallSql'
                ServerName      = $Node.NodeName
                InstanceName    = $InstanceName
                OptionName      = $_.Name
                OptionValue     = $_.Setting
            }
        }
        
    }
}

InstallSqlServerSQLDEV07 -Output .\OutputMof\ -ConfigurationData .\ConfigData.psd1

#Write-Host 'Setting up LCM to decrypt credentials...'
#Set-DscLocalConfigurationManager  .\Output\ -Verbose

Start-DscConfiguration -Path .\OutputMof\ -Wait -Verbose -Force```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0 (X64)   Mar 11 2019 23:19:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
Name  Version Path                                                                                     
----  ------- ----                                                                                     
SQLPS 1.0     E:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
SQLPS 14.0    E:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2969.amd64fre.rs1_release.190503-1820
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                                        
----                           -----                                     
[config_data.txt](https://github.com/PowerShell/SqlServerDsc/files/3403143/config_data.txt)
                                                                                                                   
PSVersion                      5.1.14393.2969                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                      
BuildVersion                   10.0.14393.2969                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1    

#### Version of the DSC module that was used ('dev' if using current dev branch)
Name         Version  Path                                                                     
----         -------  ----                                                                     
SqlServerDsc 12.5.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\SqlServerDsc.psd1

**Comment by johlju** [comment]
It looks like you are using the `Members` property, I think you should use `MembersToInclude` in this case. 🤔 

With the `Members` property you say "this members, and only the members", so the resource want to remove all members from the role. Using `MembersToInclude` (and `MembersToExclude`) do not touch existing members.

**Comment by johlju** [comment]
@KarimAlpha you can see the documentation for the properties here https://github.com/PowerShell/SqlServerDsc#sqlserverrole

**Comment by KarimAlpha** [comment]
Hello Johan, many thanks for you timely reply. I will re-try and come back to you.
IMHO, the Members property can be a dangerous command. 
Nothing in its name suggest it may remove existing members. It would be safer to use MembersToInclude and MembersToExclude only. Im wondering if there's any added value in having the Members property.
Again, many thanks for your timely reponse. Much appreciated.

Karim
Senior Database administrator

**Comment by johlju** [comment]
The parameter `Members` can be used when you have a role that you only want specific users in. If there are members added or removed outside of DSC (for example in a another management tool), then the resource will add the missing user back into the role, or remove members that should not be in the role.

**Comment by malikadilahmed** [comment]
Hello Johan
I see you have contributed tremendously in sql server and I found some of the sql server dsc configurations you have shared, but I never found readme.txt that can explain how to run and execute them. Especially people who are new to PS DSC (like me) have very much difficulty. Could you please add couple of lines regarding how to run your DSC configuraion scripts.
Regards
Mali

**Comment by malikadilahmed** [comment]
> The parameter `Members` can be used when you have a role that you only want specific users in. If there are members added or removed outside of DSC (for example in a another management tool), then the resource will add the missing user back into the role or remove members that should not be in the role to get back to the desired state.

Hello Johan
I see you have contributed tremendously in sql server and I found some of the sql server dsc configurations you have shared, but I never found readme.txt that can explain how to run and execute them. Especially people who are new to PS DSC (like me) have very much difficulty. Could you please add couple of lines regarding how to run your DSC configuraion scripts.
Regards
Mali
