### ISSUE TITLE
SqlSetup: If you set a certain variable outside the resource definition it can screw up ResourceID generation and break DependsOn

### ISSUE THREAD

**Issue by cdeadspine** [dsccommunity/SqlServerDsc#1411]
#### Details of the scenario you tried and the problem that is occurring
Inside of a Node {} and outside of a SqlSetup Resource I set the variable $instanceName to something. This caused SqlSetup and other resources in the mof file to start adding "::[configuration]::[configuration]" to their ResourceIDs, breaking DependsOn 
#### Verbose logs showing the problem
ValidateNodeResources : Resource '[File]InstallDir::[configuration]::[configuration]' required by
'[SqlSetup]sql2014::[configuration]::[configuration]' does not exist.
#### Suggested solution to the issue
Magically know all variable names that you can not use inside of a Node definition.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
File InstallDir
{
...
}
$instanceName = "SQLExpress"
SqlSetup sql2014
{
...
DependsOn = "[File]InstallDir"
}
```

#### SQL Server edition and version the target node is running
N/A

#### SQL Server PowerShell modules present on the target node
N/A
#### The operating system the target node is running
N/A

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
SqlServerDsc 13.0.0.0

**Comment by johlju** [comment]
I did not know this. Thank you for sharing your finds, it will help other users. This must be the parser that uses that variable name internally. 🤔 
Suggest testing if this is an issue with the newly release PowerShell 7.0 preview 2, it should now be able to parse configurations I think. https://github.com/PowerShell/PowerShell/releases. If it is an issue could be added to the PowerShell repo.

This is external to this resource module, so labelling this external

**Comment by johlju** [comment]
Closing this issue as external.
