### ISSUE TITLE
Can this be used to install a driver (native client) on a remote machine?

### ISSUE THREAD

**Issue by pfoppe** [dsccommunity/SqlServerDsc#1421]
We are looking for a way to quickly install and upgrade the SQL Server 64-bit drivers on client machines.  Can the SqlServerDsc Module handle this situation?  Thanks!

**Comment by johlju** [comment]
That is a separate package right, if so no, not currently, but maybe either the resource xMsiPackage or xPackage in [xPSDesiredStateConfiguration](https://github.com/PowerShell/xPSDesiredStateConfiguration) can handle that?

Let me know if the above works, or if you feel a dedicated resource would be better here (and if so why a dedicated resource would be better). 🙂
