### ISSUE TITLE
SqlAG: Cannot create AG

### ISSUE THREAD

**Issue by emyatsuna** [dsccommunity/SqlServerDsc#1428]
Hi,
I am getting below error while running the script using Puppet. I was able to create a cluster, enable SQLAlwaysON service and SQL ServerEndpoint but failed to create AG group. I have SSMS and SQL ver2017 installed in my server. Any idea/ suggestions what should I do to resolve problem?

**My AG group creation script**
```
dsc_sqlag{'CreateSQLAvailabilityGroup':
      dsc_ensure => 'Present',
      dsc_name => 'MyAG',
      dsc_servername => 'myhost',
      dsc_instancename => 'SQL01',
      dsc_availabilitymode => 'SynchronousCommit',
      require => [ Dsc_sqlalwaysonservice['EnableAlwaysOn'] , Dsc_sqlserverendpoint['SQLServerEndpoint'] ]
    }
```

**Error Encountered**
```
Error: PowerShell DSC resource MSFT_SqlAG  failed to execute Set-TargetResource functionality with error message: Creating the availability group 'MyAG'. InnerException: An attempt to fai
l over or create an availability group failed. This operation is not supported when Always On Availability Groups is running under a remote Windows Server Failover Clustering (WSFC) cluster con
text. Under a remote cluster context, failing over or creating availability groups are not supported.
```

Thank you.

**Comment by johlju** [comment]
Looks like you hitting a SQL Server restriction. I have not seen that error before. Looks like the cluster is in a state that it does not like. 

Read up on it here, but doesn't say much that would help you I think;  https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/change-the-hadr-cluster-context-of-server-instance-sql-server?view=sql-server-2017

**Comment by johlju** [comment]
Not sure this will help either https://blog.dbi-services.com/sql-server-2016-distributed-availability-groups-and-cross-cluster-migration/

Sorry, not much big help here. I think you need to look at the logs of SQL Server to see what is going on.

**Comment by johlju** [comment]
Maybe this will help though; https://www.sqlservercentral.com/forums/topic/sql-server-2017-availability-group-without-windows-server-failover-clustering

Let me know if something is missing in the resources to get this working.
