### ISSUE TITLE
SqlAGDatabase: Database when added to a 2nd secondary replica does not sync

### ISSUE THREAD

**Issue by amitchettri** [dsccommunity/SqlServerDsc#1435]
#### Details of the scenario you tried and the problem that is occurring
I am using SqlAGDatabase with the win_dsc module in Ansible in order to add the databases to the AG. When i try to add the database **(already in sync in the AG between WIN_PRI-1(primary) and SEC-WIN-1(secondary)** in the 2nd replica SEC-WIN-2 using the SqlAGDatabase it gets added but does not sync

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SqlAGDatabase 'TestAGDatabaseMemberships'
            {
                       AvailabilityGroupName   = $Node.AvailabilityGroupName
                       BackupPath              = '\\SQL1\AgInitialize'
                       DatabaseName            = 'DB*', 'AdventureWorks'
                       InstanceName            = $Node.InstanceName
                       ServerName              = $Node.NodeName
                       Ensure                  = 'Present'
                       ProcessOnlyOnActiveNode = $true
                       PsDscRunAsCredential    = $SqlAdministratorCredential
            }
But the above i am passing as below via Ansible
- name: Add Database to Always On Availability Group in WINSER1
  win_dsc:
       resource_name: SqlAGDatabase
       DatabaseName: D*, Test*
       ServerName: WINSER1
       InstanceName: MSSQLSERVER
       AvailabilityGroupName: TEST_AG
       BackupPath: \\WINSER1\backup_demo
       Ensure: Present
       ReplaceExisting: true
```

#### SQL Server edition and version the target node is running
```
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64) 
```

#### SQL Server PowerShell modules present on the target node
```
Name      Version    Path
----      -------    ----
SqlServer 21.1.18147 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18121\SqlServer.psd1
SQLPS     14.0       C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2012 R2 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.17415.amd64fre.winblue_r4.141028-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.14409.1005                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14409.1005                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```
Name         Version  Path                                                     
----         -------  ----                                                     
SqlServerDsc 13.2.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.2.0.0\SqlServerDsc.psd1
```
<img width="652" alt="issue" src="https://user-images.githubusercontent.com/46727623/66160885-b5953880-e648-11e9-9fa8-71fe5f6f2c41.PNG">

**Comment by amitchettri** [comment]
Hi @johlju need your help.

**Comment by amitchettri** [comment]
Hi @johlju need your help.

**Comment by johlju** [comment]
@amitchettri sorry I been busy over at xWebAdministration. Can you see in the SQL logs why it does not sync? What does the warnings say I see in the screenshot, is it related?

**Comment by amitchettri** [comment]
Hi @johlju 

Let me simplify the issue more for better understanding. I have 3 server namely WIN-PRI-1 which is primary server where AG will be created, SEC-WIN-1 this is the 1st secondary replica and SEC-WIN-2 which is the 2nd replicate.

Below are the test I have done and in total i have 3 database (D1, D2 and Test1) in WIN-PRI-1

**1st run of DSC. I have only use WIN-PRI-1 & SEC-WIN-1**

- Here using **SqlAG** availability group is created in WIN-PRI-1 

- Using **SqlAGReplica** 1st secondary replica SEC-WIN-1 is added to the AG.

- Using **SqlAGDatabase** database D1, D2 and Test1 are added on to the AG in WIN-PRI-1 & SEC-WIN-1


**2nd run of DSC I have only use WIN-PRI-1 & SEC-WIN-2** (introducing a new server to add as a replica)

- Using **SqlAGReplica** 2nd secondary replica SEC-WIN-2 is added to the AG.

- Using **SqlAGDatabase** we try to add database D1, D2 and Test1 onto the AG in WIN-PRI-1 & SEC-WIN-2 I get the error as shown in my last screenshot. You can see the Availability Group state is not healthy and is showing a warning. If you look down the list, you will see the warning for the 2nd secondary replica SEC-WIN-2 whereas for 1st secondary replica SEC-WIN-2 we see green indicating a "Synchronized" state. Clicking on the "Warnings" link to get more details I see that the issue is due to the synchronization issue between the availability databases on the primary and this secondary replica (SEC-WIN-2) 

Issue is very similar to https://www.mssqltips.com/sqlservertip/4687/fix-sql-server-alwayson-availability-group-error-1408-joining-database-on-secondary-replica-resulted-in-an-error/

For the DSC module i am using the parameter **ReplaceExisting: true in SqlAGDatabase** so that the restore happen **WITH NORECOVERY, REPLACE** but it does not work.

**Comment by johlju** [comment]
Looking at the link you provided, the solution to that issue is to backup and restore the databases on the secondary (SEC-WIN-2). This backup and restore should be done by the resource, but is it a problem when it does that? 🤔 Can you get any error message from the resource when running against SEC-WIN-2? For example can you found any output in the folder `C:\Windows\System32\Configuration\ConfigurationStatus` that can help us. The verbose output from the resource would be tremendously helpful. Also if the SQL Error Log says anything that can be helpful. 

We need to figure out if there is a problem when the resource is run due to SQL configuration issue, or a bug in the resource.

**Comment by andyt98** [comment]
@amitchettri @johlju Is there any solution to this issue?

**Comment by johlju** [comment]
@andyt98 can you provide more information any errors or problems related to this that you have? See comment https://github.com/dsccommunity/SqlServerDsc/issues/1435#issuecomment-541733167.
