### ISSUE TITLE
SqlScriptQuery: "ErrorActionPreference" or common parameter is set to Stop

### ISSUE THREAD

**Issue by emyatsuna** [dsccommunity/SqlServerDsc#1449]
Hi,
I'm getting below error when trying to execute `SqlScriptQuery`. I did a testing to include `ErrorActionPreference ` or `Error `parameter but the resource won't accept it. Any way to move forward with this one? Thanks.

**My Snippet**
```
sqlscriptquery{ "sqlscriptquerytest":
     serverinstance = 'hostname\MSSQLSERVER',
     testquery = $msquery,
     getquery = $msquery,
     setquery = $msquery,
     variable = 'ErrorAction=Start',
}
```

**ERROR**
 ```
Wrapped exception:
 PowerShell DSC resource MSFT_SqlScriptQuery  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A RETURN statement with a return value cannot be used in this context.
```

**Comment by johlju** [comment]
The important part of the error message is the last part "A RETURN statement with a return value cannot be used in this context". You are using a TSQL script that uses the `RETURN` statement in apparently an invalid way. 🙂

**Comment by johlju** [comment]
Closing this as this does not seem to be an error with the resource. If you think it is, then provide more context of the error like the script you are trying to run and the verbose logs when running.
