### ISSUE TITLE
Non-Required, final, trailing zero in 'SqlServerDsc' version numbers causing 're-publishing', version amendments

### ISSUE THREAD

**Issue by SphenicPaul** [dsccommunity/SqlServerDsc#1451]
At present, this `SqlServerDsc`, PowerShell module is consistently using a 4-part version (e.g. `13.2.0.0`).

Unfortunately, when using the Microsoft-recommended approach to copying/duplicating/republishing a PowerShell module ...

[https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-6#publishing-to-a-local-repository](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-6#publishing-to-a-local-repository)

... the version of the `SqlServerDsc` module published to the local/internal repository omits the final zero (e.g. `13.2.0.0` becomes `13.2.0`), presumably on the basis that this adds no/little value/meaning to the version of the module.

Seemingly, there are some aspects of PowerShellGet (and PowerShell, module management and dependency management) that treat `13.2.0.0` and `13.2.0` the same, and other areas that treat them as different values, so ensuring these are identical is important.

Is there any need for the `SqlServerDsc`, PowerShell module to be published to the public, PowerShell Gallery with the final zero? - Can the public, published version please be updated to a 3-part version (if the final part is going to be zero) to remove/reduce this down-stream, version adjustment problem (from future versions going forward) for anybody that may consume/reuse this module in their own, private, PowerShell repositories/galleries?

**Comment by johlju** [comment]
This issue has been discussed here https://github.com/PowerShell/DscResources/issues/508. This repo will be moved to a new continuous delivery pipeline which will use semantic version. I'm currently working on it. When done, next release will use semantic versioning.

**Comment by SphenicPaul** [comment]
OK. Thanks.

Another few (possibly relevant) links...

- [https://github.com/PowerShell/PowerShellGet/issues/416](https://github.com/PowerShell/PowerShellGet/issues/416)

- [https://github.com/PowerShell/PowerShellGallery/issues/55](https://github.com/PowerShell/PowerShellGallery/issues/55)

**Comment by johlju** [comment]
A preview was just released to PowerShell Gallery which uses semantic version. 
https://www.powershellgallery.com/packages/SqlServerDsc/13.3.0-preview0001

Full version will be released later, hoping to get in a few more PR's before releasing a new version.

**Comment by johlju** [comment]
This should be resolved now.
