### ISSUE TITLE
SqlServerRole: Add support for nested roles

### ISSUE THREAD

**Issue by nabrond** [dsccommunity/SqlServerDsc#1452]
#### Details of the scenario you tried and the problem that is occurring
SQL Server supports both [logins and user-defined server roles](https://docs.microsoft.com/sql/t-sql/statements/alter-server-role-transact-sql#arguments) being members of a server role. The SqlServerRole resource should be enhanced to add this support. Currently, the resource checks whether all Members, MembersToInclude, or MembersToExclude are valid Logins on the system. 

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Instead of solely checking for a valid Login, the resource should also validate whether it matches a Role defined in the instance.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SqlServerRole 'Role-DBAdmins'
{
    Ensure = 'Present'
    ServerRoleName = 'DBAdmins'
    ServerName = 'sql.contoso.com'
    PsDscRunAsCredential = $SqlAdministratorCredential
}

SqlServerRole 'Role-sysadmin'
{
    Ensure = 'Present'
    ServerRoleName = 'sysadmin'
    ServerName = 'sql.constoso.com'
    MembersToInclude = 'DBAdmins'
    PsDscRunAsCredential = $SqlAdministratorCredential
}
```

#### SQL Server edition and version the target node is running
SQL 2012+

#### SQL Server PowerShell modules present on the target node
SQLPS
SqlServer
SqlServerDsc

#### The operating system the target node is running
N/A

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by johlju** [comment]
Sounds like a good addition.
