### ISSUE TITLE
SqlScript Failed in 2nd Run: Details inside script already exist in database

### ISSUE THREAD

**Issue by emyatsuna** [dsccommunity/SqlServerDsc#1465]
Hi,

I got a successful run of my sql script during my first run using this resource. However, I am getting error in 2nd run because the details in `mssql.sql` script already exist in the database (which is a valid error). Assuming the mssql.sql script creates details inside the database. Does anyone has some tips on how to filter execution state of `sqlscript` ? So that every time automation tool runs, it won't appear as failed. Please also further discuss what it meant by `variable` parameter in the resource. Thanks.

```
sqlscript{ "ExecuteSQLScript":
   serverinstance = "hostname\MSSQLSERVER",
   setfilepath = "C:\mssql.sql",
   getfilepath = "C:\mssql.sql",
  testfilepath = "C:\mssql.sql",
}
```

**Comment by johlju** [comment]
You should not use the same script for all three parameters. The "Test" SQL script is used to validate if the desired state is true or not, the "Get" SQL script should return the current state, and the "Set" state is to set to the desired state.

See this example that I think covers what you asking.

https://github.com/dsccommunity/SqlServerDsc/blob/master/source/Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1

**Comment by emyatsuna** [comment]
Thanks @johlju

**Comment by johlju** [comment]
Closing this since I'm guessing this issue was answered.
