### ISSUE TITLE
Azure DevOps is removing older build images

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1466]
The Windows Server Core 1803 image is being removed on March 23, 2020. This repository is using the image and must be removed or transition to another image as appropriate.

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/azure-pipelines.yml#L50

https://github.com/dsccommunity/SqlServerDsc/blob/209e6e53122d8c10feee6eca098afcc26153f7b4/azure-pipelines.yml#L78

**Comment by dwilkie1** [comment]
I'm going to try to work this one.

**Comment by johlju** [comment]
@dwilkie1 awesome! Thank you for the PR!
