### ISSUE TITLE
parameter for backup compression default setting

### ISSUE THREAD

**Issue by gstorme** [dsccommunity/SqlServerDsc#1468]
Would it be possible to provide a parameter to configure the backup compression default setting?

As explained on https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/view-or-configure-the-backup-compression-default-server-configuration-option?view=sql-server-ver15

**Comment by johlju** [comment]
It isn't possible to set this value with `SqlServerConfiguration`?

https://github.com/dsccommunity/SqlServerDsc/blob/master/source/Examples/Resources/SqlServerConfiguration/1-ConfigureTwoInstancesOnTheSameServerToEnableClr.ps1

**Comment by gstorme** [comment]
Ah of course... thanks.
