### ISSUE TITLE
Same registry error while using 64bit source

### ISSUE THREAD

**Issue by SecureString** [dsccommunity/SqlServerDsc#1469]
hi 
i am trying to install sqlserver 2016 with a reduced and simple setup:
 SqlSetup 'InstallDefaultInstance'
          {  
	SQLSysAdminAccounts = @('Administrators')			 
          InstanceName           = 'MSSQLSERVER'
          SourcePath          = "$($NodeConfiguration.zipfolder)\SQLServer"
	 PsDscRunAsCredential = $NodeConfiguration.Domain_User_Administrator_Cred
	 Action = "Install"
         Features               = 'SQLENGINE'            			
	 SQLSVCACCOUNT=$NodeConfiguration.Domain_User_Administrator_Cred	
         UpdateEnabled          = 'False'
         ForceReboot            = $false
	DependsOn                           = "[Archive]Microsoft_SQLServer2016_ProvidingInstallationSources"
            
          }
This ends in several Registry errors like:
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL' because it does not exist. have you any hints to find the source of these messages ?
thanks

**Comment by johlju** [comment]
Could you please provide the verbose output when you run the configuration so we can see how far it comes and when it fails?

**Comment by SecureString** [comment]
Hi
this is the verbose out (a part of it)
![output](https://user-images.githubusercontent.com/61046650/74753638-b386eb80-5270-11ea-9701-7b8f6c419306.PNG)
No SQL Services are installed. In the Windows Menu i find many SQLServer related Tools, but None of These are working.
The SQLServer log Reports:
Exception summary:
The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

Exception type: System.ComponentModel.Win32Exception
    Message: 
        1: 2203 2: C:\TempFolder\ZipFolder\SQLServer\x64\setup\sql_as.msi 3: -2147286775
    HResult : 0x80004005
    Error : 110
Thanks for any hint

**Comment by SecureString** [comment]
Hi 
![output](https://user-images.githubusercontent.com/61046650/74754347-c51cc300-5271-11ea-826f-919e7ac1326b.PNG)
the verbose output.
the SQL Server log Reports:
Exception summary:
The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

Exception type: System.ComponentModel.Win32Exception
    Message: 
        1: 2203 2: C:\TempFolder\ZipFolder\SQLServer\x64\setup\sql_as.msi 3: -2147286775
    HResult : 0x80004005
    Error : 110
Thanks for any help

**Comment by SecureString** [comment]
Hi 
![output](https://user-images.githubusercontent.com/61046650/74754547-13ca5d00-5272-11ea-957c-31eab77b9263.PNG)
the SQL Server Reports:
Exception summary:
The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

Exception type: System.ComponentModel.Win32Exception
    Message: 
        1: 2203 2: C:\TempFolder\ZipFolder\SQLServer\x64\setup\sql_as.msi 3: -2147286775
    HResult : 0x80004005
    Error : 110
thanks for any help

**Comment by johlju** [comment]
That error means that when testing if the features was installed that test failed. So something higher up in the verbose log happened. Where in the verbose log output started the error you mentioned above? 

Also you seem to be running an older version on SqlServerDsc as that error message in your screen shot has a better description in the latest released version https://www.powershellgallery.com/packages/SqlServerDsc/13.3.0

**Comment by johlju** [comment]
If the error in the screenshot is the only error you are seeing then you need to check the *Setup Bootstrap/Log* folder for what is happening, e.g. `C:\Program Files\Microsoft SQL Server\120\Setup Bootstrap\Log` (120 is depending on SQL Server version). That is the SQL Setup log and can tell you more what error occurred during setup.

**Comment by SecureString** [comment]
the log return following error:
Exception summary:
The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

Exception type: System.ComponentModel.Win32Exception
    Message: 
        1: 2203 2: C:\TempFolder\ZipFolder\SQLServer\x64\setup\sql_as.msi 3: -2147286775
    HResult : 0x80004005
    Error : 110
    Data: 
      WatsonData = 110@2203
      DisableWatson = true

**Comment by johlju** [comment]
Where do you see that error? Is it part of the verbose output or do you see that in the Setup log? If it is part of the verbose output then please provide the output as it will help narrowing it down. You can obfuscate any sensitive information before pasting here.

It is starting to look like you have a bad media (setup files are corrupt) so that it is setup.exe that fails, it has happened to me and that gives some strange error. But I'm not certain that is the case here yet. 🤔

**Comment by SecureString** [comment]
i found the same error (as a warning) in the verbose output:

WARNING: [SQL-TSA-01]: [[SqlSetup]InstallDefaultInstance] Setup exited with code
'-2147467259'. Please see the 'Summary.txt' log file in the 'Setup Bootstrap\Log' folder.
No idea at all

**Comment by SecureString** [comment]
hi
you are right , - i found one corupt file in X64, hope that was my only problem. Thanks for your support. i will try it with a new binary.

**Comment by johlju** [comment]
Great that you find the corrupt file. I'm sure it works once you get a good media. 🙂
