### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by wb529kq** [dsccommunity/SqlServerDsc#1471]
How can i find a list of the supported features when I try to use 'SQLENGINE,CONN,BC' 
    from the ini file CONN and BC cannot be found.
    I cannot seem to find any list of the options.

**Comment by johlju** [comment]
See the SQL Server setup documentation fir the version of SQL you are trying to install https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver15#Feature
