### ISSUE TITLE
SqlSetup: failing to apply the SQL 2019 CUs 

### ISSUE THREAD

**Issue by rodtobias** [dsccommunity/SqlServerDsc#1472]
The SqlSetup is running the installation for the most part perfectly.  But when it comes to updating the patch we are getting the error message below.  When I run the CU outside of the DSC it runs finds but the Update is installed from a diffeernt temp directory though (not c:\windows\temp).  I don't know if this is a bug in the code as there is nothing being passed through SqlSetup to say use the temp windows directory.  This problem is occuring with SQL 2019.  SQL 2017 and below runs the updates with no issues and it is installing the updates from Windows temp directory.  

I did check and the C:\ drive does have 30 GB free out of 70 GB.  So, I wouldn't think the patch would be 30 GB worth of patching.  But I don't know if anyone has experience this or not.  We do have a workaround for now where we install SQL 2019 first using the SqlServerDSC and then run PowerShell code to install the latest CU afterwards.  But just checking if anyone seen this before?  

Version of SqlServerDSC is **13.3.0**

**_Line in the DSC Log File that kicks off the Install_** (I took out the SysadminAccounts to post here):
```
Using path 'C:\SQL\SQLDSC\SqlSetupFiles\setup.exe'.
[LABServerName]:                            [[SqlSetup]InstallSqlInstance::[SqlServerBaseInstallation]InstallBaseInstallation] Starting setup using arguments: /FEATURES=SQLENGINE,REPLICATION,FULLTEXT,DQ,CONN,BC,SDK /QUIET="True" /SQLTEMPDBLOGDIR="E:\TEMP\VOL01\MSSQL15.MSSQLSERVER\MSSQL\TEMPDB" /BROWSERSVCSTARTUPTYPE="Automatic" /SQLBACKUPDIR="E:\BACKUPS\VOL01\MSSQL15.MSSQLSERVER\MSSQL\Backup" /IACCEPTSQLSERVERLICENSETERMS="True" /SECURITYMODE="SQL" /ACTION="Install" /AGTSVCSTARTUPTYPE="Automatic" /INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server" /SQLTEMPDBFILESIZE="1024" /SQLTEMPDBDIR="E:\TEMP\VOL01\MSSQL15.MSSQLSERVER\MSSQL\TEMPDB" /UPDATESOURCE="C:\SQL\SQLDSC\UpdatePackages" /SQLTEMPDBLOGFILESIZE="1024" /INSTALLSQLDATADIR="E:\SYSTEM" /SQLTEMPDBFILEGROWTH="1024" /SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS" /SAPWD="********" /SQLUSERDBDIR="E:\DATA\VOL01\MSSQL15.MSSQLSERVER\MSSQL\Data" /UPDATEENABLED="True" /SQLUSERDBLOGDIR="E:\LOG\VOL01\MSSQL15.MSSQLSERVER\MSSQL\Log" /INSTANCENAME="MSSQLSERVER" /INSTANCEDIR="C:\Program Files\Microsoft SQL Server" /INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server" /SQLTEMPDBLOGFILEGROWTH="1024" /SQLSVCSTARTUPTYPE="Automatic" /SQLTEMPDBFILECOUNT="2"
```

**_Error in the DSC Log File:_**
```
PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state. 

```
**_Error Message in the Summary Text:_**
```
Error message:
The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

Exception type: Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractionFailureException
    Message: 
        SQL Server Setup was not able to extract requested product update C:\SQL\SQLDSC\UpdatePackages\SQLServer2019-KB4536075-x64.exe to C:\WINDOWS\TEMP\SQL Server 2019\Hotfix. This can often happen when drive does not have enough space or the update package is corrupted. Click Retry to extract again or Cancel to exit out of Setup.
    HResult : 0x851b0001
        FacilityCode : 1307 (51b)
        ErrorCode : 1 (0001)
    Data: 
      PackageLocation = C:\SQL\SQLDSC\UpdatePackages\SQLServer2019-KB4536075-x64.exe
      ExtractLocation = C:\WINDOWS\TEMP\SQL Server 2019\Hotfix
      Result = 336
      WatsonData = Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractionFailureException@1
    Stack: 
        at Microsoft.SqlServer.Configuration.SmartSetupExtension.SfxcabExtractEngine.ExtractUpdate()
        at Microsoft.SqlServer.Configuration.SmartSetupExtension.PackageExtractAction.ExecuteAction(String actionId)
        at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClass2_0.<ExecuteActionWithRetryHelper>b__0()
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
```

**Comment by johlju** [comment]
I just tried this and it works perfectly. 

```tsql
select @@version
```

```plaintext
Microsoft SQL Server 2019 (RTM-CU2) (KB4536075) - 15.0.4013.40 (X64)   Feb  3 2020 16:40:57   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

**Comment by johlju** [comment]
Have you verified that there are neither of these problems as stated in the error message?

"...This can often happen when drive does not have enough space or the update package is corrupted..."

**Comment by rodtobias** [comment]
So, there is about 30 GB of free space out of 60 GB space. So it using the c:\windows\temp root directory should not be a problem. Installing version 2017 and below doesn't have this problem using the same location.

Also, I don't believe the file is corrupt as I used the same file doing the update manually except it doesn't use the windows directory, and I  didn't tell it to use a specific location for running the update.

Regards,
Rod

⁣Get TypeApp for Android ​

**Comment by rodtobias** [comment]
Can you show where the update  extraction occurs from?  Basically that information is in the detail log file.

Regards,
Rod

⁣Get TypeApp for Android ​

**Comment by rodtobias** [comment]
Please show your extract location as I want to see if the DSC is also using the same location for you as it did for me like I showed in my initial response.  Thanks in advance.

Here is the extract location I posted intially:
```
ExtractLocation = C:\WINDOWS\TEMP\SQL Server 2019\Hotfix

**Comment by johlju** [comment]
Since I use `PsDscRunAsCredential` with the resource SqlSetup it is that users temp folder.

```
(01) 2020-03-06 20:44:43 Slp: Setting: CUSOURCE
(01) 2020-03-06 20:44:43 Slp: Value specified: C:\Users\sqlinstall\AppData\Local\Temp\SQL Server 2019\Hotfix
(01) 2020-03-06 20:44:43 Slp: New setting source: CommandLine; previous setting source: NotSpecified
```

I'm guessing you run the resource as SYSTEM since you get `C:\WINDOWS\TEMP`?

**Comment by rodtobias** [comment]
That is correct. Right now in our process we are not using a  designated  user account.  This is part of a bigger process of building a  SQL VM.  Can you try it that way as well running the resources system to see if you get the same results?


Thanks for your help.
⁣Get TypeApp for Android ​

**Comment by johlju** [comment]
From issue #1475 the following information was provided by @taschaal:

> Manually running C:\Windows\Temp\Developer_Edition\Updates\sqlserver2019-kb4527376-x64_01dcaca398f0c3380264078463fc1a6cc859ec7c.exe /x:"C:\Windows\TEMP\SQL Server 2019\Hotfix" /q gives error "the application cannot be compressed to a system directory". I don't receive this error with 2017 CU packages. Perhaps the destination should be changed to a different directory

This is starting to sound like a SQL Server setup issue. To work around it with DSC you should install with another account than the account SYSTEM using the property `PsDscRunAsCredential`. 

For the root issue I suggest opening a case with Microsoft support asking if it is no longer supported to extract the CU to a system directory.

**Comment by taschaal** [comment]
Thanks for the suggestion.  I will follow up with MS

**Comment by johlju** [comment]
At this time I label this as external and closing this issue. If there are any more information then please comment to help others. Thanks for your contribution @taschaal.

**Comment by ShawnHardwick** [comment]
I don't have any additional information to add to this issue other than that I experienced the exact issue as described. We use the SYSTEM account to run the SQLSetup resource. My workaround is to use a designated service account to run this resource. I also plan on submitting a ticket to Microsoft through the support channel as this is a SQL implementation change in 2019.

**Comment by ShawnHardwick** [comment]
Received word from Microsoft that the CU5 patch for SQL Server 2019 will have a fix for this.

**Comment by johlju** [comment]
That is great news, thanks @ShawnHardwick, thank you for running this with MS Support!
