### ISSUE TITLE
SqlSetup: Support /ENU setup argument

### ISSUE THREAD

**Issue by wb529kq** [dsccommunity/SqlServerDsc#1473]
Is there an option to force english language in the installation using DSC ?

**Comment by johlju** [comment]
Can you please be a bit more descriptive, for example what do you want to have in english? You mean installing Sql Server in english on a non-english OS?

**Comment by wb529kq** [comment]
I need to enforce that its installs in English on a non-English OS like you say in the ini file there is an option ENU=True.

**Comment by johlju** [comment]
Ah, you are looking for the `/ENU` parameter mentioned in this article https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver15#Install

There are no parameter to set that in the SqlSetup resource, but I'm happy to review a PR that adds the functionality.

**Comment by wb529kq** [comment]
yes that is what i was looking for :) I will try to make a PR.
