### ISSUE TITLE
SqlServerLogin: Set default database

### ISSUE THREAD

**Issue by bozho** [dsccommunity/SqlServerDsc#1474]
#### Details of the scenario you tried and the problem that is occurring
`SqlServerLogin` resource currently does not support setting the default database for logins.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Add an optional `DefaultDatabase` parameter.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### SQL Server edition and version the target node is running
N/A

#### SQL Server PowerShell modules present on the target node
N/A

#### The operating system the target node is running
N/A

#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.3471                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.3471                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

#### Version of the DSC module that was used
```
Name         Version  Path                                                                              
----         -------  ----                                                                              
SqlServerDsc 13.0.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.0.0.0\SqlServerDsc.psd1
```

I'm happy to provide a patch for this, just wanted to check if there are any caveats/problems I should be aware of...

**Comment by johlju** [comment]
Sounds like a new property in the existing resource, so can't see any problems or caveats, at least not now. 🙂
