### ISSUE TITLE
SqlServerDsc: Inconsistent Naming *Name / DatabaseName / Database / Name

### ISSUE THREAD

**Issue by Rob-S** [dsccommunity/SqlServerDsc#1484]
#### Details of the scenario you tried and the problem that is occurring

After creating SqlServerLogin then SqlDatabaseUser, I copied the User to a SqlDatabaseRole expecting the resource properties for various Database-specific objects to be similar. However, the DatabaseName property was "Database" instead, where most other properties end with "Name".

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Properties should be named consistently. Since most properties include "Name" at the end, so should the DatabaseName property. In fact, that is the way it already is in SqlDatabaseUser, for example.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
N/A

#### SQL Server edition and version the target node is running

N/A

#### SQL Server PowerShell modules present on the target node

N/A

#### The operating system the target node is running

N/A

#### Version and build of PowerShell the target node is running

5.1.14409.1005

#### Version of the DSC module that was used

13.4.0

**Comment by johlju** [comment]
Yes, there are some properties that should be renamed, but it is a breaking change so we should do it when doing other breaking changes if possible.

**Comment by johlju** [comment]
If anyone is interested and sending in a PR for this I would appreciate it. There is a pending breaking change release coming up.

**Comment by Rob-S** [comment]
[#1507 ](https://github.com/dsccommunity/SqlServerDsc/pull/1507)
