### ISSUE TITLE
SqlDatabaseUserRole: New resource proposal with code

### ISSUE THREAD

**Issue by Rob-S** [dsccommunity/SqlServerDsc#1488]
### Description

It is probably at least as common to want to manage what a specific user or group can do in the database, via membership in multiple roles that already exist, as it is to manage the members of a specific role, which the existing SqlDatabaseRole resource does. For example, it is quite common to want to assign the 'db_datareader' and possibly also the 'db_datawriter' roles to various users and groups. A Database User Role resource could "enforce" a specific set of roles for various users and groups without accidentally modifying other users or group members assigned to the same roles. This allows the option to focus on managing the capabilities of the database User object as users and groups are added to the environment.

### Proposed properties

    [Key, Description("The host name of the SQL Server to be configured.")] String ServerName;
    [Key, Description("The name of the SQL instance to be configured. Can be NULL, an empty string or 'MSSQLSERVER' for an unnamed instance.")] String InstanceName;
    [Key, Description("The name of the database in which the user roles should be configured.")] String DatabaseName;
    [Key, Description("Specifies the name of the database user to be configured.")] String UserName;
    [Write, Description("The names of the database roles the user should have. This parameter will replace all the current database role members with the specified members. Can only be used when parameter Ensure is set to 'Present'.")] String[] RoleNamesToEnforce;
    [Write, Description("The names of the database roles that should be included. This parameter will only add members to a database role. Can only be used when parameter Ensure is set to 'Present'. Can not be used at the same time as parameter RoleNamesToEnforce.")] String[] RoleNamesToInclude;
    [Write, Description("The names of the database roles that should be excluded. This parameter will only remove members from a database role. Can only be used when parameter Ensure is set to 'Present'. Can not be used at the same time as parameter RoleNamesToEnforce.")] String[] RoleNameToExclude;
    [Read, Description("The roles that the user is a member of.")] String[] RoleName;
    [Read, Description("Indicates whether the server is the primary replica for the database. Null if not an HA database.")] Boolean IsPrimaryReplica;
    [Write, Description("Indicates whether the configuration is to be tested and set on all replicas. The default is to update the database only on the primary replica.")] Boolean OnAllReplicas;

### Special considerations or limitations

We make use of Always On Availability Groups on most of our SQL Server database servers. SqlServerDsc provides a way to keep the Logins in sync (at least the Windows authenticated ones; for SQL Server authenticated Logins, the SID values must be the same on all servers hosting the replicas). The SqlDatabase* resources throw errors when attempting to make changes to the secondary replicas. The code in the SqlDatabaseUserRole branch addresses this limitation.

**Comment by Rob-S** [comment]
See pull request #1489.

**Comment by johlju** [comment]
I'm not sure about this resource. If we would add this resource then together with the SqlDatabaseRole resource that could make a ping-pong behavior where one resource could add a user to a database while the other can remove it again. 

If the issue is that SqlDatabaseRole throws an error then I think we need to adress that in that resource.  🤔 

What is the root cause with SqlDatabaseRole and a database that is in an Availability Group?

**Comment by Rob-S** [comment]
> One resource could add a user to a database while the other can remove it again.
This resource does not add users to a database. That's the SqlDatabaseUser resource which does that.

**Comment by johlju** [comment]
Sorry, it should have said that one resource could add a user to a database _role_ while the other resource can remove the user from the role. 

SqlDatabaseRole adds a user to a role, in the same configuration this new resource removes the same user from the role. Running the configuration again will add and then remove again giving a ping-pong behavior.

**Comment by Rob-S** [comment]
With this resource, Logins, Users and User Roles for a new user or group would be grouped together in the configuration files (as in the code from one of the examples below). The Role resource, which will ensure that the role exists before adding members, isn't needed at all for built-in roles, which you would normally expect to exist unless deleted. A "RoleMember" resource would be sufficient in that case.
```
    # Make sure the login exists
        SqlServerLogin 'Login_CONTOSO_Clare' {
            ServerName      = 'sqltest.company.local'
            InstanceName    = 'DSC'
            Name            = 'CONTOSO\Clare'
            Ensure          = 'Present'
            LoginType       = 'WindowsGroup'
            Disabled        = $false
        }
    # Make sure the user exists
        SqlDatabaseUser 'User_AdventureWorks_Clare_MacIntyre-Ross' {
            ServerName      = 'sqltest.company.local'
            InstanceName    = 'DSC'
            DatabaseName    = 'AdventureWorks'
            Name            = 'Clare MacIntyre-Ross'
            LoginName       = 'CONTOSO\Clare'
            UserType        = 'Login'
            Ensure          = 'Present'
#            OnAllReplicas   = $false
            Force           = $false
        }
    # Make sure the user has only the appropriate roles
        SqlDatabaseUserRole 'UserRoles_AdventureWorks_Clare_MacIntyre-Ross_Enforce'
        {
            ServerName              = 'sqltest.company.local'
            InstanceName            = 'DSC'
            DatabaseName            = 'AdventureWorks'
            UserName                = 'Clare MacIntyre-Ross'
            RoleNamesToEnforce      = 'db_datareader', 'db_datawriter'
            OnAllReplicas           = $false
            PsDscRunAsCredential    = $SqlAdministratorCredential
        }
```

**Comment by johlju** [comment]
Setting the the above role memberships can already be accomplished by the following configuration. 

```powershell
SqlDatabaseRole 'Members_db_datareader'
{
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    Name                 = 'db_datareader'
    MembersToInclude     = @('Clare MacIntyre-Ross')
    Ensure               = 'Present'
}

SqlDatabaseRole 'Members_db_datawriter'
{
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    Name                 = 'db_datawriter'
    MembersToInclude     = @('Clare MacIntyre-Ross')
    Ensure               = 'Present'
}
```

The parameter `MembersToInclude` can be replaced with `Members` to enforce that only that membership should be present, but the below will add members and don't change any existing role memberships.
We should also have one resource that manage database roles to prevent ping-pong behavior.

**Comment by Rob-S** [comment]
To ensure the user could execute only DML and not DDL, you would also have to include (with just the most common roles):
```
SqlDatabaseRole 'Members_db_owner'
{
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    Name                 = 'db_owner', 'db_denydatareader', 'db_denydatawriter'
    MembersToExclude     = @('Clare MacIntyre-Ross')
    Ensure               = 'Present'
}
```
And for the read-only group in the example provided, you would need to exclude the group from both the owner and writer groups - in theory, you should exclude _all_ undesired roles, especially the deny, admin, etc. roles:
```
SqlDatabaseRole 'Members_read-only-group'
{
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    Name                 = 'db_datawriter', 'db_owner', 'db_securityadmin', 'db_accessadmin', 'db_backupoperator', 'db_ddladmin', 'db_denydatareader'
    MembersToExclude     = @('CONTOSO Read-Only Users')
    Ensure               = 'Present'
}
```
However, I suspect it won't allow doing that, since if it did it you could wind up with the ping-pong effect you mention.

**Comment by johlju** [comment]
If that is the desired state then add an instance of SqlDatabaseRole for each role (it is not allowed to have an array as a key).

```
SqlDatabaseRole 'db_datawriter'
{
    Name                 = 'db_datawriter'
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    MembersToExclude     = @('CONTOSO Read-Only Users')
    Ensure               = 'Present'
}

SqlDatabaseRole 'db_owner'
{
    Name                 = 'db_owner'
    ServerName           = 'sqltest.company.local'
    InstanceName         = 'DSC'
    Database             = 'AdventureWorks'
    MembersToExclude     = @('CONTOSO Read-Only Users')
    Ensure               = 'Present'
}

... and any other desired role
```

**Comment by johlju** [comment]
What does this proposed resource SqlDatabaseUserRole solve that SqlDatabaseRole not already support? 🤔
