### ISSUE TITLE
SqlDatabase: Cannot convert value "Version140"   to type "Microsoft.SqlServer.Management.Smo.CompatibilityLevel"

### ISSUE THREAD

**Issue by Susanthab** [dsccommunity/SqlServerDsc#1516]
#### Details of the scenario you tried and the problem that is occurring
Creating a database in SQL Server 2017.

#### Verbose logs showing the problem
PowerShell DSC resource MSFT_SqlDatabase  failed to execute Set-TargetResource functionality with error message: 
System.InvalidOperationException: Failed to create the database 'dbname'. ---> 
System.Management.Automation.SetValueInvocationException: Exception setting "CompatibilityLevel": "Cannot convert value "Version140"  
to type "Microsoft.SqlServer.Management.Smo.CompatibilityLevel". Error: "Unable to match the identifier name Version140 to a valid    
enumerator name. Specify one of the following enumerator names and try again:
Version60, Version65, Version70, Version80, Version90, Version100, Version110, Version120, Version130""
#### Suggested solution to the issue
I'm using the latest version of SqlServerDsc and I've used it couple times to configure 2017 servers and it worked fine no issues. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        SqlDatabase CreateDbaDatabase {
            ServerName          = $Node.NodeName
            InstanceName        = 'MSSQLSERVER'
            Name                = 'dbname'
        }
```

#### SQL Server edition and version the target node is running

Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)   Jan 23 2020 21:00:04   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node

SqlServer    20.0    C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psd1                                    
SQLASCMDLETS 2.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1
SQLPS        1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1              
SQLPS        14.0    C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3564.amd64fre.rs1_release.200303-1942
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

PSVersion                      5.1.14393.3471                                                                                        
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.14393.3471                                                                                       
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used

SqlServerDsc 13.5.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.5.0\SqlServerDsc.psd1

**Comment by johlju** [comment]
Does this node have more than one edition of SQL Server? Or do you configure something else that imports SQLPS module instead of the SqlServer module. My thinking is that something loads the wrong assembly `Microsoft.SqlServer.Management.Smo` which can cause strange errors.

**Comment by Susanthab** [comment]
@johlju This server has two instances, SQL Server engine, and SQL Server RS. However, it works fine, when changing the compatibility level to Version130 for the database being created.

**Comment by johlju** [comment]
So there is there one instance of SQL Server 2017 and another instance of SQL Server 2016?

Because I see SQLPS for SQL Server 2016 being installed 
``` 
SQLPS 1.0 C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```
This indicated that there are potentially assemblies for SQL Server 2016 in the GAC. If one of those is loaded into the PowerShell session prior to running the SqlDatabase resource then that can override the one that the module `SqlServer` expects, thus giving these strange errors.
It trying to use `Version140` against an assmebly that does not support that value.

**Comment by Susanthab** [comment]
@johlju, as I stated earlier the SQL Server Database Engine, is 2017, and SQL Server Reporting Service is also 2017. Does it really matter the server has multiple SQL Server services such as RS, AS, etc. The reason is, you can create the database only in SQL Server engine version, right? If it has multiple server instances, yes then I get your point but in this case, it is not.

**Comment by johlju** [comment]
I didn't mean multiple services, I meant multiple _SQL Server versions_. :) For example if an instance of both SQL Server 2017 and SQL Server 2016 is or have been installed on the node. Then those have added assemblies to GAC with different version. Although this might be a problem with an older SqlServer module. 🤔 

What version of SqlServer are you using? 

I tested with SqlServer version `21.1.18080` which works.
```
PS C:\Windows\system32> Get-Module -Name '*sql*' -ListAvailable | ? Name -ne 'SqlServerDsc' | ft Name,Version,Path

Name      Version    Path
----      -------    ----
SqlServer 21.1.18080 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18080\SqlServer.psd1
SQLPS     14.0       C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

Running this configuration successfully creates a database using `CompatibilityLevel` set to `Version140`.

```powershell
Invoke-DscResource -ModuleName SqlServerDsc -Name SqlDatabase -Method Set -Property @{
    Ensure               = 'Present'
    ServerName           = 'testclu02-AG1'
    InstanceName         = 'sql2017'
    Name                 = 'AdventureWorks2'
    CompatibilityLevel   = 'Version140'

    PSdscRunAsCredential = $SqlInstallCredential
} -Verbose 
```

```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQLTEST with user sid S-1-5-21-2246212248-426023572-517575333-1441.
VERBOSE: [SQLTEST]: LCM:  [ Start  Set      ]  [[SqlDatabase]DirectResourceAccess]
VERBOSE: [SQLTEST]:                            [[SqlDatabase]DirectResourceAccess] Preferred module SqlServer found. (SQLCOMMON0023)
VERBOSE: [SQLTEST]:                            [[SqlDatabase]DirectResourceAccess] Importing PowerShell module 'SqlServer' with version '21.1.18080' from path 'C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18080\SqlSe
rver.psm1'. (SQLCOMMON0025)
VERBOSE: [SQLTEST]:                            [[SqlDatabase]DirectResourceAccess] Connecting as current user 'SHAMN\johlju.admin' using integrated security. (SQLCOMMON0054)
VERBOSE: [SQLTEST]:                            [[SqlDatabase]DirectResourceAccess] Connected to SQL instance 'testclu02-AG1\sql2017'. (SQLCOMMON0018)
VERBOSE: [SQLTEST]:                            [[SqlDatabase]DirectResourceAccess] Creating the database 'AdventureWorks2'.
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]  [[SqlDatabase]DirectResourceAccess]  in 4.1420 seconds.
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]    in  4.5470 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.

RebootRequired 
-------------- 
False          
VERBOSE: Time taken for configuration job to complete is 4.739 seconds
```

**Comment by Susanthab** [comment]
@johlju This server has only one SQL Server instance which is 2017. However, earlier we had 2016 and we did an in-place upgrade to SQL Server 2017. That might be something to consider.

**Comment by johlju** [comment]
Please verify that you have version of the PowerShell module `SqlServer` that supports the SQL Server 2017. I was testing with https://www.powershellgallery.com/packages/SqlServer/21.1.18080.

If you still have that issue when using that version of the SqlServer module then I you might run some other resource prior to the `SqlDatabase` resource is run which loads an assembly from the GAC that is probably left from the prior SQL Server version (prior to the in-place upgrade).

**Comment by Susanthab** [comment]
@johlju Below is the version of SqlServerDsc that I've installed in the target server.

SqlServer    20.0    C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psd1 

Does this one support SQL Server 2017?

**Comment by johlju** [comment]
Since it says '20' and the one I used starts with '21.x.x.x' I'm guessing you running with an older module. I don't know what versions supports what version of SQL Server. But I would start by downloading version `21.1.18080` since that worked for me so you can verify if the module is too old module.

**Comment by Susanthab** [comment]
@johlju I get your point. Can you clarify this for me? I checked my PS code which does the sql server configuration. In that, I installed only SqlServerDsc and I do not install SqlServer module explicitly. So I'm confused about the difference between SqlServer and SqlServerDsc. My understanding was, CreateDbaDatabase is part of SqlServerDsc. For SqlSreverDsc, I install 13.2.0.0 version. Since I did not install SqlServer module explicitly, I believe it comes with PS installation. Correct me if I'm wrong. 
Thanks.

**Comment by johlju** [comment]
The module **SqlServer** is from the Microsoft SQL Server Product Team and is the official module with cmdlets for SQL Server, it is the new module that can replace SQLPS that is shipped with SQL Server. 

**SqlServerDsc** contain open source DSC resources and are released through the DSC Community. SqlServerDsc is dependent on that either SQLPS or SqlServer module is present. If both are installed then SqlServer takes precedence.

The DSC resource `SqlDatabase` are dependent on assemblies that are loaded by the SQLPS or SqlServer module when either is imported.

SqlServer module must be downloaded separately. In your case it must have been installed by someone, maybe it was downloaded for the previous installation (SQL 2016)?

**Comment by Susanthab** [comment]
Okay, that clears things up. Thanks for the clarification. I will install the SqlServer 21 version and see it works.

**Comment by johlju** [comment]
No worries! 🙂 Confident that it will work with a new version of SqlServer.

**Comment by Susanthab** [comment]
@johlju The same error hit me again on SQL Server 2019. Initially this was SQL Server 206 and I did an inplace upgrade to SQL Server 2019. 
Exception setting "CompatibilityLevel": "Cannot convert value "Version150"

This is what I'm having in the target server. (Get-Module -Name 'sql*' -ListAvailable)

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   20.0       SqlServer                           {Add-SqlColumnEncryptionKeyValue, Complete-SqlColumnMasterKeyRotat...
Manifest   13.5.0     SqlServerDsc
Manifest   13.2.0.0   SqlServerDsc


    Directory: C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.0        SQLASCMDLETS                        {Add-RoleMember, Backup-ASDatabase, Invoke-ASCmd, Invoke-ProcessCu...
Manifest   1.0        SQLPS                               {Add-SqlColumnEncryptionKeyValue, Complete-SqlColumnMasterKeyRotat...


    Directory: C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   15.0       SQLPS                               {Backup-SqlDatabase, Save-SqlMigrationReport, Invoke-PolicyEvaluat...

Is this because I've SQLPS module? If so can I uninstall it?

**Comment by Susanthab** [comment]
In addition to the above error, there is an error when setting up server accounts. You can test this by installing prior SQL Server version and then do an inplace upgrade. Then try to set service account.

InvalidOperation: PowerShell DSC resource MSFT_SqlServiceAccount  failed to execute Test-TargetResource functionality with error message: System.Exception: The DatabaseEngine service on **SQLName**\MSSQLSERVER could not be found.

SQLName is the default instance name.

**Comment by johlju** [comment]
> Is this because I've SQLPS module? If so can I uninstall it?

Most likely another resource imports SQLPS it into the session or something uses an assembly from the cache. But can also be that the module SqlServer must be updated to a version that supports SQL Server 2019.

To rule out SQLPS you can remove it by either 
1. (preferably)  Remove the module paths from the machine environment variable `PSModulePath`.
1. Rename the`Modules` folder in the `C:\Program Files (x86)\Microsoft SQL Server\xxx\Tools\PowerShell\Modules`. Where xxx is the versions you have installed, 130 and 150. This might break other things outside of SqlServerDsc.
1. Remove the `Modules` folder entirely mentioned in previous option. This might break other things outside of SqlServerDsc.

**Comment by johlju** [comment]
Please submit another issue for the other error you are seeing and provide the information that is requested in the issue template.
