### ISSUE TITLE
SqlServerDsc: Renaming resources that contain '*Server*'

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1540]
Some of the resources that contain the word _Server_ in its name might wrongly indicate that the resource enforces properties for the entire server and affect multiple instances. The reason the word "server" is used is probably because, for example, the GUI for SQL Server (SSMS) is using that terminology when configuring an individual instance. Example is looking at the configuration properties for an instance like memory, they are called "server properties". But that is not a reason to keep the names unless we think the names are good as-is and is following the [naming convention](https://github.com/dsccommunity/SqlServerDsc/blob/master/CONTRIBUTING.md#naming-convention).

Most of the resources that contain the word _Server_ in the name only affects the specified instance. Because of that a more proper name would be _Instance_ instead of _Server_. An example is `SqlServerConfiguration` which would have a more proper name with `SqlInstanceConfiguration`. But, looking at the [naming convention](https://github.com/dsccommunity/SqlServerDsc/blob/master/CONTRIBUTING.md#naming-convention) that the community has put together the resource would be simply named `SqlConfiguration` since the component is the SQL Server Database Engine. 

This is a list of resource that could potentially be renamed:

*Updated to reflect the conversation below:*

- **initial proposal**:  Was the initial issue proposal
- **2nd proposal**: The proposal that is being updated as discussion evolves below.

Current name | initial proposal | 2nd proposal
--- | --- | ---
SqlServerConfiguration | SqlConfiguration | SqlInstanceConfiguration
SqlServerDatabaseMail | SqlDatabaseMail | SqlInstanceDatabaseMail
SqlServerEndpoint | SqlEndpoint  | SqlEndpoint
SqlServerEndpointPermission | SqlEndpointPermission | SqlEndpointPermission
SqlServerLogin | SqlLogin | SqlLogin
SqlServerMaxDop | SqlMaxDop | SqlInstanceMaxDop
SqlServerMemory | SqlMemory | SqlInstanceMemory
SqlServerPermission | SqlPermission | SqlInstancePermission
SqlServerProtocol | SqlProtocol | SqlInstanceProtocol
SqlServerProtocolTcpIp | SqlProtocolTcpIp | SqlInstanceProtocolTcpIp
SqlServerReplication | SqlReplication | SqlReplication
SqlServerRole | SqlRole | SqlRole
SqlServerSecureConnection | SqlSecureConnection | SqlInstanceSecureConnection
SqlAgentAlert | - | SqlInstanceAgentAlert
SqlAgentFailsafe | - | SqlInstanceAgentFailsafe
SqlAgentOperator | - | SqlInstanceAgentOperator

**Comment by jpomfret** [comment]
Hi @johlju,

I started writing this feeling pretty against the change, it's big breaking change as without being able to use an alias there is no gently implementation here. The more I've thought about it though the naming makes sense.

I would probably lean towards SqlInstance instead of just Sql. These are all SqlInstance level, thinking about dbatools they also standardised to using SqlInstance across the board for this reason.

My main worry is it will be a big change for people and they will get stuck at the module version before this change and not update if there is no easy way (alias) to work around it.

**Comment by johlju** [comment]
Thank you for you input, appreciate it! 😃 

Yes I agree it is a big breaking change. Unfortunately we have waited so long to handle this technical debt so it has grown. I thought we should take care of it now so we can move forward from there (and not add to the technical debt). 🙂

> My main worry is it will be a big change for people and they will get stuck at the module version before this change and not update if there is no easy way (alias) to work around it.

My thought was that as well, that it is a lot of existing configurations to change for people, there are also already a lot of breaking changes pending release (and more to come). But I'm also afraid that not doing the above soon it will be even more configurations out there tomorrow. 😕 

> I would probably lean towards SqlInstance instead of just Sql.

Using the work _Instance_ in the resource names would more clearly indicate that the resources are per instance, although when submitting this issue I thought it would be implicitly so since the "object", for example a database, can only be created per instance. But the same can of course be said even if it keeps the name as today. 🙂 
But using _Instance_ in the names then we add more technical debt since for example the resource `SqlDatabase` need to be renamed `SqlInstanceDatabase`. Going with _Instance_ would practically make a breaking change in (almost) all resource. 😕 But if so, then we have solved that technical debt as well. 

This is not really an issue, just thought I should mention it. We should try to avoid long resource names since using the resource names in for example example files and so on has a hard limit to work in Azure. Though, using the _Instance_ vs _Server_ is just two more letters. _It was worse in earlier days when we had a resources for example  `xSqlServerAvailabilityGroupDatabase` which was changed to `SqlAGDatabase` and the naming convention mentioned above was created_

**Comment by jpomfret** [comment]
> But using Instance in the names then we add more technical debt since for example the resource SqlDatabase need to be renamed SqlInstanceDatabase. Going with Instance would practically make a breaking change in (almost) all resource. 😕 But if so, then we have solved that technical debt as well.

Would we have to add instance to this? Wouldn't the level be database so `SqlDatabase`, `SqlDatabaseOwner` would still be appropriate?

I would 100% agree we don't want `SqlInstanceDatabaseOwner`, etc. That is getting way too long.

**Comment by johlju** [comment]
> Would we have to add instance to this? Wouldn't the level be database so SqlDatabase, SqlDatabaseOwner would still be appropriate?

I see your point - that resources that configures instance have _Instance_ in its name, but then what would indicate what configures an instance. Would it be something that affects multiple databases,  multiple logins, or something else? 🤔 

So if we say that SqlDatabase is keeping its name, would you say this is true.

- the resource `SqlServerConfiguration` would be named `SqlInstanceConfiguration` since it manages properties that affects (or can affect) multiple databases (or the instance as a whole)
- the resource `SqlServerLogin` would be named `SqlLogin` since it manages logins in the instance (like SqlDatabase manages databases in the instance)

**Comment by jpomfret** [comment]
> but then what would indicate what configures an instance.

I guess I'm thinking instance specific things, so I would say 
- SqlInstanceConfiguration - since it's making changes to instance level configurations
- SqlLogin - since it's creating a login on an instance... not specifically affecting the instance?
- SqlInstanceMaxDop - instance level configuration change
- SqlInstancePermission - Instance level permissions

**Comment by johlju** [comment]
I updated the list above (in the issue description). Can you look and see if that follows you thoughts? 

Also, these other resources was the only that I could find that could potentially need a name change. What are your thought for these?

Current name | New name
--- | ---
SqlAgentAlert | SqlInstanceAgentAlert 
SqlAgentFailsafe | SqlInstanceAgentFailsafe
SqlAgentOperator | SqlInstanceAgentOperator

**Comment by jpomfret** [comment]
Looks good I think, there is a typo for SecureConnection and I think the only one I might debates is replication:

Current name | New name
-- | --
SqlServerReplication | ~~SqlReplication~~ SqlReplication
SqlServerSecureConnection | ~~SqlSecureConnection~~ SqlInstanceSecureConnection

I also think we could use more feedback from the community on this, would it be brought up for discussion in the next community call?

**Comment by johlju** [comment]
I though we let it rest for a couple of weeks to see if we get more feedback. We can bring it up, I make sure it gets on the agenda so we can discuss it.

**Comment by johlju** [comment]
Yes, I thought about the Replication one too.. Is that a object or configuration like DatabaseMail. But can go with SqlReplication for that one too. This is never gonna be 100% perfect. 😄

**Comment by nabrond** [comment]
Reading through this and reviewing the naming convention again, I can see some value in making some adjustments. That being said, I am not a fan of adding "Instance" into the mix. Maybe it is because I live in a SQL Server world, but I do not see the confusion in scope. 

The more I think about it, the more in favor I am of dropping "Server" from the list of possible resource scopes. I think this cleans up the resource names and removes the confusion @johlju initially discussed. It would also help to remove some of the inconsistencies I see in the proposed names; for example:
Current name | Proposed name | New name
-- | -- | --
SqlServerDatabaseMail | SqlInstanceDatabaseMail | SqlDatabaseMail
SqlServerEndpoint | SqlEndpoint | SqlEndpoint

Both of these are instance-level objects, yet the proposed scheme

**Comment by nabrond** [comment]
Reading through this and reviewing the naming convention again, I can see some value in making some adjustments. That being said, I am not a fan of adding "Instance" into the mix. Maybe it is because I live in a SQL Server world, but I do not see the confusion in scope. 

The more I think about it, the more in favor I am of dropping "Server" from the list of possible resource scopes. I think this cleans up the resource names and removes the confusion @johlju initially discussed. It would also help to remove some of the inconsistencies I see in the proposed names; for example:
Current name | Proposed name | New name
-- | -- | --
SqlServerDatabaseMail | SqlInstanceDatabaseMail | SqlDatabaseMail
SqlServerEndpoint | SqlEndpoint | SqlEndpoint

These are both instance-level objects, yet both do not have "Instance" defined as their scope? Hopefully more people review this thread and weigh-in so we can set the best direction.

**Comment by jpomfret** [comment]
I agree @nabrond - I think SqlDatabaseMail works here... and agree - bring on the people for discussion.

**Comment by codykonior** [comment]
The naming convention Microsoft uses is ServerInstance. That’s what is used by SQLPS and SqlServer modules as the name of the server/instance to be operated on.

**Comment by ykuijs** [comment]
Agree that the word Server implicates something different than it is actually doing. I like the comment of @jpomfret to include the Instance name where it actually affects an instance thing. Like SQLDatabase, SQLLogin affects an object **inside** an instance, not the instance itself.

Not being a SQL expert myself: On which level is SQL Replication operating?

**Comment by jpomfret** [comment]
Reading the help for replication it seems that the resource is effecting the instance level replication stuff. So I guess SqlInstanceReplication would be appropriate. 

https://github.com/dsccommunity/SqlServerDsc#sqlserverreplication
`This resource manage SQL Replication distribution and publishing.`

**Comment by jpomfret** [comment]
Although if we then wrote resources to set replication up in certain databases for certain objects it would be database level so for example would we create `SqlReplicationPublication` to create a publication and `SqlReplicationArticle` to add an article to a publication... in which case would it make sense the main resource be named `SqlReplication`... 

(sorry went down a rabbit hole 😄)

**Comment by johlju** [comment]
I'm not very familiar with the replication stuff either, but I proposed in other issues that the SqlServerReplication would be split up into two resources because the current implementation didn't feel it could cover all possible scenarios with replication. But since I'm not very familiar with the replication topic, never used it practically until I wrote an integration tests for for this module the issues I created should be taken with a grain of salt. 

Anyway I proposed to split it up into SqlServerReplicationDistributor and SqlServerReplicationPublisher, which for this conversation (and continue on @jpomfret last post)  would be `SqlReplicationDistributor` and `SqlReplicationPublisher`. Then have other resources that publishes an database and/or availability group databases (which is an entire other scenario) - hopefully that can be rolled into the existing SqlDatabase and SqlAGDatabase.

**Comment by johlju** [comment]
> The more I think about it, the more in favor I am of dropping "Server" from the list of possible resource scopes. I think this cleans up the resource names and removes the confusion @johlju initially discussed. It would also help to remove some of the inconsistencies I see in the proposed names

@nabrond if I understand you correctly you are in favor of the names that has been strikethrough? Do you see any resource name that could have _Instance_ in its name?

**Comment by codykonior** [comment]
Re the replication discussion, technology wise some of it would be considered instance level, and other parts are database level.

**Comment by nabrond** [comment]
@johlju, correct, I am not in favor of adding "Instance" to the resource names. 

The initial issue cited was that including "Server" in the name of the resource could be confusing to a new user of the module; whether the setting is at the Server/OS level or Instance level.

Reviewing the proposed resource names, the logic appeared to be inconsistently applied (resources cited previously). Stepping back and looking at the overall listing of resources, I saw very few that would apply the underlying operating system (server). This lead me to personally favor the approach of dropping "Server" all together and not adding a new scope in its place; assuming that all resources, by default, impact the instance. This would make the resource names look like this (with a couple additions):

Current name | "Instance" name | nabrond name
-- | -- | --
SqlServerConfiguration | SqlInstanceConfiguration | SqlConfiguration
SqlServerDatabaseMail | SqlInstanceDatabaseMail | SqlDatabaseMail
SqlServerEndpoint | SqlEndpoint | SqlEndpoint
SqlServerEndpointPermission | SqlEndpointPermission | SqlEndpointPermission
SqlServerLogin | SqlLogin
SqlServerMaxDop | SqlInstanceMaxDop | SqlMaxDop
SqlServerMemory | SqlInstanceMemory | SqlMemory
SqlServerPermission | SqlInstancePermission | SqlPermission
SqlServerProtocol | SqlInstanceProtocol | SqlProtocol
SqlServerProtocolTcpIp | SqlInstanceProtocolTcpIp | SqlProtocolTcpIp
SqlServerReplication | SqlReplication | SqlReplication
SqlServerRole | SqlRole | SqlRole
SqlServerSecureConnection | SqlInstanceSecureConnection | SqlSecureConnection
SqlAgentAlert | SqlInstanceAgentAlert | SqlAgentAlert
SqlAgentFailsafe | SqlInstanceAgentFailsafe | SqlAgentFailsafe
SqlAgentOperator | SqlInstanceAgentOperator | SqlAgentOperator
SqlScript | N/A | SqlDatabaseScript
SqlScriptQuery | N/A | SqlDatabaseScriptQuery
SqlServerEndpointState | N/A | SqlEndpointState

To me, this makes for cleaner, more-easily understood resources that are more closely aligned with the underlying SMO objects that are being modified. Any resources I left off that list would not require a change.

**Comment by johlju** [comment]
@nabrond thanks for your input. That falls inline with my initial proposal. `SqlServerEndpointState` will be deprecated in a PR that is gonna be merged today so we can ignore that resource (that is why I wasn't in the list).

In regards to `SqlScript` and `SqlScriptQuery` I don't think it is appropriate to add _Database_ to its name because that would imply you can only run queries against a database when it is possible to manage the entire SQL Server with that resource if you like.  🤔

**Comment by johlju** [comment]
> Re the replication discussion, technology wise some of it would be considered instance level, and other parts are database level.

@codykonior if you are familiar with replication would you say that the parts that targets database level should be separate resources than those  that target instance level?

**Comment by johlju** [comment]
I added a agenda entry for this issue in the next Community Call. I hope we have time to discuss this.

I made a mindmap over how I think the resource is placed against "objects" in an instance.

**Legend:**
 - Green: I think the name is correct.
 - Red: Being discussed in this issue.
 - Orange: To me the name feel inappropriate together with the rest of the resource in same grouping.

----

If any should have _Server_ in its name it is these. ;) But I think the names are good as-is.

![image](https://user-images.githubusercontent.com/7189721/82233802-d50b7800-9930-11ea-941e-2e9a7d5607f8.png)

----

This resource name is good as-is too.

![image](https://user-images.githubusercontent.com/7189721/82233831-de94e000-9930-11ea-84fc-386864185ba3.png)

----
Looking at the mindmap below we see a pattern where most of the resource that have _Server_ in its name are grouped together in "Configuration/Management". This gets me thinking that maybe the only resources that should be renamed are the ones in the table below, but then we still have an the initial issue suggestion that a the word _Server_ could be misleading, also looking at this the resources SqlScript and SqlScriptQuery have the wrong name compared to the other resources in that group.

Current name | Suggested name
-- | --
SqlServerPermission| SqlPermission
SqlServerLogin | SqlLogin
SqlServerEndpoint| SqlEndpoint
SqlServerEndpointPermission| SqlPermission

Looking at the group "Configuration/Management" those could be renamed to have _Instance_ instead of _Server_. That would make SqlInstanceScript and SqlInstanceScriptQuery.

**But I still inclined to think that we could just remove the word _Server_ from the resource names.** 🤔  

![image](https://user-images.githubusercontent.com/7189721/82233611-91187300-9930-11ea-9988-c2f06d8d16c9.png)

**Comment by johlju** [comment]
I mentioned this issue in the DSC Community Call so let's wait until at least 1st June for more comments from the community. 

**If you vote _against_ the below statement then please comment below:**

- Remove the word _Server_ from the resource names and do not replace it with anything else (`SqlServer*` to `Sql*`)

**Comment by johlju** [comment]
I have now sent in PR #1565 that will rename the resource. 🙂
