### ISSUE TITLE
SqlAlwaysOnService -SQL 2019 on windows 2019-  Getting WMI error

### ISSUE THREAD

**Issue by pra6hu** [dsccommunity/SqlServerDsc#1607]
#### Verbose logs showing the problem

 ```
PowerShell DSC resource DSC_SqlAlwaysOnService  failed to execute Set-TargetResource functionality with error message: The running command stopped because the 
preference variable "ErrorActionPreference" or common parameter is set to Stop: An attempt to connect to WMI on ‘server01’ failed with the following error: SQL 
Server WMI provider is not available on server01.. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost 
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration EnableAlwaysOn
{
    Import-DscResource -ModuleName SqlServerDsc

    Node 'localhost' {
        SqlAlwaysOnService 'EnableAlwaysOn'
        {
            Ensure               = 'Present'
            InstanceName         = $instance
            ServerName           = $env:computername
        }
    }
}
```

#### SQL Server edition and version the target node is running

Microsoft SQL Server 2019 (RTM-CU5) (KB4552255) - 15.0.4043.16 (X64)   Jun 10 2020 18:25:25   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node

                                                                               
SqlServer 21.0.17279 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.0.17279\SqlServer.psd1           
SQLPS     15.0       C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1 

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US} 

#### Version and build of PowerShell the target node is running

 Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.17763.1007                                                                                                                         
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.17763.1007                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                        

#### Version of the DSC module that was used

 Name         Version  Path                                                                              
----         -------  ----                                                                              
SqlServerDsc 14.2.0   C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\14.2.0\SqlServerDsc.psd1  
SqlServerDsc 11.4.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\11.4.0.0\SqlServerDsc.psd1

**Comment by johlju** [comment]
Curious if you can enable it SQL Server Configuration Manager without any problem?

**Comment by pra6hu** [comment]
@johlju  yes, able to do it manually. Did't faced this issue on SQL 2016.

**Comment by johlju** [comment]
I have not run this resource on SQL Server 2019 yet so not sure what can be wrong.

Can you provide verbose logs of the DSC run thats shows what happens before the error happens? Can you narrow down to what the resource tries to do when the error happens? Is there any other error message that can help narrow it down, like if something is missing on the node that is needed for SQL Server 2019?

**Comment by pra6hu** [comment]
While Checking found that version of module `SqlServer` with version '21.0.17279' was used. 
Updated with latest version of module SqlServer to `21.1.18226` . It fixed the issue.
@johlju  Thanks for checking!

**Comment by johlju** [comment]
Thanks for reporting the solution! 😄  I close the issue at this time.
