### ISSUE TITLE
SqlSetup - Parameter Ensure

### ISSUE THREAD

**Issue by DirkHuste** [dsccommunity/SqlServerDsc#1614]
Feature Request SqlSetup - Parameter Ensure = 'Present' / Ensure = 'Absent'

Hello,

i created a configuration for a SQL-server installation containing an instance + database + login and applied it to a host . It works like a charm.

Now i want to do a clean uninstallation. As far as i see for the database + login there is a parameter Ensure present, so i can rollback. For the SqlSetup i'm still missing the parameter, to do the uninstallation of the instance.

Thank you for your support in advance.

**Comment by johlju** [comment]
This is being tracked in issue https://github.com/dsccommunity/SqlServerDsc/issues/181 but no one in the community have started to work on it yet.

I'm closing this as a duplicate.
