### ISSUE TITLE
[SQLLogin] Shouldn't the ServerName property be a Key parameter?

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/SqlServerDsc#1624]
#### Details of the scenario you tried and the problem that is occurring
I am trying to use the SQLLogin to add logins to several SQL instances. Unfortunately I am getting a conflict detected error. During troubleshooting I discovered that just the Name and Instance parameters are Key parameters. So if I want to add the same account to two instances which have the same name, the conflict error is thrown.

#### Verbose logs showing the problem
```
Test-ConflictingResources : A conflict was detected between resources 
'[SqlLogin]AddServicesAppPoolLoginToInstance_SQL01::[CompositeResource]CompositeResource
(C:\src\Example\CompositeResource.schema.psm1::120::9::SqlLogin)' 
and '[SqlLogin]AddServicesAppPoolLoginToInstance_SQL02::[CompositeResource]CompositeResource
(C:\src\Example\CompositeResource.schema.psm1::120::9::SqlLogin)' 
in node 'SQL01'. Resources have identical key properties but there are differences in the following non-key properties: 
'ServerName'. Values 'SQL01' don't match values 'SQL02'. Please update these property values so that they are identical in both 
cases.
```

#### Suggested solution to the issue
Make the ServerName parameter Key

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        SqlLogin "AddWebAppPoolLoginToInstance_$sqlInstance"
        {
            ServerName           = 'SQL01'
            InstanceName         = 'MSSQLSERVER'
            Name                 = 'domain\user1'
            LoginType            = 'WindowsUser'
            Ensure               = 'Present'
        }

        SqlLogin "AddWebAppPoolLoginToInstance_$sqlInstance"
        {
            ServerName           = 'SQL02'
            InstanceName         = 'MSSQLSERVER'
            Name                 = 'domain\user1'
            LoginType            = 'WindowsUser'
            Ensure               = 'Present'
        }
```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
v21.1.18228

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3930.amd64fre.rs1_release.200901-1914
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                             
----                           -----                                                                                                                                             
PSVersion                      5.1.14393.3866                                                                                                                                    
PSEdition                      Desktop                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                           
BuildVersion                   10.0.14393.3866                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                               
SerializationVersion           1.1.0.1      

#### Version of the DSC module that was used
v14.2.1

**Comment by johlju** [comment]
So this is an issue when using one configuration to configure two nodes. This is to be expected when using one node to configure two other nodes. Shouldn’t this instead be two separate configurations that is pushed to the respective node. A configuration that is making sure the individual node is in desired state.

**Comment by ykuijs** [comment]
I get where you are going, but in this case the SQL servers are managed by a DBA team (not using DSC). The SharePoint team is creating databases and managing permissions on those databases.

Since the SQL environment is using SQL Always-On for HA, we have to sync the used logins to all nodes in the Always-On cluster (by default SharePoint manages only on the instance where the databases are created). Since we are using DSC to manage SharePoint, I was trying to use this resource to accomplish this task....unfortunately without luck. This would be solved if the Servername parameter would be Key ;-)

**Comment by johlju** [comment]
I really don't see the solution is to make a breaking change in every resource. I think what you are looking for is the missing resource discussed in the issue https://github.com/dsccommunity/SqlServerDsc/issues/86. It is not just logins that need to be synced, there are also scenarios where jobs need to be synced as well to make sure they are run on the primary node (that is known to be online).

**Comment by Fiander** [comment]
This is one of those moments the DBATools come in.
sync-dbaAvailabilityGroup can be used to sync all needed items between all nodes of a Availability Group.
As long the AG is not a DAG, this works well. For a DAG more work is needed.
[https://github.com/sqlcollaborative/dbatools/issues/6793](url)
but that is a slow process, that copies all to all nodes.

As for the discussion:
For me it is simple, I need both parts ( servername AND instancename) to unique identify a SQLServerInstance.
When I only use the servername, it is assumed I mean the default instance.
When I only use the instancename, it is assumed I mean the localhost.

I am most frequently told that assumptions are the mother of all XXXXX ups.
so to be certain, I think server and instance should together be the key.


But I think the most elegant way to solve this would be 
`SqlLogin "AddWebAppPoolLoginToInstance_$sqlInstance"
        {
            ServerName           = 'Listener.Contoso.com'
            InstanceName         = 'MSSQLSERVER'
            Name                 = 'domain\user1'
            LoginType            = 'WindowsUser'
            Ensure               = 'Present'
            AcrossAvailabilitieGroup = 'AG01' 
        }`
This would make it connect to the listener who is always on ;-)
and should install the login to all nodes of the AG ( or DAG when needed)
When at later time a node is added to the alwaysOn cluster, DSC should pick this up. 
No need for a new configuration.

SqlJobs could be done the same way.

this solution does not mean I don't support adding the servername to the key. that I do. The downside is that it would be a breaking change, with potentially a lot of work.

**Comment by ykuijs** [comment]
The missing resource you are referring to indeed also solves my issue, but I agree with @Fiander: The server and instance names should have always been key parameters. Those are the two pieces of information to identify the instance you want to use, with the greatest flexibility. If I am not using two SQL instances without AGs, which are both running the same instance name, the missing resource wouldn't fix the issue.

I know that most SQLServerDsc are targetting the local server, but especially resources like SQLLogin is a resource that can be used remotely as well. In my customers case, the SharePoint admins own the accounts used for SharePoint and manages the databases (SharePoint recommends to have dbcreator and securityadmin privileges for the SharePoint Farm account). So as soon as I add a new IIS application pool account SharePoint creates the SQL login to the instance running the listener. When a fail-over occurs, errors will be thrown. By allowing the SharePoint config to create these logins on all AG instances as soon as they add functionality, the dependency on SQL admins is removed..

I realize that currently this is a breaking change, but that should stop us from doing the right thing. Maybe not in a minor release, but in the next major release?

**Comment by johlju** [comment]
ServerName is meant to be set to the listener as @Fiander points out. Then there should be a resource that replicates the logins to all replicas, or maybe better to add that replication functionality to SqlLogon resource that @Fiander suggests.   

By adding ServerName as a Key would introduce the the possibility of ping-pong behaviour when the same configuration could change the same login by referencing the instance in various ways; listener, localhost, computer name, IP address. All those would become unique in the same configuration (for example partial configurations joined together). The way it is implemented now prevents that. There is still a potential for ping-pong behaviour today if a jump-server (SharePoint node) uses the listener on two different jump-servers in two different configurations, but that can't be prevented. 

@ykuijs could you use a composite resource that wraps SqlLogin for each SQL Server node for what you are after until the above is sorted?
