### ISSUE TITLE
Clarify use of BrowserSvcStartupType when used with failover installs.

### ISSUE THREAD

**Issue by ddubick** [dsccommunity/SqlServerDsc#1627]
`    Action: InstallFailoverCluster
    BrowserSvcStartupType: null 
`
Hello, I would request that you clarify in the documentation the usage of the BrowserSvcStartupType parameter.  It took me a day of troubleshooting and finally digging through the code to realize that I needed to specify BrowserSvcStartupType: null  when using Action: InstallFailoverCluster (and AddNode) - and probably the two other cluster options.

Thank you.

**Comment by johlju** [comment]
Thank you for sending in a issue for this! It will help another person and I label this so someone in the community can update the documentation.

**Comment by ddubick** [comment]
To clarify, any other option on BrowserSvcStartupType results in the setup.exe complaining that BROWSERSVCSTARTUPTYPE cannot be used with action INSTALLFAILOVERCLUSTER.
