### ISSUE TITLE
SQLSetup SQL 2016 CU  SQLServer2016-KB4577775-x64 is not applying on existing SQL instance using SQL setup resource

### ISSUE THREAD

**Issue by SarmaChavali** [dsccommunity/SqlServerDsc#1629]
#### Details of the scenario you tried and the problem that is occurring
1)SQL server is installed using DSC
2)Couple of months later try to apply the SQL 2016 SP2 CU14  by placing the file in Updates folder and run the script

Some reason the CU wasn't picked up, Am i doing something wrong or missing
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### SQL Server PowerShell modules present on the target node

Name      Version    Path                                                                                     
----      -------    ----                                                                                     
SqlServer 21.1.18218 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18218\SqlServer.psd1           
SQLPS     1.0        C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### Version and build of PowerShell the target node is running

OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3503.amd64fre.rs1_release.200131-0410
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used

SqlServerDsc 13.3.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.3.0\SqlServerDsc.psd1

**Comment by johlju** [comment]
There is no evaluation of versions in SqlSetup currently. Any update path specified in the configuration is used only during setup the first time. I'm not sure it is possible to use setup.exe to apply a CU after the fact either. 🤔 If you want to apply a CU I suggest another option that SqlSetup resource.
