### ISSUE TITLE
issue deploying DREPLAY_CTLR and DREPLAY_CLT on SQL 2019 on Win 2019

### ISSUE THREAD

**Issue by bytejunkie** [dsccommunity/SqlServerDsc#1630]
#### Details of the scenario you tried and the problem that is occurring
Im running SQLServerDSC under an ansible installation pattern. 

The installer works fine for all componenets, including DREPLAY_CTLR and DREPLAY_CLT. However the DSC module reports an installation failure.

#### Verbose logs showing the problem

ansible output:
_fatal: [ansibleprovision_platform_windows_817647_2020-11-06]: FAILED! => {
    "changed": false,
    "module_version": "14.2.1",
    "reboot_required": false
}

MSG:

Failed to invoke DSC Set method: PowerShell DSC resource DSC_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state.__

from the summary.txt

_Overall summary:
  Final result:                  Passed
. . . 
  Feature:                       Distributed Replay Controller
  Status:                        Passed
_

#### Suggested solution to the issue

I dont really have a solution, I guess im posting to find out if this is known behaviour, or if I've missed something in config. Has anyone else got this working?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### SQL Server edition and version the target node is running

SQL Server 2019 Developer, running on Windows 2019

#### SQL Server PowerShell modules present on the target node

Name  Version Path                                                                                     
----  ------- ----                                                                                     
SQLPS 15.0    C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

Name                           Value                                                                          
----                           -----                                                                          
PSVersion                      5.1.17763.1490                                                                 
PSEdition                      Desktop                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                        
BuildVersion                   10.0.17763.1490                                                                
CLRVersion                     4.0.30319.42000                                                                
WSManStackVersion              3.0                                                                            
PSRemotingProtocolVersion      2.3                                                                            
SerializationVersion           1.1.0.1      

#### Version of the DSC module that was used

Name         Version Path                                                                            
----         ------- ----                                                                            
SqlServerDsc 14.2.1  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\14.2.1\SqlServerDsc.psd1

**Comment by johlju** [comment]
This is because the function Get-TargetResource not yet understands how to recognize if the features are installed. It is being tracked in issue #1168. Happy to review a PR that adds this functionality.

**Comment by bytejunkie** [comment]
understood, thanks for the reply. 

I'll take a look at the module, but I'm not totally sure my codes kills will be up to this.

**Comment by johlju** [comment]
If you can figure out how to detect if the features are installed (registry entries?) then I think it would be easy enough to look at the code for similar features. 

Let me know if you need any help.

Closing this issue and let’s continue the discussion in issue #1168.
