### ISSUE TITLE
Help Wanted: Convert tests to Pester 5

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1654]
I appreciate if you are willing to help converting tests. 

There is a PR #1550 currently in draft where community can add converted test that locally passes in Pester 5. Due to that Pester 5 is not really backward compatible ALL test must be converted and merged in one go. Pester 5 is a big improvement how to write and adds stability to run tests. Can we get the tests converted we can use future features that will be added to Pester.

## How to help

1. Clone the working branch in @johlju's fork to the current folder. 
```bash
git clone -b f/support-pester-5 https://github.com/johlju/SqlServerDsc
cd SqlServerDsc
```
2. Create your own working-branch
```bash
git checkout -b f/my-working-branch
```
3. Run the following to prepare the environment.
```powershell
# Downloads prerequisites into the './output' folder 
.\build.ps1 -ResolveDependency -Tasks noop
# Builds the module and prepares to run/debug tests (builds the module to './output'.
.\build.ps1 -Tasks build
```
4. Convert a test below that haven't yet been converted.
5. You can run tests by using `Invoke-Pester` from console like below, or run/debug the from within Visual Studio code (see note above).
```
# run entire file
Invoke-Pester .\tests\Unit\DSC_SqlProtocol.Tests.ps1 -Output Detailed
# or run just the describe block with tag 'Get'
Invoke-Pester .\tests\Unit\DSC_SqlProtocol.Tests.ps1 -Output Detailed -Tag Get 
```
6. Create a remote to your own fork (assumes you have forked it in GitHub already).
    Replace the URL with your username, e.g. `https://github.com/johlju/SqlServerDsc` 
```bash
git remote add my https://github.com/<MyGitHubUserName>/SqlServerDsc
```
7. Push the changes to your fork.
```bash
git push my
```
8. Send a pull request (PR) to @johlju's fork https://github.com/johlju/SqlServerDsc and target the working branch **f/support-pester-5**.
9. Mention @johlju in the PR to merge it. On merge it will automatically update PR #1550.
10. @johlju will update this issue to check off any finished tests.

> NOTE: If you use _Visual Studio Code_ to write and debug test make sure to run `.\build.ps -task build` in the
>_PowerShell Integrated Console_ inside _Visual Studio Code_ . This makes sure the environment is ready to
> debug tests. If the module have already been built then fastest is to run `.\build.ps -task noop`.

## What needs to be done

These tests need to be converted. See an existing converted unit test to see the pattern needed.

Read the blog post to know how Pester 5 tests should look like: https://dsccommunity.org/blog/convert-tests-to-pester5-for-dsc-community-repository/

### Unit tests

These unit tests need to be converted. 

- [ ] DSC_SqlAG.Tests.ps1
- [ ] DSC_SqlAGDatabase.Tests.ps1
- [ ] DSC_SqlAGListener.Tests.ps1
- [ ] DSC_SqlAGReplica.Tests.ps1
- [x] DSC_SqlAgentAlert.Tests.ps1
- [x] DSC_SqlAgentFailsafe.Tests.ps1
- [x] DSC_SqlAgentOperator.Tests.ps1
- [x] DSC_SqlAlias.Tests.ps1
- [x] DSC_SqlAlwaysOnService.Tests.ps1
- [x] DSC_SqlConfiguration.Tests.ps1
- [x] DSC_SqlDatabase.Tests.ps1
- [x] DSC_SqlDatabaseDefaultLocation.Tests.ps1
- [x] DSC_SqlDatabaseMail.Tests.ps1
- [x] DSC_SqlDatabaseObjectPermission.Tests.ps1
- [x] DSC_SqlDatabasePermission.Tests.ps1
- [x] DSC_SqlDatabaseRole.Tests.ps1
- [x] DSC_SqlDatabaseUser.Tests.ps1
- [x] DSC_SqlEndpoint.Tests.ps1
- [x] DSC_SqlEndpointPermission.Tests.ps1
- [x] DSC_SqlLogin.Tests.ps1
- [x] DSC_SqlMaxDop.Tests.ps1
- [x] DSC_SqlMemory.Tests.ps1
- [x] DSC_SqlPermission.Tests.ps1
- [x] DSC_SqlProtocol.Tests.ps1
- [x] DSC_SqlProtocolTcpIp.Tests.ps1
- [x] DSC_SqlRS.Tests.ps1
- [x] DSC_SqlRSSetup.Tests.ps1
- [x] DSC_SqlReplication.Tests.ps1
- [x] DSC_SqlRole.Tests.ps1
- [x] DSC_SqlScript.Tests.ps1
- [x] DSC_SqlScriptQuery.Tests.ps1
- [x] DSC_SqlSecureConnection.Tests.ps1
- [x] DSC_SqlServiceAccount.Tests.ps1
- [x] DSC_SqlSetup.Tests.ps1
- [x] DSC_SqlTraceFlag.Tests.ps1
- [x] DSC_SqlWaitForAG.Tests.ps1
- [x] DSC_SqlWindowsFirewall.Tests.ps1
- [x] SqlServerDSC.Common.Tests.ps1
- [x] SqlServerDsc.AnalyzerRules.Tests.ps1

### Integration tests

These integration tests need to be converted. 

- [x] DSC_SqlAgentAlert.Integration.Tests.ps1
- [x] DSC_SqlAgentFailsafe.Integration.Tests.ps1
- [x] DSC_SqlAgentOperator.Integration.Tests.ps1
- [x] DSC_SqlAlwaysOnService.Integration.Tests.ps1
- [x] DSC_SqlDatabase.Integration.Tests.ps1
- [x] DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1
- [x] DSC_SqlDatabaseMail.Integration.Tests.ps1
- [x] DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1
- [x] DSC_SqlDatabasePermission.Integration.Tests.ps1
- [x] DSC_SqlDatabaseUser.Integration.Tests.ps1
- [x] DSC_SqlEndpoint.Integration.Tests.ps1
- [x] DSC_SqlLogin.Integration.Tests.ps1
- [x] DSC_SqlProtocol.Integration.Tests.ps1
- [x] DSC_SqlProtocolTcpIp.Integration.Tests.ps1
- [x] DSC_SqlRS.Integration.Tests.ps1
- [x] DSC_SqlRSSetup.Integration.Tests.ps1
- [x] DSC_SqlReplication.Integration.Tests.ps1
- [x] DSC_SqlRole.Integration.Tests.ps1
- [x] DSC_SqlScript.Integration.Tests.ps1
- [x] DSC_SqlScriptQuery.Integration.Tests.ps1
- [x] DSC_SqlSecureConnection.Integration.Tests.ps1
- [x] DSC_SqlServiceAccount.Integration.Tests.ps1
- [x] DSC_SqlSetup.Integration.Tests.ps1

**Comment by Fiander** [comment]
Hi,
hope you had a fine christmas :-)

i just finished SqlRole and SqlTraceFlag, but i am kinda stuck at step 5 in the above example.

thanks to step 1 i only have a local branch, and have no clue how to create a pull request for that (local) branch.
did i mis something? am i stupid, or should i fork it first next time before entering step 1 ( or do all of the three options validate to $true?)

**Comment by johlju** [comment]
Ah, good point, I missed that step. 😊 You have to add a remote to your own fork.

```
git remote add my https://gitHub.com/fiander/SqlServerDsc
``` 

I think you can also branch out by running (I’m not sure it possible to rename on push):

```
git push my new-working-branch
```
Or just do this which will push current branch to your fork. 

```
git push my
```

Then send in that working branch as a PR to my fork.

**Comment by johlju** [comment]
Updated the issue description with the above.

**Comment by johlju** [comment]
The remaining tests to refactor are being tracked in issues #1752, #1753, #1754.
