### ISSUE TITLE
Backup file path error

### ISSUE THREAD

**Issue by gpandeti** [dsccommunity/SqlServerDsc#1671]
We store our backups in a file share. Whenever I mention my backup file share in SqlSetupDsc it is giving me an error saying the root of the path '\\xxxxx\xx\xxxx' doesn't exist. Please let me know through what credentials it will try to access backup drive or any other thoughts regarding this error.

**Comment by johlju** [comment]
If you mean the setup argument `/SQLBACKUPDIR`. The executable `setup.exe` is run with the same credential that you provide in the built-in parameter `PsDscRunAsCredential`. If that is not provided it is run as `SYSTEM`. You can read about it here https://github.com/dsccommunity/SqlServerDsc/wiki/SqlSetup#credentials-for-running-the-resource.
