### ISSUE TITLE
The term 'SQLSetup' is not recognized 

### ISSUE THREAD

**Issue by mujtabazeshan** [dsccommunity/SqlServerDsc#1693]
Sometime running the setup is fine and sometimes i get stuck on this error that wont go away no matter what i do - Get_Modules shows that the dsc module is loaded fine but it still cant get to SQLSetup - i am running it on Server2019 and with SQL2019 - sometimes when i create a new VM and this runs fine after i copy the module to ProgramFiles/PS/Modules folder but if i restore the same VM to the previous state(before running setup) then try to run the setup again - i keep getting this error - i am using VirtualBox - can some one help???

![image](https://user-images.githubusercontent.com/50028501/108645088-9b4b3d00-747f-11eb-9555-dbca6e4161f3.png)

[New Text Document.txt](https://github.com/dsccommunity/SqlServerDsc/files/6018958/New.Text.Document.txt)

**Comment by johlju** [comment]
I have never seen that error before. It looks like PowerShell can parse the script. I use Hyper-V or VMware to revert to a previous snapshot and have not seen this. Although I push the configurations remotely in the lab, and the node download any dependent DSC resource modules from a share. I'm guessing you run everything locally and then revert to a previous state which have the scripts already installed. But I would expect that to work as well. Sorry I couldn't be more of help, but it seems like a PowerShell parsing error (not related to the actual DSC resource) when the the script is run and PowerShell should compile the configuration.

**Comment by mujtabazeshan** [comment]
thank you Johan for the reply. sorry my main reason for using the virtualbox is that its free :D i have setup an internal network with domain server with AD, DNS and DHCP windows server 2019 with no access to internet - i use the same base for all the VMs as linked clones and sysprep them before attaching to DC. and before running the powershell scripts i simply copy all the modules to the powershell program files module folder. i am trying to create a standalone script to install SQL Server with encrypted passwords.
i am also using PSDscAllowDomainUser = $true and New-SelfSignedCertificate -Type DocumentEncryptionCertLegacyCsp -DnsName $cname -HashAlgorithm SHA256 to generate encrypted passwords in the mof file and passing the thumbprint to the config file in LocalConfigurationManager.
you are right the error is generated before Set-DscLocalConfigurationManager. do you think this has to do something with windows server 2019 because i could run this without any issues on servers before that. 
i will try skipping creating the certificate and see if this works fine without it. anyhow i really appreciate your response.

**Comment by johlju** [comment]
There are normally no problems running PowerShell scripts on Windows Server 2019. I’m guessing that there are something happening when you revert to the prior state.

**Comment by mujtabazeshan** [comment]
thank you Johan - appreciate you

**Comment by mujtabazeshan** [comment]
the problem is that some times when i create a new VM, it still wont work and sometimes it will. very weird. anyhow i will keep digging on this. I do have another question though, is it possible to encrypt passwords in mof without the use of certificates?

**Comment by johlju** [comment]
Maybe something haven’t started correctly on the machine before you run?

With mof you can only encrypt using certificate.

**Comment by mujtabazeshan** [comment]
Hi Johan, i think i have found the problem. Copying the modules whether using copy-item or xcopy is creating these problems (i could be using them wrong as well) so sometimes it would run and sometime(mostly) give that error. anyhow i used the zip modules and using Expand-Archive is works like a charm. thank you very much for your attention. :D
