### ISSUE TITLE
Action = Uninstall is not an allowed parameter in SQLSetup resource of dsc

### ISSUE THREAD

**Issue by romilgupta28** [dsccommunity/SqlServerDsc#1700]
Sample code

- name: SQL Server | Un-Install SQL Server 2019 Enterprise Edition | Instance Name {{ sql_instance_name }} when provider is {{ provider }}
      win_dsc:
        resource_name: SQLSetup
        Action: Uninstall
        ErrorReporting: False
        UpdateEnabled: True
        SourcePath: "{{ sql_enterprisesetup_working_directory }}"
        InstanceName: "{{ sql_instance_name }}"
        Features: "{{ sql_features }}"

Error Message: value of Action must be one of: Install, Upgrade, InstallFailoverCluster, AddNode, PrepareFailoverCluster, CompleteFailoverCluster. Got no match for: Uninstall"

Further check :
https://www.powershellgallery.com/packages/SqlServerDsc/14.2.1/Content/DSCResources%5CDSC_SqlSetup%5Cen-US%5Cabout_SqlSetup.help.txt

This link also confirms the error message. Please advise if something I'm doing incorrect or is it a missing feature.

**Comment by johlju** [comment]
That action have yet been added by the community, but I'm happily review a PR that adds the functionality if you like to add it. This is tracked in issue https://github.com/dsccommunity/SqlServerDsc/issues/181.

Closing this issue as duplicate, please continue conversation regarding 'uninstall' in issue https://github.com/dsccommunity/SqlServerDsc/issues/181.
