### ISSUE TITLE
SqlEndpoint for DatabaseMirroring throws CimException

### ISSUE THREAD

**Issue by jrobiii** [dsccommunity/SqlServerDsc#1701]
I'm trying to reassign the owner of the database mirroring ENDPOINT to `sa`.  The server in question has several Availability Groups.

This is my configuration (replaced actual computer name with `{ServerName}`}
```powershell
            SqlEndpoint "SQLConfigureEndpoint - {ServerName}"
            {
                EndpointName = 'HADR'
                EndpointType = 'DatabaseMirroring'
                InstanceName = 'MSSQLSERVER'
                Owner        = 'sa'
                Ensure       = 'Present'
            }
```

Here is the DSC output.  As it turns out this is also all that is in the event log on the target server as well:
```
'{ServerName}' node '[SqlEndpoint]SQLConfigureEndpoint - {ServerName}' resource instance not in desired state

CimException: Exception calling "Create" with "0" argument(s): "Create failed for Endpoint 'HADR'. "
CimException: Exception calling "Start" with "0" argument(s): "Start failed for Endpoint 'HADR'. "
InvalidOperation: The PowerShell DSC resource '[SqlEndpoint]SQLConfigureEndpoint - {ServerName}' with SourceInfo 'C:\workspaces\GitHub\mssql-windows\Configuration.ps1::299::13::SqlEndpoint' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
CimException: The SendConfigurationApply function did not succeed.
```

I've been googling about for hours and have not found anything helpful.

**Comment by johlju** [comment]
Doesn't sound like it should call create if the endpoint already exist. Can you run the configuration with the verbose output so we can see what code paths it takes?

**Comment by beargle** [comment]
The default endpoint name created with an availability group is `Hadr_endpoint`, instead of `HADR`.

Guessing the `EndpointName` value in the configuration here does not match the AG endpoint name on the target.

**Comment by jrobiii** [comment]
Thanks for the find.  The name was wrong and correcting it allowed me to continue.
