### ISSUE TITLE
SqlPermission: Add support for additional server permissions

### ISSUE THREAD

**Issue by beargle** [dsccommunity/SqlServerDsc#1704]
# Background
In the  `SqlPermission` resource, it seems these are the currently supported server permissions

https://github.com/dsccommunity/SqlServerDsc/blob/49f78a8b12c0f540ef76cdcbf6605fffa30c17fa/source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1#L45

It would be useful to have additional permissions available (e.g. `ConnectAnyDatabase`, `ViewAnyDefinition`).

A complete list is available via [ServerPermissionSetValue](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.serverpermissionsetvalue) enum

```PowerShell
✦ ❯ ([Microsoft.SqlServer.Management.Smo.ServerPermissionSetValue]).GetEnumNames()
AdministerBulkOperations
AlterAnyCredential
AlterAnyConnection
AlterAnyDatabase
AlterAnyEventNotification
AlterAnyEndpoint
AlterAnyLogin
AlterAnyLinkedServer
AlterResources
AlterServerState
AlterSettings
AlterTrace
AuthenticateServer
ControlServer
ConnectSql
CreateAnyDatabase
CreateDdlEventNotification
CreateEndpoint
CreateTraceEventNotification
Shutdown
ViewAnyDefinition
ViewAnyDatabase
ViewServerState
ExternalAccessAssembly
UnsafeAssembly
AlterAnyServerAudit
AlterAnyServerRole
CreateServerRole
AlterAnyAvailabilityGroup
CreateAvailabilityGroup
AlterAnyEventSession
SelectAllUserSecurables
ConnectAnyDatabase
ImpersonateAnyLogin
```

I'm guessing the available permissions _could_ vary based on the SMO version.

# Questions

Wondering if there is any desire to derive the `$Permission` parameter validation from these enum names?

Or is it preferred to maintain a hardcoded permission list, for a more stable interface?

**Comment by johlju** [comment]
Happy a PR that adds more permissions and unit and integration tests that covers the additional permissions.
