### ISSUE TITLE
Docs: READMEs switched between two functions

### ISSUE THREAD

**Issue by LowlyDBA** [dsccommunity/SqlServerDsc#1709]
The wiki pages for [SqlAgentFailsafe](https://github.com/dsccommunity/SqlServerDsc/wiki/SqlAgentFailsafe) and [SqlAgentAlert](https://github.com/dsccommunity/SqlServerDsc/wiki/SqlAgentAlert) have their README files swapped.

**Comment by johlju** [comment]
Good catch! You are correct the files here should be switched. That will solve it when the documentation is regenerated on publish.

- [source/DSCResources/DSC_SqlAgentAlert/README.md](https://github.com/dsccommunity/SqlServerDsc/blob/main/source/DSCResources/DSC_SqlAgentAlert/README.md)
- [source/DSCResources/DSC_SqlAgentFailsafe/README.md](https://github.com/dsccommunity/SqlServerDsc/blob/main/source/DSCResources/DSC_SqlAgentFailsafe/README.md)
