### ISSUE TITLE
SqlAg: DtcSupportEnabled should be updatable

### ISSUE THREAD

**Issue by zevanreg** [dsccommunity/SqlServerDsc#1735]
Documentation for SqlAG resource says DtcSupportEnabled "can not be altered once the availability group is created and is ignored if it is the case.". But [Configure distributed transactions for an Always On availability group](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-availability-group-for-distributed-transactions?view=sql-server-2016#alter-an-availability-group-for-distributed-transactions) mentions this is actually possible starting with SQL Server 2016 SP2. Any plans to implement this?

**Comment by johlju** [comment]
Happy to review a PR with that change the resource to support this, with the appropriate accompanied tests.
