### ISSUE TITLE
PowerShell DSC & Credential, Windows Patch, Problem(s)/Issue

### ISSUE THREAD

**Issue by SphenicPaul** [dsccommunity/SqlServerDsc#1763]
Hi @johlju 

Just flagging this as this seems to have surfaced via the SqlServerDsc resources, but looks to be a wider, PowerShell DSC and Windows updates problem/issues.

We were/are seeing this error:

`The password supplied to the Desired State Configuration resource DSC_SQLSetup is not valid. The password cannot be null or empty.`

But looks to be the result of a Windows patch causing problems for credentials within PowerShell DSC - Related Twitter thread.
- https://twitter.com/RobertBiddle/status/1538287531833303042

Don't think it's a problem for this project to sort, but might save anyone else having this issue, a little time.

**Comment by johlju** [comment]
Yes, it is being discussed by the community in the [#dsc channel](https://dsccommunity.org/community/contact/), Robert is there as well. Last update in the channel was that Microsoft is working on it, but I don't have any details. I suggest opening a support case with MS if this is blocking production.

**Comment by johlju** [comment]
The build workers also have this issue so we can't release any new modules that runs integration tests, unless we disable them temporary, but rather not do that.

**Comment by johlju** [comment]
A fix should have been released with this weeks patches. Waiting for the build workers to get the patch, will close this after that.

**Comment by johlju** [comment]
The Azure DevOps build workers has gotten the patch now, that means that this issue is fixed . Closing this.
