### ISSUE TITLE
dsc is overwriting SQL Server Memory settings

### ISSUE THREAD

**Issue by vmusunoori6** [dsccommunity/SqlServerDsc#1765]
### Problem description

Hello,

SqlserverDsc is overwriting SQL Server memory settings. Server has 256GB RAM but dsc is setting max memory to 20GB and it's causing performance issues. I'm new to dsc and i just took over the system. How can I stop dsc from overwriting memory values on instance. 

Any help is appreciated. 

thanks

### Verbose logs

```text
no logs
```

### DSC configuration

```powershell
no idea about the code location
```

### Suggested solution

no idea

### SQL Server edition and version

```text
SQL Server 2016 enterprise edition
```

### SQL Server PowerShell modules

```text
sqlserver dsc
```

### Operating system

```text
Windows 2019 standard
```

### PowerShell version

```text
5.1.17763.2931
```

### SqlServerDsc version

```text
13.0.0
```

**Comment by johlju** [comment]
Push the correct DSC configuration to the node is the DSC configuration is wrong.

**Comment by vmusunoori6** [comment]
Thanks for the response @johlju but I have no idea how to check or push the correct DSC configuration. Can you please guide me on this as I just started reviewing this environment.
