### ISSUE TITLE
Why do I still need xFailoverCluster to set up a pure SQL AOAG-group?

### ISSUE THREAD

**Issue by DennisL68** [dsccommunity/SqlServerDsc#1792]
All references of using AOAG with DSC seem to require the setup of Windows Clustering as well.
However. my impression was that Windows Clustering Services no longer is a requirement for SQL Server 2019 when using AOAG?

**Comment by johlju** [comment]
Can be read about here [Failover Clustering and Always On Availability Groups (SQL Server)](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/failover-clustering-and-always-on-availability-groups-sql-server).

You coulfd also look into using a Detached Cluster.

**Comment by DennisL68** [comment]
I can't make heads or tail of this statement...

Is it that WFC is required but not a SQL FCI?

~~~
Always On availability groups, the high availability and disaster recovery solution introduced in SQL Server 2012 (11.x), requires Windows Server Failover Clustering (WSFC). Also, though Always On availability groups is not dependent upon SQL Server Failover Clustering...

[...]

To be enabled for Always On availability groups, an instance of SQL Server must reside on a WSFC node, and the WSFC and node must be online. Furthermore, each availability replica of a given availability group must reside on a different node of the same WSFC.
~~~

**Comment by johlju** [comment]
Exactly. I think if you read under the section “Windows Server Failover Clustering and Availability Groups” it explains the requirement.

**Comment by DennisL68** [comment]
So if I don't define any FCI, I don't need to configure NLB?

**Comment by johlju** [comment]
Not sure what you mean by NLB in this case. 

You install Failover Cluster service (and have a working cluster) and then you can install a standalone SQL Server instance. The standalone SQL Server instance does not use the Failover Cluster. When you enable the HADR on the SQL Server instance it will require that the Failover Cluster is present. When you create the Availability Group the Failover Cluster will be used as per the above article.

**Comment by DennisL68** [comment]
NLB = Virtual IP Address

**Comment by wsmelton** [comment]
Load Balancers and VIPs are external to SQL Server AG. Use of those is based on how you intend to support connectivity to the SQL Server Availability Group.
