### ISSUE TITLE
Test-IsNumericType: Move to DscResource.Common as a public command

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1795]
We should look at moving this to DscResource.Common (as a public command).

**Comment by hollanjs** [comment]
@johlju - while waiting on #1753, could you also assign this one to me? It is similar to the changes I made for `Assert-ElevatedUser`, so shouldn't take much time to cutover. I know you're busy, so I can get it all queued up on my end with no rush for integration.
