### ISSUE TITLE
Assert-ElevatedUser: Move to DscResource.Common as a public command

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1797]
We should look at moving this to DscResource.Common (as a public command).

**Comment by hollanjs** [comment]
Could you assign this issue to me? Looking for a "good first issue" and this looks about my speed.

**Comment by johlju** [comment]
This issues suggest that the command should be moved to another repository, DscResource.Common. When you send in a PR in that other repo, tag me in the repo. At the same time send in a PR to this repo removing the command referencing the other PR. 

Since this issue is a two parter I will assign you to this when I see the PR in the other repo. Cool?

**Comment by hollanjs** [comment]
Sounds good - thank you for the quick update.

**Comment by johlju** [comment]
Looking forward to review the PRs. Thank you! 😊
