### ISSUE TITLE
Invoke-SetupAction: New arguments for setup.exe with the GA release of SQL Server 2022

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1798]
It seems there has been new arguments added (at least one) and values for arguments has been changed (at least 'ARC' seems to have changed) for GA version of SQL Server 2022. 

The private function `Invoke-SetupAction` should be changed to reflect that, and also any public command that are affected by it.

**Comment by sara921-spec** [comment]
hi @johlju Does the new parameter propertycoveredbysa included in the new Sqldsc release? kind of fails for me.

**Comment by johlju** [comment]
The property `ProductCoveredBySA` is available in the command `Install-SqlDscServer`. If there an issue with it or a resource, please open a separate issue. 🙂

**Comment by sara921-spec** [comment]
Another QQ, does this parameter not available on the dsc-sqlsetup resource?
Or can we make it available?


Thanks,
Saravana

**Comment by johlju** [comment]
There are currently no resource that are using `Install-SqlDscResource`, until then that parameter must be added to SqlSetup resource. Please add that to an issue and I'm happy to review a PR that make that change.
