### ISSUE TITLE
SqlSetup: UpdateEnable argument is not supported for SQL Server 2008 R2

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#180]
When installing SQL Server 2008 R2 the installation throws an error. If you manually install SQL Server 2008 R2 with the same arguments as the xSQLServerSetup does, you get the following error saying that the `UpdateEnable` argument is not available.

![image](https://cloud.githubusercontent.com/assets/7189721/20021262/5c2b1922-a2d5-11e6-97a8-59fe4a8a87b3.png)

```
Microsoft (R) SQL Server 2008 Setup 10.00.6000.29
Copyright (c) Microsoft Corporation.  All rights reserved.

The following error occurred:
The setting 'UPDATEENABLED' specified is not recognized.

Error result: -2068578301
Result facility code: 1204
Result error code: 3
```

xSQLServerSetup default to use `/UpdateEnabled="False"` in the command line argument when starting the SQL Server installation. It should not add this argument when SQL major version is SQL Server 2008 R2.

**Comment by johlju** [comment]
I was wrong. `UpdateEnable` is not added by default at all. I had `UpdateEnable = $false` in my configuration file. After removing that, the installation worked flawless.

**Comment by johlju** [comment]
Reopening this so we can add this to the documentation. That parameter `UpdateEnable` does not work with SQL Server 2008 R2.

**Comment by thallesnoce** [comment]
I also faced this issue. 
The problem that I have identified is that the parameter of the source folder for the update is different as well.

SQL Server 2008 R2 the parameter is 
/PCUSOURCE

instead of 
/UPDATESOURCE

https://support.microsoft.com/en-ie/help/955392/how-to-update-or-slipstream-an-installation-of-sql-server-2008

**Comment by johlju** [comment]
Closing this as SQL Server 2008 R2 has reached end-of-life.
