### ISSUE TITLE
`Uninstall-SqlDscServer`: Does not support argument `SuppressPrivacyStatementNotice`

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1809]
### Problem description

When using the cmmand `Uninstall-SqlDscServer` it is not possible to suppress the privacy statement notice.

### Verbose logs

```text
PS C:\Windows\system32> Uninstall-SqlDscServer -MediaPath e:\ -InstanceName 'SQL2019' -Features 'SQLENGINE' -Verbose
VERBOSE: Specified setup executable arguments: /QUIET /ACTION=Uninstall /INSTANCENAME="SQL2019" /FEATURES=SQLENGINE

Invoke a Microsoft SQL Server setup action
Are you sure you want to invoke the setup action 'Uninstall'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
VERBOSE: Started the process with id 6968 using the path 'e:\setup.exe', and with a timeout value of 7200 seconds.
(SQLCOMMON0017)
Microsoft (R) SQL Server 2019 15.00.2000.05
Copyright (c) 2019 Microsoft.  All rights reserved.

SQL Server 2019 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2019 data processing and privacy controls, please see the Privacy Statement.
The following error occurred:
Instance Name SQL2019 for product Microsoft SQL Server doesn't exist. Specify a valid instance name.
```

### How to reproduce

On every run with the command, for example:

```powershell
Uninstall-SqlDscServer -MediaPath e:\ -InstanceName 'SQL2019' -Features 'SQLENGINE'
```

### Expected behavior

Should have an option to suppress the privacy statement notice.

### Current behavior

No option to suppress the privacy statement notice.

### Suggested solution

Add the parameter `SuppressPrivacyStatementNotice` to the command `Uninstall-SqlDscServer` and add the parameter to the Uninstall parameter set in the command `Invoke-Setup`.

### Operating system the target node is running

```text
Any
```

### PowerShell version and build the target node is running

```text
n/a
```

### Module version used

```text
Main branch.
```

**Comment by bleakprestiger** [comment]
@johlju can you please also assign this task to me ?

**Comment by johlju** [comment]
Done. Looking forward to a PR. 😊

**Comment by johlju** [comment]
@bleakprestiger are you still on this?

**Comment by bleakprestiger** [comment]
Yes

**Comment by johlju** [comment]
@bleakprestiger I have not seen and PR for this for over a month. I will remove the assignment within a week unless I see a PR, so someone else can work on this.
