### ISSUE TITLE
`Install-SqlServerDsc`: Wrongly says that parameter `AgtSvcAccount` must be specified

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1810]
### Problem description

When using `Install-SqlServerDsc` to install feature SQLENGINE it wrongly throws an exception saying that the parameter `AgtSvcAccount` must be specified.

### Verbose logs

```text
PS > Install-SqlDscServer -Install -AcceptLicensingTerms -MediaPath e:\ -InstanceName 'SQL2019' -Features 'SQLENGINE' -SqlSysAdminAccounts 'administrator' -Verbose
Assert-RequiredCommandParameter : The parameters 'AgtSvcAccount' must all be specified.
At C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\16.1.0\SqlServerDsc.psm1:2923 char:13
+             Assert-RequiredCommandParameter -BoundParameter $Property ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Command parameters:String) [Assert-RequiredCommandParameter], Excepti
   on
    + FullyQualifiedErrorId : ARCP0001,Assert-RequiredCommandParameter
```

### How to reproduce

Run the command:

```
PS > Install-SqlDscServer -Install -AcceptLicensingTerms -MediaPath e:\ -InstanceName 'SQL2019' -Features 'SQLENGINE' -SqlSysAdminAccounts 'administrator' -Verbose
```

### Expected behavior

Install the feature without needing to pass parameter `AgtSvcAccount`.

### Current behavior

Throws an exception.

### Suggested solution

Remove `'Install'` from the list here:
https://github.com/dsccommunity/SqlServerDsc/blob/8dde54df19ccbdb95629ec1c074e7a97acf229d2/source/Private/Assert-SetupActionProperties.ps1#L123

### Operating system the target node is running

```text
Any
```

### PowerShell version and build the target node is running

```text
n/a
```

### Module version used

```text
Main branch.
```

**Comment by bleakprestiger** [comment]
Can I take This Issue as well ?

**Comment by bleakprestiger** [comment]
@johlju , I have opened the pull request for the same. #1813

**Comment by bleakprestiger** [comment]
Thanks @johlju
