### ISSUE TITLE
`Get-SqlDscAudit`: Should not enforce to use parameter `Name`

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1812]
### Problem description

When running the command `Get-SqlDscAudit` without `Name` the command ask for a value for `Name` instead of returning all audits.

### Verbose logs

```text
PS > $serverObject | Get-SqlDscAudit

cmdlet Get-SqlDscAudit at command pipeline position 1
Supply values for the following parameters:
Name:
```

### How to reproduce

Run `Get-SqlDscAudit` without `Name` parameter.

### Expected behavior

Return all available audits.

### Current behavior

Stops and asks for a single audit name.

### Suggested solution

The parameter `Name` should not be mandatory. 

### Operating system the target node is running

```text
Any.
```

### PowerShell version and build the target node is running

```text
n/a
```

### Module version used

```text
Main branch.
```

**Comment by bleakprestiger** [comment]
Can I Take This Issue ?

**Comment by johlju** [comment]
You are so welcome, looking forward to review a PR. 🙂

**Comment by bleakprestiger** [comment]
Can you assign this issue to me.

**Comment by johlju** [comment]
Thought I could not assign other than members but I could. This is now assigned to you.

**Comment by bleakprestiger** [comment]
i had a minor doubt, so for creating audits what we could do ? for e.g. in order to test this Get-SqlDscAudit in powershell, we would have to create some audits, so how could we create the same ?

**Comment by johlju** [comment]
For this you only need to make a unit test to test the code change. In a unit test you just mock the audits with "mocking code". 

Take a look at the existing unit test and re-use the same principle to add a new Context- and It-block as necessary.

**Comment by bleakprestiger** [comment]
On analyzing the issue, it seems that the parameter `Name` is being used as a mandatory parameter, as it is being mentioned by the Mandatory Annotation.

**Comment by johlju** [comment]
Yes. But it should not need to be mandatory, I think it should instead be optional.

**Comment by johlju** [comment]
@bleakprestiger are you still on this issue?

**Comment by bleakprestiger** [comment]
Yes

**Comment by johlju** [comment]
@bleakprestiger I have not seen and PR for this for over a month. I will remove the assignment within a week unless I see a PR, so someone else can work on this.
