### ISSUE TITLE
Add README.md documentation for each resource

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#182]
In SharePointDsc there is a README.md for each individual resource that explains what that resource does. That is later used to automatically build documentation in the wiki (the parameters are take from the schema).
We don't have that documentation yet but I think we should start to prepare for it. Also those individual README.md files can be used to in more detail describe each resource. and help users.

Example of a README.md for the SPConfigWizard.
https://github.com/PowerShell/SharePointDsc/tree/dev/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard

Anyone in favor of doing this?

**Comment by luigilink** [comment]
Status of README.md documentation for each resource
- [x] MSFT_xSQLAlias
- [x] MSFT_xSQLAOGroupEnsure
- [x] MSFT_xSQLAOGroupJoin
- [ ] MSFT_xSQLDatabaseRecoveryModel
- [ ] MSFT_xSQLServerAlwaysOnService
- [x] MSFT_xSQLServerAvailabilityGroupListener
- [x] MSFT_xSQLServerConfiguration
- [x] MSFT_xSQLServerDatabase
- [x] MSFT_xSQLServerDatabaseOwner
- [ ] MSFT_xSQLServerDatabasePermissions
- [ ] MSFT_xSQLServerDatabaseRole
- [ ] MSFT_xSQLServerEndpoint
- [x] MSFT_xSQLServerEndpointPermission
- [x] MSFT_xSQLServerEndpointState
- [ ] MSFT_xSQLServerFailoverClusterSetup
- [ ] MSFT_xSQLServerFirewall
- [x] MSFT_xSQLServerLogin
- [ ] MSFT_xSQLServerMaxDop
- [ ] MSFT_xSQLServerMemory
- [ ] MSFT_xSQLServerNetwork
- [x] MSFT_xSQLServerPermission
- [x] MSFT_xSQLServerReplication
- [x] MSFT_xSQLServerRole
- [ ] MSFT_xSQLServerRSConfig
- [ ] MSFT_xSQLServerRSSecureConnectionLevel
- [x] MSFT_xSQLServerScript
- [x] MSFT_xSQLServerSetup
- [ ] MSFT_xWaitForAvailabilityGroup

**Comment by johlju** [comment]
Let's put this on hold for a while, to see if this is the way to go. But please discuss this even if it is on hold.

**Comment by johlju** [comment]
This was resolved in a recent PR.
