### ISSUE TITLE
Importing the Module into Azure Automation using Terraform fails

### ISSUE THREAD

**Issue by techdecline** [dsccommunity/SqlServerDsc#1873]
I tried to upload the module into Azure Automation using Terraform `azurerm_automation_module` resource as shown below:

```
azurerm_automation_module.aa_module["SqlServerDsc"] will be created
   resource "azurerm_automation_module" "aa_module" {
       automation_account_name = "myautomationaccoung"
       id                      = (known after apply)
       name                    = "SqlServerDsc"
       resource_group_name     = "myresourcegroup"

       module_link {
           uri = "https://www.powershellgallery.com/api/v2/package/SqlServerDsc/16.1.0"
        }
    }
```

When the configuration gets applied, an error indicates an issue with some missing type: [Microsoft.SqlServer.Management.Smo.Wmi.Service]

Complete Error Message:
```
Module Name: "SqlServerDsc") to finish provisioning: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while extracting activities from the module.  Internal error message: Unable to find type [Microsoft.SqlServer.Management.Smo.Wmi.Service]..
│    at Orchestrator.Activities.SetAutomationActivityMetadata3.Extract(String moduleName, ModuleLanguage moduleLanguage, String moduleFullPath, ActivitiesMetadataWorkflowExtension activitiesMetadataWorkflowExtension, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, ContentUriInfo contentUri, String storageUri, Int32 moduleVersion, HashSet`1 extractedOutputTypes)
│    at Orchestrator.Activities.SetAutomationActivityMetadata3.ExecuteInternal(CodeActivityContext context, String moduleName, ModuleLanguage moduleLanguage, String modulePath, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion)
│    at Orchestrator.Activities.SetAutomationActivityMetadata3.Execute(CodeActivityContext context)
│    at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
│    at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
```

Uploading the module using the Azure Portal works fine which confuses me even more.

**Comment by johlju** [comment]
Hmm.. It sounds like it imports the module after it uploads it. When SqlServerDsc is imported it expects to import module SqlServer (available from PowerShell Gallery) or SQLPS available after the SQL Server installation.
So you can probably solve it by first uploading the SqlServer module? 🤔

**Comment by johlju** [comment]
Hmm... Thinking of this it might be time to package SqlServer inside SqlServerDsc. I has not been done yet because the user to this point could choose to use either SqlServer module or SQLPS. But, since public commands and class-based resources are dependent on the SMO assemblies and SQLPS isn't available until SQL Server is installed, well that will be catch-22.

**Comment by techdecline** [comment]
I just tested the approach of uploading the SqlServer Module first and it is working now. As manual upload has been working from the start, I guess Azure Portal automatically checks for dependent modules whereas the Terraform resource does not.

**Comment by johlju** [comment]
Actually SqlServer is not specified as a dependent module in the module manifest of SqlServerDsc. That is because the user can choose between SqlServer or SQLPS. 

What I guess happened is that Terraform imported the module after upload whereas Azure Portal did not. But in the end using Azure Portal it would fail too since SqlServer (or SQLPS) module was not available. You would have need to upload SqlServer module from the Azure Portal too.

**Comment by gaelcolas** [comment]
Make sure there's no funky distribution rights before shipping it inside the module 🙃

**Comment by johlju** [comment]
Right, good thinking. I'm hoping it is getting open sourced eventually. I think there is a repo open, but only for issues right now. 🤔 
Better wait until it is properly open sourced.

**Comment by johlju** [comment]
@techdecline closing this issue as you solved the problem.
