### ISSUE TITLE
SqlServerDsc: Release assets on a GitHub release

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1923]
Look and see if we can add the nupkg as a release asset on the GitHub release similar to what is done here:

https://github.com/chocolatey-community/Chocolatey/blob/8975b7356aba181d333c766c6891f991af06847a/build.yaml#L163-L165

**Comment by gaelcolas** [comment]
The nupkg is default. Other files are optional 😁
