### ISSUE TITLE
Error while running the DSC_SqlSetup Module

### ISSUE THREAD

**Issue by mjbarron** [dsccommunity/SqlServerDsc#1937]
We are receiving the following error message while running this module.

Seems like SQL Gets installed, but then errors out and dies at this point

"module_version": "16.3.0", 
    "msg": "Failed to invoke DSC Set method: PowerShell DSC resource DSC_SqlSetup  failed to execute Set-TargetResource functionality with error mes****ge: Running the Get-Module cmdlet without ListAvailable parameter is not supported for module names that include a path. Name parameter has this element 'C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\SQLPS' which resolves to a path. Update the Name parameter to not have path elements, and then try again. ", 
    "reboot_required": false, 
    "verbose_set": [
        "Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.",

**Comment by johlju** [comment]
This was fixed in v16.3.1 and was reported in issue https://github.com/dsccommunity/SqlServerDsc/issues/1928.
