### ISSUE TITLE
Problem using dsc_sqlscript as a resource in puppet

### ISSUE THREAD

**Issue by emayoral** [dsccommunity/SqlServerDsc#1950]
Hi. I am trying to use a resource declaration of type dsc_sqlscript

I just want to check if some stored procedures already exist on the server, and if they do not, then create them.

Maybe I am doing it wrong. No matter what the get script returns, puppet seems to think that the resource already exists, and does not execute the set script. I have tried setting the validation mode to resource and property, I have tried with a get script which returns NULL (Select NULL), or simply with an empty get script. No luck, and I am out of ideas.

This is one of the resources I am having trouble with.

```
  dsc_sqlscript { 'Maintenance_scripts':
    validation_mode  => 'resource', # Maybe change property to resource ?
    dsc_instancename => 'MSSQLSERVER',
    dsc_servername   => $facts['networking']['hostname'],
    dsc_credential   => { user => 'mysa', password => Sensitive($sapassword) },
    dsc_testfilepath => 'D:\\Software\\SQLMaintenance\\test-MaintenanceSolution.sql',
    dsc_setfilepath  => 'D:\\Software\\SQLMaintenance\\set-MaintenanceSolution.sql',
    dsc_getfilepath  => 'D:\\Software\\SQLMaintenance\\get-MaintenanceSolution.sql',
    require          => File['d_software_sqlmaintenance'],
  }
```

What should the get script return so puppet decides that the resource is not in its desired state and executes the set script ?

Windows 2022 , SQL Server 2022, puppet 7.24 and sqlserverdsc 16.0.0-0-3

**Comment by johlju** [comment]
Test script determines if Set is run. See example here: https://github.com/dsccommunity/SqlServerDsc/blob/main/source/Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1
