### ISSUE TITLE
Table of Contents broken

### ISSUE THREAD

**Issue by ic248** [dsccommunity/SqlServerDsc#1956]
Hi,

The Table of Contents seems to be broken on the Puppet Forge page at https://forge.puppet.com/modules/dsc/sqlserverdsc/reference

Once you click on "Show remaining content" the following error appears. I understand you can go direct to the wiki but it's a pain.

```
Sorry, we were unable to render this content
We're working to resolve the issue, so please try again later.
```

Thanks
Ian

**Comment by gaelcolas** [comment]
This sounds like a Puppet forge issue, not a DSC Community one, or am I missing something?

**Comment by gaelcolas** [comment]
Yes, we don't maintain those.
Please let us know if there's something broken on our pages/resources, and we'll look into that.
