### ISSUE TITLE
Install-SqlDscServer with -PrepareImage errors when InstanceName is specified

### ISSUE THREAD

**Issue by derhally** [dsccommunity/SqlServerDsc#1960]
### Problem description

We are trying to syspref a VM image that include sql server.   I'm using the Install-SqlDscServer with the -PrepareImage option like

```shell
Install-SqlDscServer -PrepareImage -AcceptLicensingTerms -InstanceName 'MSSQLSERVER' -InstanceId 'MSSQLSERVER' -Features 'SQLENGINE' -MediaPath "D:\" -Force -Verbose
```

It errors with

```
Microsoft (R) SQL Server 2022 16.00.1000.06
Copyright (c) 2022 Microsoft.  All rights reserved.

SQL Server 2022 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2022 data processing and privacy controls, please see the Privacy Statement.
The following error occurred:
The setting 'INSTANCENAME' is not allowed when the value of setting 'ACTION' is 'PrepareImage'.

Error result: -2068578299
Result facility code: 1204
Result error code: 5
```

If i remove the instanceName switch,  it prompts me for InstanceName

```
cmdlet Install-SqlDscServer at command pipeline position 1
Supply values for the following parameters:
InstanceName:
```

### Verbose logs

```text
Provided all the logging I have in the description
```

### How to reproduce

Run the command (update the media path)

```Install-SqlDscServer -PrepareImage -AcceptLicensingTerms -InstanceName 'MSSQLSERVER' -InstanceId 'MSSQLSERVER' -Features 'SQLENGINE' -MediaPath "D:\" -Force -Verbose```

### Expected behavior

Only pass InstanceName when needed

### Current behavior

The cmdlet errors out.

### Suggested solution

not sure yet

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2022 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module version used

```text
16.3.1
```

**Comment by johlju** [comment]
That seems to be a bug, it is not mentioned in the docs either: https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16#prepare-image-parameters

It seems then that these lines should be removed:

https://github.com/dsccommunity/SqlServerDsc/blob/e52f4a52cdfa938fb739fa2f91b67ddd506ae740/source/Public/Install-SqlDscServer.ps1#L474

https://github.com/dsccommunity/SqlServerDsc/blob/e52f4a52cdfa938fb739fa2f91b67ddd506ae740/source/Private/Invoke-SetupAction.ps1#L580

Can you confirm that it works if you remove the line from each function?
