### ISSUE TITLE
`Get-SqlDscPreferredModule`: Should be possible to specify which version of the SqlServer module is imported

### ISSUE THREAD

**Issue by YaroBear** [dsccommunity/SqlServerDsc#1965]
Hello!

We have been using SqlServerDSC on systems that have the SqlServer v21.x.x powershell module installed for some time.

We have a requirement now where we need to have both SqlServer v21 and v22 installed on the system.

Is there any way we can specify which version of SqlServer module is imported in SqlServerDSC? We mainly use the `SqlScriptQuery` module and want to stick with using v21 for some time.

Great work, love what you guys have built! Thanks!

**Comment by YaroBear** [comment]
Maybe something like `Import-Module -Name "sqlserver" -RequiredVersion 21.1.18245 -Force` after `Import-DscResource -ModuleName SqlServerDsc` would override the sqlserver module in the current session? For example:

```
Import-DscResource -ModuleName SqlServerDsc

Import-Module -Name "sqlserver" -RequiredVersion 21.1.18245 -Force

Node $ServerName
    {
        SqlScriptQuery DatabaseSpecs {
        ...

```

**Comment by kilasuit** [comment]
It should be possible as per the docs on [Import-DSCResource](https://learn.microsoft.com/en-us/powershell/dsc/configurations/import-dscresource?view=dsc-1.1) 
This though depends on how you are making use of DSC as it's changed lots in recent years

Can you add some more environment details, like is this in Azure, are you using Machine Configuration at all etc etc so that can ensure to give the right advice here.

**Comment by YaroBear** [comment]
Certainly!

- We are using Azure Windows Server 2016+ VMs hooked up to Azure Automation Account as our pull server.
- We use DSC 1.1 and do not use Machine Configuration.

What part of the documentation of Import-DSCResource are you referring to?

Tracing the code from [SqlScriptQuery.psm1 ](https://github.com/dsccommunity/SqlServerDsc/blob/ca239e32c4aac76377185a088c1535ee43b177c8/source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1#L136)-> [InvokeSqlScript ](https://github.com/dsccommunity/SqlServerDsc/blob/ca239e32c4aac76377185a088c1535ee43b177c8/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L1912)-> [Import-SqlDscPreferredModule](https://github.com/dsccommunity/SqlServerDsc/blob/ca239e32c4aac76377185a088c1535ee43b177c8/source/Public/Import-SqlDscPreferredModule.ps1#L43) is where SqlServer module is imported.
I don't think running `Import-Module -Name "sqlserver" -RequiredVersion 21.1.18245 -Force` before the resource block will work, because SqlScriptQuery resource is going to override that import before Invoking the Sql script.

**Comment by johlju** [comment]
You cannot specify what version of SqlServer to import during compilation, or prior to compilation. As mentioned above the (latest installed) module SqlServer is returned by `Get-SqlDscPreferredModule` and is then imported by the command `Import-SqlDscPreferredModule`. 

So I think `Get-SqlDscPreferredModule` must be extended to support a specific version (probably by reading an environment variable `$env:SMODefaultModuleVersion`) and then make sure `Import-SqlDscPreferredModule` can import the specific module version returned by `Get-SqlDscPreferredModule`.

Happy to review a PR that resolves this.

**Comment by YaroBear** [comment]
Awesome, thanks for the help! I’ll see if I can cook up a PR here

**Comment by YaroBear** [comment]
While working on this, I found a bug in [these lines of code](https://github.com/dsccommunity/SqlServerDsc/blob/8047f7c51d5b7d7d5b11bd1b23fc771dd053b096/source/Public/Get-SqlDscPreferredModule.ps1#L97-L128). The version field isn't getting populated for SQLServer module as expected. Only SQLPS.

I can't tell exactly why. When I'm debugging, the code seems to exit prematurely on [line 116 ](https://github.com/dsccommunity/SqlServerDsc/blob/8047f7c51d5b7d7d5b11bd1b23fc771dd053b096/source/Public/Get-SqlDscPreferredModule.ps1#L116C16-L116C16) even though all the keys are present. No error codes.

My code changes are modifying this block of code anyway, just thought I'd bring it up.

Here is an output when I run this code on my machine:
```
Name      Path                                                                                        Version
----      ----                                                                                        -------
SqlServer C:\Users\yaroslav.berejnoi\Documents\PowerShell\Modules\SqlServer\22.0.49\SqlServer.psd1    
SqlServer C:\Users\yaroslav.berejnoi\Documents\PowerShell\Modules\SqlServer\21.1.18256\SqlServer.psd1 
SqlServer C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18256\SqlServer.psd1              
SqlServer C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18245\SqlServer.psd1              
SqlServer C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18147\SqlServer.psd1              
SQLPS     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1   130
```

I tried both PS 7.3.6 and 5.1.19041.3031.

**Comment by johlju** [comment]
It is `ContainsKey` that throws an error that is not caught for some reason. There were several issues, thanks for catching that. 
If you would like I can push these changes, or can you incorporate them in your change? What ever is easiest for you. 

Here is the working code:

```powershell
$Name = @('sqlserver', 'SQLPS')
$availableModule = Get-Module -FullyQualifiedName $Name -ListAvailable |
        Select-Object -Property @(
            'Name',
            'Path',
            @{
                Name       = 'Version'
                Expression = {
                    if ($_.Name -eq 'SQLPS')
                    {
                        <#
                            Parse the build version number '120', '130' from the Path.
                            Older version of SQLPS did not have correct versioning.
                        #>
                        (Select-String -InputObject $_.Path -Pattern '\\([0-9]{3})\\' -List).Matches.Groups[1].Value
                    }
                    else
                    {
                        $versionToReturn = $_.Version.ToString()

                        if ($null -ne $_.PrivateData -and $null -ne $_.PrivateData.PSData -and $null -ne $_.PrivateData.PSData.Prerelease)
                        {
                            if (-not [System.String]::IsNullOrEmpty($_.PrivateData.PSData.Prerelease))
                            {
                                $versionToReturn = '{0}-{1}' -f $versionToReturn, $_.PrivateData.PSData.Prerelease
                            }
                        }

                        $versionToReturn
                    }
                }
            }
        )

$availableModule
```

This correctly returns

```
Name      Path                                                                                      Version
----      ----                                                                                      -------
SqlServer C:\Program Files\WindowsPowerShell\Modules\SqlServer\22.0.49\SqlServer.psd1               22.0.49-preview1
SqlServer C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18080\SqlServer.psd1            21.1.18080
SQLPS     C:\Program Files (x86)\Microsoft SQL Server\160\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1 160
SQLPS     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1 130
```

**Comment by YaroBear** [comment]
I can incorporate them. Thanks!

**Comment by johlju** [comment]
Hey, I just saw that the line `if (-not [System.String]::IsNullOrEmpty($_.PrivateData.PSData.Prerelease))` seems redundant now? We are already checking that it is not null on the if statement above. 🤔
