### ISSUE TITLE
Configure SQL Server Agent Properties

### ISSUE THREAD

**Issue by SQLDBAWithoutABeard** [dsccommunity/SqlServerDsc#1980]
How do I use SQL Server DSC to configure Agent Properties please?  In particular, I'd like to use it to disable 'Limit size of job history log' (SQL Server Agent Properties | History).  This is the SQL to do the same:

USE [msdb]
GO
EXEC msdb.dbo.sp_set_sqlagent_properties @jobhistory_max_rows=-1, 
		@jobhistory_max_rows_per_job=-1
GO

Many thanks

**Comment by johlju** [comment]
There are no resource yet for this. Please send in a PR with a new resource, suggested name 'SqlAgentSettings`.

It is probably the properties `MaximumHistoryRows` and `MaximumJobHistoryRows ` from the class [JobServer](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.agent.jobserver). 

Can probably re-use code from the DSC Resource [SqlAgentAlert](https://github.com/dsccommunity/SqlServerDsc/blob/main/source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1) that uses the same class.

**Comment by johlju** [comment]
Submitted issue https://github.com/dsccommunity/SqlServerDsc/issues/1981 to track this. Closing this in favor of the new issue since it is using the correct issue template for a new resource.

@SQLDBAWithoutABeard Please consider sending in a PR to resolve issue https://github.com/dsccommunity/SqlServerDsc/issues/1981.

**Comment by johlju** [comment]
@SQLDBAWithoutABeard you should also be able to use SqlScript och SqlScriptQuery using T-SQL to configure this. See documentation for those DSC resources.

**Comment by SQLDBAWithoutABeard** [comment]
Thanks for your prompt response -sqlscript worked perfectly!
