### ISSUE TITLE
SAPwd challenge on setup

### ISSUE THREAD

**Issue by heaivilin** [dsccommunity/SqlServerDsc#1992]
Working within the SQLSetup config and trying to install with mixed mode authentication.  Per the documentation, this requires a PSCredential data type to work.  However, I seem to be missing something as this isn't working for me.  I've tried the following:

`$password = ConvertTo-SecureString 'BobsYourUncle123!@#' -AsPlainText -Force
     $sapwd = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'sa', $password
`

and/or

`[System.Management.Automation.PSCredential]$credz = Get-Credential`

The first would be in the script itself and the password would be replace by the password we get from our vault.  The 2nd was me passing it in as a variable, rather than having the code as part of the script.  

Neither work and I get the message below.  Following the link provided (https://go.microsoft.com/fwlink/?LinkId=393729), it is saying I need to configure keys, certs, thumbprints, etc., which seems excessive.  Is creating these certs and such for non plain text passwords the only way to do the SAPwd, or am I missing something obvious?  

Greatly appreciate the clarity around this.  

Nathan

```
_ConvertTo-MOFInstance : System.InvalidOperationException error processing property 'SAPwd' OF TYPE 'SqlSetup': Converting and storing encrypted passwords as plain text is not recommended. For more information on securing credentials 
in MOF file, please refer to MSDN blog: https://go.microsoft.com/fwlink/?LinkId=393729
At D:\SQL_DSC_Configuration.ps1:25 char:11
   SqlSetup
At line:341 char:16
     $aliasId = ConvertTo-MOFInstance $keywordName $canonicalizedValue
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    FullyQualifiedErrorId : FailToProcessProperty,ConvertTo-MOFInstance
WARNING: The configuration 'SQLInstall' is loading one or more built-in resources without explicitly importing associated modules. Add Import-DscResource –ModuleName 'PSDesiredStateConfiguration' to your configuration to avoid this me
ssage.
Compilation errors occurred while processing configuration 'SQLInstall'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
     throw $ErrorRecord
     ~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (SQLInstall:String) [], InvalidOperationException
     FullyQualifiedErrorId : FailToProcessConfiguration_
```

**Comment by johlju** [comment]
In production you should use certificates to encrypt and decrypt PSCredential object, otherwise they will be in clear text in the compiled MOF file.

For non-production environment you can override it by saying it should allow clear-text password.

See here for more information: https://learn.microsoft.com/en-us/powershell/dsc/configurations/configdatacredentials?view=dsc-1.1

**Comment by heaivilin** [comment]
> In production you should use certificates to encrypt and decrypt PSCredential object, otherwise they will be in clear text in the compiled MOF file.
> 
> For non-production environment (e.g lab environment) you can override it by saying it should allow clear-text password.
> 
> See here for more information: https://learn.microsoft.com/en-us/powershell/dsc/configurations/configdatacredentials?view=dsc-1.1

Thank you @johlju.  Follow-up question, and I haven't looked so if this is quickly searchable I apologize in advance for my laziness, but is the cert and such something that can be done inside DSC before we get to the sqlsetup part?

Thanks,
Nathan

**Comment by heaivilin** [comment]
ah, I see what you are saying.  Makes sense.  Really appreciate your help and support.  Time to talk with Windows and InfoSec to see how we can do this.  
Nathan

**Comment by heaivilin** [comment]
Thank you @johlju for the assistance.  Closing this task.
