### ISSUE TITLE
New parameter productcoveredbysa : Command proposal

### ISSUE THREAD

**Issue by sara921-spec** [dsccommunity/SqlServerDsc#2040]
### Command proposal

A new installation parameter, /PRODUCTCOVEREDBYSA, was introduced in SQL Server 2022 (16.x). This parameter indicates whether the provided product key (/PID=) license is covered under a Software Assurance or SQL Server Subscription contract, or just a SQL Server license.

<img width="490" alt="image" src="https://github.com/user-attachments/assets/e9d41e9a-1b5e-4099-9b73-71c399b54e53">

### Proposed parameters

Parameter | Mandatory | Data type | Description | Default value | Allowed values
--- | --- | --- | --- | --- | ---
productcoveredbysa | yes | String | Detailed description | None | true,False

"PRODUCTCOVEREDBYSA"

### Special considerations or limitations

We have the **new** parameter "PRODUCTCOVEREDBYSA" available for "Install-SqlDscResource" but currently there is no resource using that command and this is to add the parameter to the DSC resource "**DSC_SqlSetup**" for the SQL 2022 installs.

SqlServerDsc-16.6.0\source\DSCResources\DSC_SqlSetup

https://github.com/dsccommunity/SqlServerDsc/issues/1798

**Comment by sara921-spec** [comment]
Documentation : https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16

**Comment by johlju** [comment]
Suggest we add a boolean parameter `ProductCoveredBySA` to the existing logic in the resource SqlSetup. I think this should be fairly easy to add for someone in the community. 

>[!NOTE]
>_Suggest not use the new command `Install-SqlDscServer` as that would be a much larger undertaking, one that work was started for in PR #1912 but was not completed._
