### ISSUE TITLE
DSC_SqlPermission - "Undefined property permissionstate" error on Dsc versions >15

### ISSUE THREAD

**Issue by sara921-spec** [dsccommunity/SqlServerDsc#2048]
Not an issue mostly, a general question!

I have a Question on this resource "DSC_SqlPermission" (Also "DSC_SqlDatabasePermission") we are currently using Sqlserverdsc version 14 and while updating the version we found that this resource is no more available in the newer versions. looking to use dsc version "17"

Error msg:
"Undefined property **permissionstate**" can u help me with what is the alternate resource for this ?

**Comment by sara921-spec** [comment]
@johlju ^^ if u have any thoughts on this when u get a chance

**Comment by johlju** [comment]
In v15 SqlPermission was converted to a class-based resource and refactored. in v16 SqlDatabasePermission was converted to a class-based resource and refactored.

**Comment by johlju** [comment]
It looks like we forgot to add BREAKING entry in the releases notes for this for some reason. :/ At least I can't find any such entry.

See here how to use SqlPermission going forward: https://github.com/dsccommunity/SqlServerDsc/wiki/SqlPermission
