### ISSUE TITLE
SqlWindowsFirewall: When a firewall is disabled, this resource will not enable it

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#314]
**Details of the scenario you try and problem that is occurring:**
If you run thru the configuration, so the firewall rules are set, then go an disable the firewall rule. If you now run the configuration again, one expects the rule to be enabled again, but it doesn't. 

**The DSC configuration that is using the resource (as detailed as possible):**
```powershell
xSQLServerFirewall 'InstanceFirewallConfiguration'
{
    Ensure = 'Present'
    SourcePath = '\\fileserver.company.local\images'
    SourceFolder = 'SQL2016'
    InstanceName = 'SQL2016'
    Features = 'SQLEngine,Rs,Is,As'
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, SQL Server 2016, PowerShell 5.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by awickham10** [comment]
If I'm understanding this issue correctly then it looks like this is no longer a problem.

### Make sure Firewall rule is enabled
```powershell
Invoke-DscResource -name 'SqlWindowsFirewall' -Module 'SqlServerDsc' -Method Test -Property @{Ensure = 'Present'; SourcePath = '\\domain\share\SQL2017\Developer\'; Feature
s = 'SQLEngine'; InstanceName = 'MSSQLSERVER' }
```
InDesiredState = true

### Disable firewall rule
```powershell
Get-NetFirewallRule -DisplayName 'SQL Server Database Engine instance MSSQLSERVER' | Set-NetFirewallRule -Enabled 'false' -PassThru
```
Enabled = false

### Test
```powershell
Invoke-DscResource -name 'SqlWindowsFirewall' -Module 'SqlServerDsc' -Method Test -Property @{Ensure = 'Present'; SourcePath = '\\domain\share\SQL2017\Developer\'; Feature
s = 'SQLEngine'; InstanceName = 'MSSQLSERVER' }
```
InDesiredState = false

### Set
```powershell
Invoke-DscResource -name 'SqlWindowsFirewall' -Module 'SqlServerDsc' -Method Set -Property @{Ensure = 'Present'; SourcePath = '\\domain\share\SQL2017\Developer\'; Feature
s = 'SQLEngine'; InstanceName = 'MSSQLSERVER' }
```

### Test
```powershell
Invoke-DscResource -name 'SqlWindowsFirewall' -Module 'SqlServerDsc' -Method Test -Property @{Ensure = 'Present'; SourcePath = '\\domain\share\SQL2017\Developer\'; Feature
s = 'SQLEngine'; InstanceName = 'MSSQLSERVER' }
```
InDesiredState = true

**Comment by SphenicPaul** [comment]
Can this be closed?

**Comment by johlju** [comment]
Closing this as per @awickham10's comment. Thank you! 🙂
