### ISSUE TITLE
SqlSetup: Should not skip cluster validation tests

### ISSUE THREAD

**Issue by nabrond** [dsccommunity/SqlServerDsc#335]
**Details of the scenario you try and problem that is occurring:**
When installing a clustered SQL Server instance, the undocumented parameter ````/SkipRules='Cluster_VerifyForErrors'```` is automatically added to the setup arguments. This can introduce supportability issues when contacting Microsoft for support. See [this article](https://support.microsoft.com/en-us/help/953748/error-message-when-you-install-sql-server-2008-on-a-windows-server-2008-based-cluster-the-cluster-either-has-not-been-verified-or-there-are-errors-or-failures-in-the-verification-report.-refer-to-kb953748-or-sql-server-books-online) for more information. This option should be converted to a parameter to support all use cases.

**The DSC configuration that is using the resource (as detailed as possible):**
Any configuration which specifies 'InstallFailoverCluster' or 'CompleteFailoverCluster' for the parameter 'Action'.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2008R2+

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
We should add a parameter `SkipRules`.

We should allow it to pass serveral rules:
https://dba.stackexchange.com/questions/115377/skip-multiple-rules-during-sql-server-installation

Since these are undocumented this is blog and has a reference; https://deep.data.blog/2014/04/02/sql-2012-setup-rules-the-missing-reference/
