### ISSUE TITLE
SqlServerRole: Ensure Absent does not work

### ISSUE THREAD

**Issue by bodunjo** [dsccommunity/SqlServerDsc#351]
Ensure 'absent' property does not work on the xsqlserverole. 
I tried to revoke a server level permission using the resource, but wouldn't do it.

---- DELETE THIS LINE AND ABOVE ----

**Details of the scenario you try and problem that is occurring:**

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

**Comment by luigilink** [comment]
May be the fix suggested here #349 can work

**Comment by johlju** [comment]
@bodunjo I merged the fix in PR #349. Could you please be so kind to get the latest Dev branch and see if that solves your problem?

**Comment by SphenicPaul** [comment]
Can this be closed?

There's been no feedback from @bodunjo on this and it looks like the `DSC_SqlRole\Set-TargetResource` unit tests in [here](https://github.com/dsccommunity/SqlServerDsc/blob/master/tests/Unit/DSC_SqlRole.Tests.ps1) and the `DSC_SqlRole_Role2_RemoveMembers_Config` and `DSC_SqlRole_RemoveRole3_Config`, integration test configurations [here](https://github.com/dsccommunity/SqlServerDsc/blob/master/tests/Integration/DSC_SqlRole.config.ps1) cover variations of this scenario (i.e. remove role members and remove role).

**Comment by johlju** [comment]
Yes, let's close this since this issue is probably obsolete by now.
