### ISSUE TITLE
SqlServerDscHelper: Test-SQLDscParameterState: $PSBoundParameters does not include default parameters

### ISSUE THREAD

**Issue by randomnote1** [dsccommunity/SqlServerDsc#358]
**Details of the scenario you try and problem that is occurring:**
Test-SQLDscParameterState requires that $PSBoundParameters be passed in for the DesiredValues parameter. $PSBoundParameters does not include parameters that were passed with default parameters. Test-SQLDscParameterState should be updated to work with $MyInvocation.MyCommand.Parameters which will get all parameters.

`foreach ( $parameter in $MyInvocation.MyCommand.Parameters.GetEnumerator() )`
`{`
`    $parameterName = $parameter.Key`
`    $parameterValue = Get-Variable -Name $parameterName -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Value`
`}`

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
Think we label this as a bug instead of enhancement.

**Comment by johlju** [comment]
Test-DscParameterState should just evaluate parameters that should be enforced. There are circumstances when default values are just used to create an object and should not be enforced unless specified in the configuration. If a default value should be used in the evaluation then that value should be set in a hashtable before calling Test-DscParameterState.

The function Test-DscParameterState has been moved to the common module DscResource.Common but see not reason to move this issue over to that repo.

We also have a new pattern that is used by newer resources that tests both in Set and Test. That pattern does not use Test-DscParameterState, but a function that has been extended.

Closing this issue at this time.
