### ISSUE TITLE
SqlServerLogin: Set-SQLServerLoginPassword setting secure password string for method accepting only plain text version of password

### ISSUE THREAD

**Issue by ofaruk09** [dsccommunity/SqlServerDsc#361]
Causes logins to have incorrect password as the ChangePassword method requires the plain text version not the secure version:
    try
    {
        $originalErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Stop'
        
        $Login.ChangePassword($SecureString)
    }

This works however:

    try
    {
        $originalErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Stop'
        
        $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($pw)
        $UnsecurePassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
        $Login.ChangePassword($UnsecurePassword)
    }

**Comment by johlju** [comment]
Are you trying to change password on a SQL authentication login? Just want to verify that it might work for Windows authentication login, but not SQL authentication.

**Comment by ofaruk09** [comment]
Hi Johan

This is sql login. I have used the xSqlServerLogin resource to create a sql
login, but one of the functions which get called as part of
set-targetresource calls the set password function. Every time a
consistency check runs, the secure password as plain text overwrites the
correct password. And subsequently fails all other consistency checks
because the user is unable to login in with the correct password and fails
the password check.

**Comment by randomnote1** [comment]
@ofaruk09, I believe you are correct. I'm not sure how I missed that one!

We might want to add a parameter called 'DscEnsurePassword' which will ensure the password passed in via the configuration is set. This way the LoginMustChangePassword parameter can be set and allow the login's password to be changed after creation without resetting it on the LCM interval.
