### ISSUE TITLE
BREAKING CHANGE: SqlDatabaseRole: Create database role and grant/deny permissions

### ISSUE THREAD

**Issue by bozho** [dsccommunity/SqlServerDsc#782]
Hi,

I've been looking and I cannot find a resource to manage database roles and their permissions. xSQLServerDatabaseRole can only assign users to already existing roles.

Is there a resource to manage database roles and their permissions?

Thank you,
Marko

**Comment by johlju** [comment]
You are correct. xSQLServerDatabaseRole is lacking that functionality. xSQLServerDatabaseRole should use a similar schema as xSQLServerRole. `Ensure` should say if the group should exist or not, not if one user should be member or not.

**Comment by johlju** [comment]
This was fixed a while back. SqlDatabaseRole supports this now.
