### ISSUE TITLE
BREAKING CHANGE: SqlDatabasePermission: Remove database user creation, and add assigning permission to roles

### ISSUE THREAD

**Issue by bozho** [dsccommunity/SqlServerDsc#848]
xSQLServerDatabasePermission can currently only assign DB permissions to DB users. It will also create a DB user if it doesn't already exist.

In order to simplify the resource and enable further enhancements (e.g. assigning permissions to roles), I suggest that DB user creation/removal is only handled in xSQLServerDatabaseUser (issue #846) and that xSQLServerDatabasePermission is altered to only handle permissions on users and roles.

**Comment by johlju** [comment]
I agree to this. This will be a breaking change. This change should be merged once issue #846 is merged.

**Comment by johlju** [comment]
@bozho Does the schema.mof need to change for this? Can you propose a schema.mof?

**Comment by johlju** [comment]
This will be fixed in the next release.
