### ISSUE TITLE
SqlDatabasePermission: allows set permissions at the DB level but not object?

### ISSUE THREAD

**Issue by msurasky** [dsccommunity/SqlServerDsc#903]
**Details of the scenario you tried and the problem that is occurring:**
I am trying to configure xSQLServerDatabasePermission to implement a desired state that will REVOKE the public group EXECUTE access to a particular stored procedure (let's say xp_regread...). The TSQL would be like this:

REVOKE EXECUTE ON [xp_regread] FROM public

I thought that xSQLServerDatabasePermission resource would do it, but I'm struggling to make it work given that this resource only seems to grant permissions at the DB Level and not to individual objects in the database (as it is the case in here with xp_regread).

**The DSC configuration that is using the resource (as detailed as possible):**
Notice the dsc configuration does revoke EXECUTE from the public group, but there are no configuration elements in this configuration that refer to the object I want to target (it is assumed I'm doing this at the DB Level)
xSQLServerDatabasePermission RevokeGrant_SqlDatabasePermissions_Public
{
            Ensure = 'Absent'
            Name = 'public'
            Database = 'master'
            PermissionState = 'Grant'
            Permissions = 'Execute'
            SQLServer = '[MY_SERVER]'
            SQLInstanceName = '[MY_INSTANCE]'
}

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
OS: Windows Server 2008 R2
SQL Server: 2008 R2
PowerShell: 5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Not sure how to find that info, but I don't think it is relevant...

**Comment by johlju** [comment]
Unfortunately, there is currently no resource able to grant or revoke permission on objects. 
Extending this resource to take an array of objects, how would we distinguish that the user wants to set the object only, and not on the database.
Maybe we should add an new resource 'SqlDatabaseObjectPermission'.

Do you have any suggestions?

**Comment by msurasky** [comment]
Yes, I would think a new resource is probably what we need here. The name you suggest (SqlDatabaseObjectPermission) seems right to me.

I would love to implement this myself but unfortunately my experience on power shell and DSC is pretty much null... I just happen to use some of the PowerShell resources via a Puppet Module that implements this objects, and that's all.

Hope some day the xSqlServer get's extended with this resource. In the meantime, we are forced to do these types of changes via T-SQL invoke-sqlcmd statements unfortunately.

Thanks!

**Comment by johlju** [comment]
@XabiBeltza If you looking after a 'SqlDatabaseObjectPermission' that has only been proposed here. Please open an issue making a resource propsoal, and I will tag as help wanted and hopefully someone will run with ii

**Comment by johlju** [comment]
The resource SqlDatabaseObjectPermission was contributed a while back. Closing this as I think that resource will solve this, but if there is still a gap, please open a new issue.
