### ISSUE TITLE
SqlServerDsc: Speed up testing

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#979]
**Details of the scenario you tried and the problem that is occurring:**
We are getting close to the (AppVeyor) time limit of 60 minutes, currently around ~50 minutes. I suggest we look at steps to improve the code and the build worker.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
The AppVeyor build worker only has 4GB of memory so maybe we should stop and instances after we tested finished. I'm only raising this here as a reminder if integration tests starting to go slower, we could try that as an option. Use the Service resource to stop instances, and use the same to start up the instances before next integration tests.

I don't really know if this helps anything, just throwing it up here as a reminder.

**Comment by johlju** [comment]
Yesterday, for the first time, I hit the 60 minute window for running tests in AppVeyor. It took longer than normal to download the SQL Server media, so the tests could not finish in time. 
After I merged the latest integration tests in PR I will look if there is anyway to speed up the tests. Shaving off seconds here an there would help in the long run. If that is not possible then we might need to turn off some integration tests.

**Comment by johlju** [comment]
Maybe if we ask AppVeyor kindly maybe we can get more run time. But that would only help this repository, not the forked repositories. For example if a contributor connect their AppVeyor account to their forked repository, to test a change before sending in a pull request, they would hit the 60 minute window and might not be able to test their change.
So I thought, that if we could get more run time, then maybe we could add environment variables that tell if a test should run or not.
This can be done by the contributors, thru the AppVeyor interface, on the forked repository.

![image](https://user-images.githubusercontent.com/7189721/34638753-9f353a1a-f2d2-11e7-8282-8358fb2ec988.png)

**Comment by johlju** [comment]
There seems to be an issue with AppVeyor and SqlAG; the speed degrades farther and farther down in the test we got. See testing of `Get-TargetResource`.
Please not that the same test (the whole test) take 18 seconds to complete locally.

**Comment by johlju** [comment]
### Speed test

Run times from test run: https://ci.appveyor.com/project/johlju/sqlserverdsc/build/9.0.130.0
Total run time: 50 min 21 sec

#### Individual unit and integration test run time in AppVeyor

Type | Test | run time (~minutes)
--- | --- | --- 
Unit | SqlServerDscCommon | 0:14
Unit | CommonResourceHelper | 0:03
Unit | **MSFT_SqlAG** | **10:42**
Unit | MSFT_SqlAGDatabase | 1:32
Unit | MSFT_SqlAGListener | 0:09
Unit | MSFT_SqlAGReplica | 0:24
Unit | MSFT_SqlAlias | 0:19
Unit | MSFT_SqlAlwaysOnService | 0:03
Unit | MSFT_SqlDatabase | 0:03
Unit | MSFT_SqlDatabaseDefaultLocation | 0:03
Unit | MSFT_SqlDatabaseOwner | 0:02
Unit | MSFT_SqlDatabasePermission | 0:08
Unit | MSFT_SqlDatabaseRecoveryModel | 0:01
Unit | MSFT_SqlDatabaseRole | 0:05
Unit | MSFT_SqlRS | 0:12
Unit | SFT_SqlScript | 0:02
Unit | MSFT_SqlServerConfiguration | 0:01
Unit | MSFT_SqlServerDatabaseMail | 0:12
Unit | MSFT_SqlServerEndpoint | 0:05
Unit | MSFT_SqlServerEndpointPermission | 0:01
Unit | MSFT_SqlServerEndpointState | 0:02
Unit | MSFT_SqlServerLogin | 0:08
Unit | MSFT_SqlServerMaxDop | 0:04
Unit | MSFT_SqlServerMemory | 0:04
Unit | MSFT_SqlServerNetwork | 0:04
Unit | MSFT_SqlServerPermission | 0:02
Unit | MSFT_SqlServerReplication | 0:09
Unit | MSFT_SqlServerRole | 0:06
Unit | MSFT_SqlServiceAccount | 0:04
Unit | **MSFT_SqlSetup** | **9:14**
Unit | MSFT_SqlWaitForAG | 0:00
Unit | MSFT_SqlWindowsFirewall | 0:36
Integration | SqlServerDscHelper | 0:05
Integration | **SqlSetup** | **8:42**
Integration | SqlAlwaysOnService | 1:26
Integration | SqlDatabaseDefaultLocation | 0:25
Integration | SqlRS | 3:44
Integration | SqlServerDatabaseMail | 0:08
Integration | SqlServiceAccount | 2:27
Integration | SqlServerLogin | 1:29

**Comment by johlju** [comment]
I gave it a try running unit tests in a Windows container on the build worker. My attempt failed, but maybe there is a solution to it, see the issue https://github.com/PowerShell/DscResource.Tests/issues/204.

**Comment by johlju** [comment]
Another option is to remove the integration tests from the repository and create a separate repository for the integration tests using [DscConfigurations](https://github.com/PowerShell/DscConfigurations) templates.

**Comment by johlju** [comment]
I have update with the latest elapsed times using the new CI pipeline.

**Comment by Fiander** [comment]
Is this still actual?

[https://github.com/pester/Pester/issues/1318](url)
Does this have anything to do with it?

What version of Powershell does the pipeline use?

**Comment by johlju** [comment]
The problem is that certain tests are written to complex which results in extremely long run times. There are still some that need to be fixed but the worst has been resolved. It is fixed by not trying to reuse code in the tests but instead making context-blocks self-sustaining even if that means duplicating code. 

The pipeline is using Pester 4. All tests need to be refactored for Pester 5, so that is gonna take a while before latest Pester can be supported. The pipeline need to be modified as well to support code coverage in pester 5.

**Comment by johlju** [comment]
The unit tests was also speed up by running the unit tests in PowerShell 7. But SqlSetup still takes 60 minutes to run (last time I verified, might be quicker today).
